### ISSUE TITLE
MacOS client 6.1.3 can't add server in macOS High Sierra

### ISSUE THREAD

**Issue by BenArvin** [haiwen/seafile-client#1018]

**Comment by shoeper** [comment]
Please ask questions in the forum (https://forum.seafile.com/).

An issue without any information is of no help.

**Comment by killing** [comment]
I'm using High Sierra but I don't have this problem. Maybe it's a network issue. Please provide detailed information, screenshot etc. when asking questions.

**Comment by BenArvin** [comment]
Sorry for no more details, but problem sloved by update macOS High Sierra version to 10.13.1.
