### ISSUE TITLE
Seafile client shows error for a removed server

### ISSUE THREAD

**Issue by yatesco** [haiwen/seafile-client#1019]
Seafile client was syncing to three servers. One of those servers was unused and turned off. I then removed it from the client using the `[server.url]->disconnect` option in the seafile client.

However, the red triangle is still displayed and when I click on it, it shows the three servers (i.e. the two active servers plus the one removed server, which has the triangle next to it).

This is on macOS Sierra.

![screen shot 2017-11-14 at 11 16 14](https://user-images.githubusercontent.com/181469/32777254-5470072c-c92d-11e7-9ea7-39b41b338b0b.png)
![screen shot 2017-11-14 at 11 08 41](https://user-images.githubusercontent.com/181469/32777076-bd6146d4-c92c-11e7-9658-fe2b2c4a7d96.png)
![screen shot 2017-11-14 at 11 08 48](https://user-images.githubusercontent.com/181469/32777200-23689cc0-c92d-11e7-9963-75f506ac44d6.png)

**Comment by Bjarno** [comment]
Did you restart the client? I recently moved my Seafile installation to another domain name and the old server name was still visible, a simple restart solved it for me.

**Comment by yatesco** [comment]
Thanks for the hint @Bjarno - restarting it worked for me too. I will leave this open as it is a bug (even if we know now the workaround)
