### ISSUE TITLE
Client 3.0.2 still is connected after password change on Seafile web interface

### ISSUE THREAD

**Issue by HenriWahl** [haiwen/seafile-client#105]
Hi.
I just noted that the client 3.0.2 still is connected and gets information from Seafile after a password change in web interface. I refer to the list of libraries one can see in desktop client. I assumed that this list is web based and thus password dependant, but it seems not. Is this planned behaviour?

**Comment by liayn** [comment]
Solved with https://github.com/haiwen/seafile-client/issues/416#issuecomment-95159068 ?

**Comment by freeplant** [comment]
After user change the password, all the access tokens will be deleted in the server side. The client should not be able to access the server anymore. Maybe your server is not new enough.
