### ISSUE TITLE
 hope the owner of seafile will become an old foreigner at an early date

### ISSUE THREAD

**Issue by dudumao520** [haiwen/seafile-client#1052]
Chinese is not suitable for open source, not the spirit of open source, finally there was interest to share some information, no interest will not consider the information publicly available, if seafile's old club are foreigners, will not be so bad, even a client for windows compiled data are not, really absurd, hope seafile early the replacement of the boss

**Comment by shoeper** [comment]
Could you please stop writing shit in the issue tracker?

**Comment by dudumao520** [comment]
shit just for you
