### ISSUE TITLE
need to set interval sync to autostart sync

### ISSUE THREAD

**Issue by jgirardet** [haiwen/seafile-client#1059]
I've just installed seafle-client with a new fresh arch linux.
seafile-client and seafile-applet are autocompiled taking it in repo AUR.
It's local Ext4.
The version is 6.1.4
After launched some libraries don't start syncing unless I manualy click "pause sync"and juste after "start sync". But that is only for some libraries.
But after the "first sync" everything is ok.

I changed the interval from 0 to 1 and it corrects the bug.

I'v no idea how to solve this.

thanks
Jimmy

**Comment by shoeper** [comment]
You likely need to increase you inotify limit.

**Comment by jgirardet** [comment]
what do you mean ?

**Comment by shoeper** [comment]
https://lmgtfy.com/?q=inotify+limit
