### ISSUE TITLE
Client overwrites new local changes with old version from server

### ISSUE THREAD

**Issue by CoffeePocket** [haiwen/seafile-client#1062]
Often I will make changes to a document locally, save it, and within a second or two the Seafile client will download the OLD version of the file from the server and overwrite those NEW changes.

This is extremely annoying and potentially dangerous... The client should always treat the local versions of a file as authoritative, and update the server versions from the local ones!

I am using the MacOS client.

**Comment by shoeper** [comment]
Although this looks like an issue the following should definitely not be the case.

> The client should always treat the local versions of a file as authoritative, and update the server versions from the local ones!

But with just the information you've given it is impossible to find the cause. I have never experienced something like that and synchronize 1 TB within several libraries for multiple years now.

**Comment by CoffeePocket** [comment]
@shoeper Yes, I agree, "completely broken" did come to mind -- it was because I was experiencing similar behavior with Owncloud that I switched to Seafile in the first place. (Of course it could be something on my end, but I haven't been able to find anything like that. In the event it IS on my end, I would appreciate any help in finding it!)

What information could I provide that would be more helpful? The issue tends to arise in frequently changed text-based files, such as code, where I make many small changes and the file may be saved and revised several times per minute.

I have checked the (by now 170.5 MB!) seafile.log file but it gives no information about specific file changes.

**Comment by shoeper** [comment]
The software being used could be of interest.

I'm also not sure if the high change frequency is an issue, as I could 
imagine that it is not possible to decide which version is newer.


Am 1. Februar 2018 05:05:10 schrieb CoffeePocket <notifications@github.com>:

**Comment by CoffeePocket** [comment]
I'm using Seafile Client 6.1.0 on MacOS 10.12.6

**Comment by shoeper** [comment]
I mean the Software you use to save the files which are later handled wrong.

**Comment by CoffeePocket** [comment]
I use TextWrangler (which is an ordinary text editor, though it does some stuff internally to ensure changes are recovered if the program crashes) as well as MacOS TextEdit (which does some special stuff to write version control info for Time Machine, as well as some other special MacOS stuff to ensure changes are never lost if the program is closed or computer rebooted)

**Comment by CoffeePocket** [comment]
Following up on this... I tried pausing Seafile's auto sync while working. Then when I was finished, I re-enabled auto sync... Seafile promptly overwrote the (very considerable) progress I had made with the original file, leaving my changes in a conflict file!

This is for a single user use case, there is absolutely no reason it should have considered the server version to be newer or more authoritative...

**Comment by freeplant** [comment]
This basic problem can't happen. I guess it is related to some other special reason. We will not look into the problem.

**Comment by shoeper** [comment]
@freeplant I don't agree. These are the kind of issues you should take very serious, as it is what Seafile is supposed to be market leader (reliable sync).

**Comment by EhrmannS** [comment]
6 years later and I still have this problem (with a very precious text). Discouraged to use if you are in production.

**Comment by killing** [comment]
@EhrmannS Which version of client do you use? Can you provide more details about the issue you faced? For example, does it overwrite or just create a conflict file? Do you have collaborators for the library? And of course you should check the library history about what changes happened to the file. Also check the client's log for the operations taken when the issue happened. Without such information, there is no way to tell why it happens. It doesn't have to be a bug.

**Comment by EhrmannS** [comment]
I think it was not a bug after all. After researching elsewhere, I learned that the conflict file should contain the old file. I am not 100% sure, but it could well be. It would maybe help not to read here "We will not look into the problem" because that gives the feeling like the issue is not resolved and you know we find these issues when searching for a problem...
