### ISSUE TITLE
Shared libraries not in alphabetical order

### ISSUE THREAD

**Issue by thunfischbrot** [haiwen/seafile-client#1063]
All libraries, not only the most recently updated ones, are sorted by last change date. That makes it difficult to navigate and to find the right folder in a longer list.

I would expect that except for the libraries shown in recently updated the default would be to sort them alphabetically. Alternatively being able to select the sorting algorithm (date, name, synchronized status) would be great.

![2018-02-01 13_37_12-clipboard](https://user-images.githubusercontent.com/583358/35678959-95dd0848-0755-11e8-9273-35f3dcbf3c9e.png)

**Comment by shoeper** [comment]
One can easily find libraries using the searchbar at the top.

**Comment by thunfischbrot** [comment]
That is true. I expect that it would make the client easier to navigate on top of the search function.

**Comment by freeplant** [comment]
The libraries are displayed in the order of last modified time. We don't have a plan to add other sorting method yet.
