### ISSUE TITLE
library name change not reflected in the desktop client window

### ISSUE THREAD

**Issue by xerces8** [haiwen/seafile-client#1066]
If I rename a library in the web browser, then the change is not reflected in the desktop client (windows, version 6.1.3).

It there are later changes in the files, the popup shows the correct name, but the app still shows the old one.

In the example I renamed a library from "seafiletest_x12" to "seafiletest_x123", see screenshot:

![image](https://user-images.githubusercontent.com/15932333/35916630-4f8fd946-0c0b-11e8-8a98-9be6c50e65b5.png)

After a few minutes, the app window shows the new name too. But it should do it earlier, as the app clearly knows the new name (the popup).

**Comment by freeplant** [comment]
This has been fixed in the latest release.
