### ISSUE TITLE
Mac + Windows client  using wrong port

### ISSUE THREAD

**Issue by GiovanniK** [haiwen/seafile-client#1068]
Hi all,

I've been trying to figure out why my desktop clients aren't syncing and I think I found out why. I have seahub running on port 80 and seafile running on 81 (8082 is in use for another application).

[02/22/18 12:30:29] http-tx-mgr.c(1236): Bad response code for GET http://xxx:8082/protocol-version: 401.

The same error occurs on WIndows and Mac. My guess is that it's hardcoded somewhere.

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.

**Comment by MoritzJoekel** [comment]
I have this problem too! This isn´t a question, it´s a bug, surprise!

**Comment by shoeper** [comment]
@MoritzJoekel this is not bug - for sure. It's a misconfiguration.

@BPopcorn https://manual.seafile.com/deploy_windows/deploy_with_nginx.html - it is not possible that all components listen on the same port anyway. So a proxy - e.g. nginx - is the perfect solution. Not sure why its so hard to read the documentation ...

**Comment by shoeper** [comment]
Where does it say the client requests always on port 8082? That's wrong. Anyway, have a look at the nginx / Apache instructions and everything will be fine.

**Comment by BPopcorn** [comment]
I don't know about Apache / nginx but the manual clearly states that port 8082 will always be used for file syncing: 
![grafik](https://user-images.githubusercontent.com/32960728/44308085-10b98c80-a3af-11e8-8077-61ef681bfd53.png)

**Comment by MoritzJoekel** [comment]
`[08/18/18 15:49:41] http-tx-mgr.c(1257): Bad response code for GET http://cloud.danielri.de:8082/protocol-version: 401.
[08/18/18 15:49:41] clone-mgr.c(864): Transition clone state for dc4b78ba from [check server] to [error]: check server.
[08/18/18 15:49:42] clone-mgr.c(847): Transition clone state for dc4b78ba from [error] to [check server].`

Excerpt from the clientlog. It´s the same wheter the fileserver-port is another as 8082 or it is 8082.

**Comment by shoeper** [comment]
@freeplant you've to fix the documentation. It is wrong.

**Comment by shoeper** [comment]
Having a look at "8082/protocol-version" your SERVICE_URL is wrong. I won't debug it further but it is a configuration issue.

**Comment by shoeper** [comment]
So to summarize:

 1. Have a look at the setup with nginx and https
 2. Make sure SERVICE_URL and FILE_SERVER_ROOT are configured properly.

While the path /seafhttp is hardcoded for the seafile-server component in the client, the port is not and is part of FILE_SERVER_ROOT. Using nginx solves all the issues and allows adding TLS encryption (https) which also makes your install much more secure (without anyone capturing the traffic in a public wifi can takeover your session or even steal your password in cleartext - just to show one possible scenario).

**Comment by shoeper** [comment]
Don't know. Do you have the web settings enabled? Those settings overwrite the config, so FILE_SERVER_ROOT might have been overwritten from there.

**Comment by shoeper** [comment]
We talk about different things, now. Add ENABLE_SETTINGS_VIA_WEB = False to seahub_settings.py (and restart) and see if that helps.
