### ISSUE TITLE
Large file uploads loop

### ISSUE THREAD

**Issue by AlexVonB** [haiwen/seafile-client#1073]
# Summary

When uploading large files to selfhosted Seafile via the Ubuntu desktop client, sometimes the upload loops, resulting in multiple identical versions of the same uploaded file.

Other users experienced this, too:

- https://forum.seafile.com/t/seafil-finish-uploads-saving-then-upload-loop-again/3053
- https://www.reddit.com/r/selfhosted/comments/6x5paw/seafile_upload_loop_problem/
- https://groups.google.com/forum/#!topic/seafile/Xq4eHGWvKtc

# Steps to reproduce

Occurs randomly when uploading large files above appr. 800 MB.

- Seafile Server 6.2.3
- Ubuntu Seafile Client 6.1.2

# Expected behavior

Upload should happen once.

# Observed behavior

Upload restarts after every successful upload.

Thank you for your help.

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.

**Comment by shoeper** [comment]
Btw. the issue is that your timeouts are too low. The client gets a timeout and thinks the download failed and starts it again while seafile-server still indexes the file on the server and the upload succeeds.
