### ISSUE TITLE
Seafile-cli loses track of file when renamed via SFTP

### ISSUE THREAD

**Issue by 4ley** [haiwen/seafile-client#1076]
Seafile CLI 6.1.2 runs on Ubuntu Server headless 14.04.4 LTS

Renaming a file via SFTP causes Seafile to lose track of the renamed file. Seafile then removes the file on the Seafile server repository as it was deleted. The file is back on track after client restart.

**Comment by shoeper** [comment]
Pretty much looks like SFTP does not use standard APIs and thus Seafile is not getting a notification that the file was changed. Only thing you can do is to enable the sync interval for the library which I'm not sure of whether it exists in seafile-cli
