### ISSUE TITLE
Seadrive does not clean up cache properly

### ISSUE THREAD

**Issue by 4ley** [haiwen/seafile-client#1082]
Seadrive runs on an Ubuntu Server 16.04 without GUI as daemon.

The cache settings are standard as documented in the [Help Center](https://www.seafile.com/en/help/drive_client_linux/)

    [cache]
    size_limit = 10GB
    clean_cache_interval = 10

When I check for files which haven't been accessed in the last 24 hours

`find /opt/seadrive/seadrive-data/file-cache/ -atime +0 -type f -print0 | du -hc --files0-from - | tail -n 1`

I get a figure which is almost 30G. Now aren't these old file supposed to be cleaned at some point?

Is there a way to trigger the full cleanup proccess or some workaround, since the cache is filling up the drive and it's almost not possible to define a static disk size.

**Comment by shoeper** [comment]
The SeaDrive issue tracker is located at https://github.com/haiwen/seadrive-gui/issues
