### ISSUE TITLE
"Library" spelled wrong

### ISSUE THREAD

**Issue by arjones85** [haiwen/seafile-client#1085]
It has a Y in it, not an i

![image](https://user-images.githubusercontent.com/8582158/39247854-2413c246-4860-11e8-9bd9-04724f3713c1.png)

**Comment by 92lleo** [comment]
I guess the text is "Search libraries", but it got cut after the "i". The german translation is cut off, too:
![seafile](https://user-images.githubusercontent.com/12110344/39291133-4239a286-4932-11e8-8f2d-2bf116c8de72.PNG)
(where it should be "Bibliothek suchen")

**Comment by 92lleo** [comment]
This is fixed in 6.1.8, can be closed
