### ISSUE TITLE
Windows挂载盘客户端0.9.0无法上传含有子文件夹的文件夹

### ISSUE THREAD

**Issue by xsplus** [haiwen/seafile-client#1086]
**客户端**：Windows挂载盘客户端
**版本**：0.9.0
**问题**：上传含有子文件夹(1)的文件夹(2)及文件夹中所有文件的时候，只会成功上传1和2中的所有文件，但是文件夹(1)这个文件夹没有上传。

**Comment by Songxuewen** [comment]
桌面客户端也一样，无法上传文件夹

**Comment by freeplant** [comment]
使用最新版的服务器能解决这个问题。
