### ISSUE TITLE
Ubuntu PPA Build for 18.04 is missing

### ISSUE THREAD

**Issue by jankapunkt** [haiwen/seafile-client#1087]
Hi I hope this is the right place to open this issue as I am not registered on launchpad or somewhere else related to it so I can't notify anyone there.

Can you please add a build for Ubutu 18.04. / derivatives to the official PPA?

**Comment by shoeper** [comment]
apt-get install seafile-gui

**Comment by thotypous** [comment]
The PPA was updated. Packages for bionic are now available: https://code.launchpad.net/~seafile/+archive/ubuntu/seafile-client?field.series_filter=bionic
