### ISSUE TITLE
Preconfigured Shibboleth Url

### ISSUE THREAD

**Issue by igorb90** [haiwen/seafile-client#1088]
We are currently having troubles with the preconfigured Shibboleth Login Url.
When you launch the client with the preconfigured Url the login window just stays white, there is no prompt or something else.
Now what we discovered in the source code might be the issue:
https://github.com/haiwen/seafile-client/blob/02fab49b75cc4403cd51dc1be7ddeae6ced83fe0/src/ui/login-dialog.cpp#L420

This if statement:
        if (!getShibLoginUrl(server_addr, &url)) {
            return;
        }

only launches when there is no Url preconfigured but there is no return for when the Url is configured and valid.

**Comment by igorb90** [comment]
The return statement is probably not the issue. But the "server_addr" variable which reads the preconfigured Shibboleth Url is never used in that code block.

**Comment by shoeper** [comment]
@freeplant

**Comment by freeplant** [comment]
We will look into the problem

**Comment by igorb90** [comment]
Any update on this?

**Comment by lins05** [comment]
@igorb90 Thanks for reporting this! Should be fixed in https://github.com/haiwen/seafile-client/commit/b07393b4

**Comment by igorb90** [comment]
@freeplant @lins05 Thanks for fixing this! I can confirm it is working now.
