### ISSUE TITLE
unable to compile with Qt 5.11 (qt5_use_modules in CMakeLists.txt needs to be replaced)

### ISSUE THREAD

**Issue by macearl** [haiwen/seafile-client#1097]
In Qt 5.11 `qt5_use_modules` was removed (it was deprecated a long time ago) and should be replaced with `target_link_libraries`

However just changing the Lines containing `qt5_use_modules` in CMakeLists.txt does not seem to be enough as then there are other compile errors

**Comment by ignitedPotato** [comment]
The use of `target_link_libraries` also is discouraged by Qt docs: https://doc.qt.io/qt-5/cmake-manual.html#imported-targets

The CMakeLists.txt really could use some more work..

**Comment by scachemaille** [comment]
it's not how Interpret the docs.
they talk about to use imported target names instead of variable like as Qt5<Module>_LIBRARIES inside target_link_libraries. not the it's discouraged.

**Comment by konstantingoretzki** [comment]
Would be great to see the fix #1099 merged, if it works.

**Comment by fuelflo** [comment]
+1

**Comment by fuelflo** [comment]
#1099 has been merged and works, so this issue can be closed i guess.
