### ISSUE TITLE
silent uninstall

### ISSUE THREAD

**Issue by chanlists** [haiwen/seafile-client#1100]
Silent uninstall of the windows MSI package does not appear to work. Even if I try to uninstall using

`msiexec.exe /norestart /qn /x {...}`

it prompts me with a dialog box asking if I want to keep the account information. It should just leave the account information as is and uninstall silently. Thanks for looking into this,

Christian

**Comment by chanlists** [comment]
So I figured out a workaround. Here is the silent uninstall sequence (on a 32bit system, drop `Wow6432Node`):
```
reg add "HKLM\SOFTWARE\Wow6432Node\Seafile" /v "PreconfigureKeepConfigWhenUninstall" /t REG_SZ /d "1" /f
reg add "HKCU\SOFTWARE\Seafile" /v "PreconfigureKeepConfigWhenUninstall" /t REG_SZ /d "1" /f
msiexec.exe /norestart /qn /x {...}
reg delete "HKLM\SOFTWARE\Wow6432Node\Seafile" /v "PreconfigureKeepConfigWhenUninstall" /f
reg delete "HKCU\SOFTWARE\Seafile" /v "PreconfigureKeepConfigWhenUninstall" /f
```

**Comment by shoeper** [comment]
@freeplant I don't this has been solved. chanlists only provided a workaround. I think it is valuable for your customers when it works.

**Comment by J-U-B** [comment]
Even if the ticket is now closed for a while: **We definitely need this feature.**

We deploy the software with a client management system in an unattended mode. In case of an update the software will be uninstalled first. This does not work without a workaround.
I can't imagine that no one has a need for it.
