### ISSUE TITLE
Initial sub-folder when adding a new account

### ISSUE THREAD

**Issue by simontong** [haiwen/seafile-client#1110]
I'm in the process of migrating over from nextcloud to Seafile.

Seafile creates a subfolder inside the directory you pick to sync your files.

In order to work in what I need I have had to resort to the following:
```
/seafile/Seafile
/personal -> /seafile/Seafile (symlink to main seafile folder)
```

Would it be possible to have the files sync to the folder you pick rather than creating a sub directory inside that folder?

**Comment by shoeper** [comment]
This is possible by selecting "sync with existing folder".

**Comment by freeplant** [comment]
We don't have a plan to add such a feature.
