### ISSUE TITLE
Unable to run on Ubuntu 18.04

### ISSUE THREAD

**Issue by omkarnathsingh** [haiwen/seafile-client#1114]
I took latest code from master and also for the 2 deps. I get no error in cmake, make. But when I run, i get following error 
```
(seafile-applet:7251): Searpc-WARNING **: 20:03:32.015: pipe client failed to connect to server: No such file or directory

```

It appears multiple times continuously and client doesn't appear at all. Please look into matter. Thanks in advance.

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
