### ISSUE TITLE
[Bug] Interface theming issue on dark desktop theme

### ISSUE THREAD

**Issue by Redsandro** [haiwen/seafile-client#1124]
I'm on Linux Mint 18.3 (AKA Ubuntu 16.04 with Cinnamon) with the beautiful dark Mint-Y theme.

The Seafile Desktop Client is themed light, which is not a problem, but it should either style every element, or none at all.

![image](https://user-images.githubusercontent.com/1702193/44468705-1c62b880-a626-11e8-9aaa-f4ed9aeca2ec.png)

As you can see, now there is a Frankenstein mix of Seafile custom (light) elements and system (dark) elements.

**Comment by Redsandro** [comment]
It works fine with Linux Mint 19 (Ubuntu 18.04). 

Not going to close this issue though. People will be using Linux Mint 18 / Ubuntu 16.04 (LTS) for 3 more years.

**Comment by bkilinc** [comment]
I am using new installed LM 19.3 with a dark theme (adapta nokto) and I see same problem. So the problem persists in latest version of Linux Mint.

**Comment by hydrandt** [comment]
On Linux, with KDE, global theme "Breeze Dark".

In File Sync Errors, all text is unreadable: light-grey letters on white background:

![image](https://user-images.githubusercontent.com/11388094/76758961-4f970a80-67bd-11ea-8b95-65272f497a6a.png)

In the Cloud File Browser, the current path is not readable, unless you hover a mouse above the button:

![image](https://user-images.githubusercontent.com/11388094/76759079-91c04c00-67bd-11ea-9bd6-4dd9e7c06925.png)

**Comment by itreers** [comment]
Same issue KDE neon 5.19
![image](https://user-images.githubusercontent.com/15950861/94375439-47c90300-011c-11eb-9a05-4ff2053f3bb2.png)

**Comment by m4v** [comment]
Same in Kubuntu 22.04 LTS. Client version 9.0.4

**Comment by brainbow1** [comment]
same issue here in MX Linux 23.3 KDE also with the normal Breeze theme... please fix this :( 

> On Linux, with KDE, global theme "Breeze Dark".
> 
> In File Sync Errors, all text is unreadable: light-grey letters on white background:
> 
> ![image](https://user-images.githubusercontent.com/11388094/76758961-4f970a80-67bd-11ea-8b95-65272f497a6a.png)
> 
> In the Cloud File Browser, the current path is not readable, unless you hover a mouse above the button:
> 
> ![image](https://user-images.githubusercontent.com/11388094/76759079-91c04c00-67bd-11ea-9bd6-4dd9e7c06925.png)
