### ISSUE TITLE
[Feature Request] Continuously syncing file needs debounce

### ISSUE THREAD

**Issue by Redsandro** [haiwen/seafile-client#1125]
After Dropbox effectively decided to [no longer support Linux](https://www.dropboxforum.com/t5/Syncing-and-uploads/Dropbox-client-warns-me-that-it-ll-stop-syncing-in-Nov-why/td-p/290058), I've been looking for alternatives.

In the last weeks I've been testing both NextCloud and Seafile CE. NextCloud has trouble with a lot of small files, and Seafile is awesome for that.

However, one thing that I don't like is when a file is changing, it is being synced constantly. For example, I'm using Boostnote with a synced library as its storage. When editing notes, it will write changes to disk immediately. In NextCloud, it would sync every couple of minutes. but in Seafile, it will sync after every 3-4-5 characters typed.

This means that, if the Seafile server uses a git repository for it's data, that one note typing session results in 100+ commits with a few characters added in every commit, and 100+ versions in the version history. I don't know what will happen performance-wise and size-wise after a year.

Either way, this is unwanted. The file history becomes unusable this way. In a usability sense, you'd want to see considerable changes in history revisions.

---

So with varying regard to _performance_, _size_, and most importantly, _usability_, I propose that the sync clients could use a **debounce mechanism**.

For example: When a file is changed, wait for 5 minutes. Reset the timer on more changes. When no change was made in 5 minutes, commit the changed file to the Seafile server.

---

I also understand that it is desirable to have a _single_ change uploaded as quickly as possible. To facilitate that behavior, there could be a **hybrid debounce** mechanism that will sync the first change immediately, and start the timer.

**Comment by shoeper** [comment]
The current solution for this is to set a sync interval for the library. It has the drawback (and sometimes also advantage) that all files are scanned every x seconds (defined by the interval).

From my experience within the last 4 years the instant synchronization and a high number of versions is no issue, though.

**Comment by Redsandro** [comment]
@shoeper thank you, this helps with my immediate history overkill issue. Although it's not ideal.

I wonder if the debounce idea is feasible from a developer point of view.

**Comment by freeplant** [comment]
I'm sorry we don't have a plan to add this feature.

**Comment by Redsandro** [comment]
> I'm sorry we don't have a plan to add this feature.

@freeplant so leave this open?

Perhaps someone else wants to implement [something like this](https://github.com/petoem/inotify.cr/blob/master/examples/debounce.cr) at some point, or someone can put a bounty on this issue. Not if it's closed.

Unless you don't accept PR's, in which case I probably didn't read properly how exactly this project/repository works.
