### ISSUE TITLE
seafile data is too big: 50GiB for 109GiB of real data

### ISSUE THREAD

**Issue by lemmel** [haiwen/seafile-client#1144]
I use the seafile command line client and when I looked to the size I see that:
- my data size is: 109GiB
- size of seafile internal storage: 50GiB

I tried to restart the client but it did nothing.
Is that normal ? If it is, can I do something to avoid this ?

P.S. : 
- seafile client: 5.1.4
- my repository contains: 183364 files

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.

**Comment by lemmel** [comment]
Albeit I'm doubtful, I go !

P.S.: I'm doubtful because I did no settings/tweakings so I wonder about how I could mess up something.
P.P.S. : here the post on the forum (for people having encountered the same problem) https://forum.seafile.com/t/another-seafile-data-is-too-big-50gib-for-109gib-of-real-data/7536

**Comment by lemmel** [comment]
Hi !
I posted as asked on the seafile forum, but I got no help.

So I update this issue by providing more information.
I you don't want to re-open this ticket, at least please tell it on this post: otherwise I wouldn't decide between "nobody took notice of my new message" or "they still think there is no problem".

--------------

Now [copied from the forum](https://forum.seafile.com/t/another-seafile-data-is-too-big-50gib-for-109gib-of-real-data/7536/17) 

--------------


First I updated my client to the last version:
```
ii  libseafile0                           6.2.4                           amd64        Shared libraries for Seafile
ii  libsearpc1                            3.1.0                           amd64        SeaRPC library for Seafile client
ii  python-searpc                         3.1.0                           all          simple and easy-to-use C language RPC framework
ii  seafile-cli                           6.2.4                           amd64        Seafile command line interface.
ii  seafile-daemon                        6.2.4                           amd64        Seafile daemon
```
Secondly (copied from the forum):
```
xxxx@yyyy:~# seaf-cli status
# Name  Status  Progress

# Name  Status
lib1  synchronized
lib2  synchronized
```
A ncdu view:
```
  105,5GiB [######### ] /seafile-data                                                                                                                                                                              
   53,5GiB [#####     ] /seafile-client
```

my data being in the seafile-data, and the seafile’s data in seafile-client; I know I didn’t make a good use of my brain when I choose those names.

A view of
```
 /var/backups/seafile-client
          |------------seafile-data
                                |---------------seafile  (an empty directory)
                                |---------------seafile-data
```
And inside the last seafile-data (i.e. inside of /var/backups/seafile-client/seafile-data/seafile-data):
```
   53,5GiB [##########] /storage
   30,2MiB [          ] /index  
   48,0KiB [          ]  repo.db
   16,0KiB [          ] /deleted_store
   16,0KiB [          ]  clone.db
    8,0KiB [          ]  filelocks.db
e   4,0KiB [          ] /tmpfiles
e   4,0KiB [          ] /fs
e   4,0KiB [          ] /commits
    4,0KiB [          ]  transfer.db
    4,0KiB [          ]  config.db
    4,0KiB [          ]  branch.db
    4,0KiB [          ]  id
@   0,0  B [          ]  seafile.sock
    0,0  B [          ]  certs.db
```
A ps -ax view:
```
XXXX ?        Ss     0:01 ccnet --daemon -c /root/.ccnet
YYYY ?        Ssl    6:37 seaf-daemon --daemon -c /root/.ccnet -d /var/backups/seafile-client/seafile-data/seafile-data -w /var/backups/seafile-client/seafile-data/seafile
```
