### ISSUE TITLE
6.2.5 tarball

### ISSUE THREAD

**Issue by eolianoe** [haiwen/seafile-client#1145]
Hi,
As one of the packager of the seafile suite in the AUR, I already asked why the tarball change once released (https://github.com/haiwen/seafile-server/issues/27) and I understood the answer.

However, the 6.2.5 release was made a month ago but a few days ago the tarball changes again... Why a 6.2.6 release was not made ? 

Pinging at @lins05, @sunyuzhao who done the last commit.

**Comment by freeplant** [comment]
This is changed by an accident. We will change it back.
