### ISSUE TITLE
Client v7.0.0 reports sync error for Excel temporary files during save

### ISSUE THREAD

**Issue by liayn** [haiwen/seafile-client#1201]
When saving an Excel file the seafile client (v.7.0.0) reports an error:

![seafile temporary files](https://user-images.githubusercontent.com/222377/59367736-03560000-8d3d-11e9-92ef-f30f0bfba0af.jpg)

It seems this is a/the temporary file of Excel (version 1905), which is written, when saving a file.
Saving temporary files of MS Office should be disabled according to my settings of seafile.

**Comment by chpiter** [comment]
+1

**Comment by andrin55** [comment]
+1
have the same issue

**Comment by tlaguz** [comment]
+1

**Comment by andrin55** [comment]
Is there any progress regarding this issue?

**Comment by freeplant** [comment]
The new 7.0.1 client should have fixed the problem.

**Comment by liayn** [comment]
@freeplant Thanks for the info. Just to let you know that #1202 hits here again. My v.7.0.0 says it's up to date, even though the download page has the new version already available.

**Comment by liayn** [comment]
Seems to work with v7.0.1
Thanks!
