### ISSUE TITLE
Single sign on with Azure not possible

### ISSUE THREAD

**Issue by stefanfritsch** [haiwen/seafile-client#1216]
Hi,

we're trying to use single sign-on with **Microsoft Azure** but in the **Windows client** the login page ([https://login.microsoftonline.com/...](https://login.microsoftonline.com)) doesn't render correctly. I assume due to js issues:

Login fields missing in the Windows client:
![image](https://user-images.githubusercontent.com/7372706/64172991-88d9df80-ce56-11e9-8406-e02b18e1ae76.png)

In the browser it renders correctly:
![image](https://user-images.githubusercontent.com/7372706/64173006-92fbde00-ce56-11e9-98d3-c7f7b4ace4d2.png)

I can give you the URL of our server if you want to try it for yourself.

Thanks,
Stefan

**Comment by HolySephi** [comment]
Same as https://github.com/haiwen/seafile-client/issues/1258 - internal browser not redirecting to loginpage

**Comment by killing** [comment]
@stefanfritsch @HolySephi Which version are you using? Can you give us your URL for testing?

**Comment by HolySephi** [comment]
@killing Latest version of seafile-client (7.0.6) and drive-client from the website (1.0.11) both for windows with server 7.1.2 on centos 8.
Our URL is https://share.premier-experts.de
If you use SSO in a desktop browser you can see that the exact same window is showing up like the one that hangs in the client but the desktop browser then redirects to your company login site.
It looks like just the redirection is not working properly.

**Comment by stefanfritsch** [comment]
@killing sorry this reply took so long.

In my case the url is [https://cloud.statup.company](https://cloud.statup.company). The redirect seems to work fine. The login page is just not rendered correctly.

I currently can't guarantee that the page is up when you use it because the 7.1.x docker images miss the `requests_oauthlib` module and I haven't created private docker images with a fix yet.

Seafile version: 7.1.3
Client version: 7.0.7

**Comment by HolySephi** [comment]
@killing Can i assist you any further into debugging this? Maybe an idea on where to look?

**Comment by fr500** [comment]
I'm willing to assist for a solution here too

**Comment by killing** [comment]
We've reproduce the issue. It's only on Windows. It works properly on Mac and Linux clients. The reason is that the embedded browser in Windows clients are much older than other platforms. It's a build environment restriction. We need to change our build environment.

Note that SeaDrive 2.0 version on Windows works properly too, since it's built in a new environment.

**Comment by killing** [comment]
8.0.0 version should fix this issue.

**Comment by HolySephi** [comment]
Version 8 did fix this issue - thank you!
