### ISSUE TITLE
Ubuntu 19.10 install client failed

### ISSUE THREAD

**Issue by jianzs** [haiwen/seafile-client#1265]
I don't know why Ubuntu19.10 install client failed. Alert 404.
By editing the apt.conf and http_proxy to set proxy, but it didn't work for this problem.

![image](https://user-images.githubusercontent.com/20160766/72658832-9bae1480-39f1-11ea-816c-b868e951f4a5.png)

**Comment by Jianzs** [comment]
Ubuntu 19.10
