### ISSUE TITLE
Bug in Check for Update

### ISSUE THREAD

**Issue by carlstegmann** [haiwen/seafile-client#1282]
Hi,

the check for update function seems to be broken. After manual updating to the new version the check for update tells version 7.0.2 is the newest current available. See screenshot attached.
<img width="547" alt="Screen Shot 2020-04-03 um 12 44 13" src="https://user-images.githubusercontent.com/54107509/78352917-7e78f300-75a9-11ea-8c65-83b38ee7f8e7.png">

Kind regards,
Carl

**Comment by killing** [comment]
This is because we don't update the latest version number very frequently. Newer version may contains bugs. We usually keep stable versions for longer time.
