### ISSUE TITLE
Package for Ubuntu 20.04

### ISSUE THREAD

**Issue by darkdragon-001** [haiwen/seafile-client#1283]
Please package for Ubuntu 20.04 and publish via http://ppa.launchpad.net/seafile/seafile-client/ubuntu

**Comment by s1shed** [comment]
Yes please. Ubuntu 20.04 was just released and it is an LTS release.

In the meantime the seafile client for 18.04 (bionic) will work.

Sadly this is not the case for the SeaDrive client.  I filed [a bug for SeaDrive over here](https://github.com/haiwen/seadrive-gui/issues/215) .

**Comment by fukawi2** [comment]
Ubuntu 20.04 is the current LTS and will be used more and more very soon.

Is there anything we can do to help get this done?

**Comment by sbmw** [comment]
I just checked and there are actually updated instructions for Ubuntu 20.04 here.

https://download.seafile.com/published/seafile-user-manual/syncing_client/install_linux_client.md

Works great

**Comment by fukawi2** [comment]
This can be closed then....?

**Comment by sbmw** [comment]
I'd say so.  You just need to use the new seafile.com ppa instead of the launchpad one.
