### ISSUE TITLE
"View on cloud" ends up on 404 page when server address includes port number

### ISSUE THREAD

**Issue by mike386** [haiwen/seafile-client#1287]
Hi!

Steps to reproduce:
* Seahub instance is running on non-standard HTTP port (specifically `8000`, which is the default).
* In `seafile-applet`, user right-clicks any library and chooses "View on cloud" from context menu.
* Browser is being opened on `http://_address_:8000/client-login/?next=%3A8000%2Flibrary%2F_uuid_%2F_name_%2F&token=_token_` and then redirected to `http://_address_:8000/client-login/:8000/library/_uuid_/_name_/`.
* The later says "Sorry, but the requested page could not be found".

I believe that the port part should not be in "next" query parameter.

**Comment by rcoss** [comment]
Similar problem with Mac OS client versions 7.0.6, 7.0.9
Right click on  "View on cloud" for some library returns 404 with URL:
https://_seafile-server_/library/_uuid_/_library_name_/

error msg is: 
"sorry requested page not found: 
https://_seafile-server_/library/_uuid_/_library_name_/"

**Comment by killing** [comment]
This is fixed in latest version.
