### ISSUE TITLE
click windows client url to redirect to website will append port after url 

### ISSUE THREAD

**Issue by freemanke** [haiwen/seafile-client#1291]
Version: Windows client 7.0.7
If the server port is not default 443, The login url will append port info when we click windows client url to open web management page.
For example:
Server address: https://a.b.c:60001
click the desktop client url will redirect to https://a.b.c:60001/client-login/:60001/, lead to login fail.
![image](https://user-images.githubusercontent.com/1439128/81998183-6efac880-9684-11ea-8ba4-5f0a198f5d87.png)

**Comment by sergioamr** [comment]
I can confirm it has the same issue in the linux client.

**Comment by sergioamr** [comment]
Also, the option "view in cloud" will fail:
![image](https://user-images.githubusercontent.com/7228031/87600064-b127a100-c6eb-11ea-80d2-a946bc6c7434.png)

**Comment by freemanke** [comment]
Any plan to fix this bug @killing @freeplant @TimWolla

**Comment by TimWolla** [comment]
I'm not sure why I'm mentioned there, but I am not related to Haiwen in any way nor am I responsible for Seafile development.

**Comment by killing** [comment]
This is fixed in latest verison.
