### ISSUE TITLE
Debian repo down

### ISSUE THREAD

**Issue by mrjovanovic** [haiwen/seafile-client#1312]
Since yesterday, I cannot access/install Seafile, per the recommended instructions. `ping linux-clients.seafile.com` returns:

```
PING linux-clients.seafile.com (18.212.2.44) 56(84) bytes of data.
^C
--- linux-clients.seafile.com ping statistics ---
106 packets transmitted, 0 received, 100% packet loss, time 587ms
```

For Debian 10 users, the present workaround is to use seafile from `buster-backports`, however that is an older version.

**Comment by killing** [comment]
The repository works on our side. Ping doesn't work since it's blocked in firewall.
