### ISSUE TITLE
automatically start syncing when local dir becomes available (again)

### ISSUE THREAD

**Issue by unDocUMeantIt** [haiwen/seafile-client#1326]
i am using the client (7.0.10 on linux) with several libraries which are synced but the local device is not always available. in the client's configuration i have checked that syncing shouldn't be dropped if a local directory is unavailable. when that becomes the case, the client sets the respective library on pause. that's also what i would expect.

when the directory becomes available (again), however, the client doesn't seem to notice. the library remains on pause even though it could be synced with the server now. i can imagine use cases where this is the desired behaviour. but for my libraries i'd rather have seafile sync with the server as soon as the local directory is available, as this kind of "pause" is different from those where you manually stopped syncing. day in, day out, i must reactivate syncing for each library individually -- for accounts on multiple servers.

ideally, the client would allow to configure this behaviour (keep it paused vs. sync if possible) both as a global default and for each library individually; like a dropdown menu in the dialog that currently only configures the sync interval.

alternatively, to allow more situational control, when directories become available, you could raise a simple dialog with a table of all now available but still paused libraries, and offer checkboxes to decide whether you want to re-enable syncing now.

at the very least, the client should check not only with the server but also for the availablility of local dirs when you hit the reload-button.

**Comment by killing** [comment]
It'll be fixed in 8.0.1 version. This version will be uploaded this week.

**Comment by unDocUMeantIt** [comment]
seems to be fixed, thank you!
