### ISSUE TITLE
File is locked by another application

### ISSUE THREAD

**Issue by nukedone** [haiwen/seafile-client#1347]
This is the issue that happens in the seafile-client on windows. I have the latest seafile clinet 8.0.1 beta, although the issue was present in the stable version 7.

I don't know what this means, that the file (which file) is locked and is unable to create a library on the client machine. I tried to delete library and recreate it, but the same issue occurs. I send you the screenshot.

https://ibb.co/m0Ts4Gx

**Comment by killing** [comment]
You can ask usage issues on our forum. I'll close this issue here.
