### ISSUE TITLE
Build errors on Gentoo with glib 2.68.0

### ISSUE THREAD

**Issue by CaseOf** [haiwen/seafile-client#1349]
Hello the build is failing on Gentoo for some users: https://bugs.gentoo.org/777477

**Comment by CaseOf** [comment]
It seems to be an issue with glib 2.68.0 and specifically this commit:
https://gitlab.gnome.org/GNOME/glib/-/commit/552b8fd862061e74b5ad2ffe6a700f850a76f797

**Comment by CaseOf** [comment]
It seems that the pull request https://github.com/haiwen/seafile-client/pull/1346 could fix this issue

**Comment by CaseOf** [comment]
After testing, this PR did not solve the issue https://bugs.gentoo.org/attachment.cgi?id=692847 (build log)

**Comment by alebastr** [comment]
> After testing, this PR did not solve the issue https://bugs.gentoo.org/attachment.cgi?id=692847 (build log)

> Depends on: haiwen/libsearpc#57, haiwen/seafile#2428
> Important note: the change here won't even compile without the PRs above

You don't need that PR to fix the build though. Adding `add_definitions(-DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26)` should be sufficient with stable glib 2.68.0

**Comment by CaseOf** [comment]
It works, thanks!
