### ISSUE TITLE
Temp file too big when sync big library.

### ISSUE THREAD

**Issue by Chuanbin-Wang** [haiwen/seafile-client#1351]
I have a 2TB size images library.  And I try sync it to a other 3TB hard disk .
The Seafile client cache folder is set to D: in My PC , the size is 500GB.
After starting the sync, the cache grows as the progress grows. Eventually the entire volumn is filled with cache.

It is recommended to add an option when add a sync, for example: no keep cache. And when selected, to delete the already synchronized data immediately, except for the mandatory data

**Comment by Chuanbin-Wang** [comment]
![image](https://user-images.githubusercontent.com/76732400/113805107-780bf100-9792-11eb-85de-7309d2381476.png)
The error message in log file.

**Comment by killing** [comment]
If you have a single large file to sync, it's required that the cache folder to have enough space for the entire file. The file needs to be split into chunks and saved to the cache folder before uploading.
