### ISSUE TITLE
Platform support for macOS and Windows due to Qt 6 migration

### ISSUE THREAD

**Issue by Chilledheart** [haiwen/seafile-client#1393]
It seems Qt 6 migration will be coming soon ref to #1391. And I checked with the source code with 27a042405ea3d70e2765f3ac783eb4af2523c886 where it replies Qt 5.9's new feature and make the actual requirement of MacOS X to 10.10.

May I ask what's the status of the supported platforms including MacOS X/macOS and Windows (where Windows 7 support will be dropped in Qt 6 series)?

For the support platform on Qt 6, you can refer to the [official document](https://doc.qt.io/qt-6/supported-platforms.html).

Notable change is the dropped support for Windows 8.1 or below (including Windows 7) and MacOS X 10.13 or below.

<h3 id="linux-x11" style="margin: 1.5em 0px 0.75em; padding: 0px; border: 0px; font-size: 1.35em; vertical-align: baseline; font-weight: 300; color: var(--main-color-alt); font-family: &quot;Titillium Web&quot;, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(18, 18, 18); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://doc.qt.io/qt-6/linux.html" style="margin: 0px; padding: 0px; border: 0px; font-size: 21.6px; vertical-align: baseline; color: var(--link-color); text-decoration: none; transition-duration: 0.3s;">Linux/X11</a><a class="plink" href="https://doc.qt.io/qt-6/supported-platforms.html#linux-x11" title="Direct link to this headline" style="margin: 0px; padding: 0px 0px 0px 8px; border: 0px; font-size: 0.8em; vertical-align: baseline; color: var(--link-color); text-decoration: none; transition: opacity 180ms ease-in-out 0s; opacity: 0; font-weight: 600;"></a></h3><div class="table" style="margin: 0px; padding: 0px; border: 0px; font-size: 16px; vertical-align: baseline; overflow-x: auto; color: rgb(193, 193, 196); font-family: &quot;Titillium Web&quot;, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(18, 18, 18); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Distribution | Architecture | Compiler | Notes
-- | -- | -- | --
CentOS Linux 8.2 | x86_64 | GCC 10 (toolset) |  
openSUSE 15.3 | x86_64 | GCC 9 |  
SUSE Linux Enterprise Server 15 SP3 | x86_64 | GCC 10 |  
Ubuntu 20.04 | x86_64 | GCC as provided by Canonical, GCC 9.x |  
Generic Linux | x86 and x86_64 | GCC 9 |  

</div>

<h3 id="macos" style="margin: 1.5em 0px 0.75em; padding: 0px; border: 0px; font-size: 1.35em; vertical-align: baseline; font-weight: 300; color: var(--main-color-alt); font-family: &quot;Titillium Web&quot;, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(18, 18, 18); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://doc.qt.io/qt-6/macos.html" style="margin: 0px; padding: 0px; border: 0px; font-size: 21.6px; vertical-align: baseline; color: var(--link-color); text-decoration: none; transition-duration: 0.3s;">macOS</a><a class="plink" href="https://doc.qt.io/qt-6/supported-platforms.html#macos" title="Direct link to this headline" style="margin: 0px; padding: 0px 0px 0px 8px; border: 0px; font-size: 0.8em; vertical-align: baseline; color: var(--link-color); text-decoration: none; transition: opacity 180ms ease-in-out 0s; opacity: 0; font-weight: 600;"></a></h3><div class="table" style="margin: 0px; padding: 0px; border: 0px; font-size: 16px; vertical-align: baseline; overflow-x: auto; color: rgb(193, 193, 196); font-family: &quot;Titillium Web&quot;, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(18, 18, 18); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Target Platform | Architecture | Build Environment
-- | -- | --
macOS 10.14, 10.15, 11 | x86_64, x86_64h, and arm64 | Xcode 12 (11 SDK)

</div><br class="Apple-interchange-newline">

<h3 id="windows" style="margin: 1.5em 0px 0.75em; padding: 0px; border: 0px; font-size: 1.35em; vertical-align: baseline; font-weight: 300; color: var(--main-color-alt); font-family: &quot;Titillium Web&quot;, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(18, 18, 18); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://doc.qt.io/qt-6/windows.html" style="margin: 0px; padding: 0px; border: 0px; font-size: 21.6px; vertical-align: baseline; color: var(--link-color); text-decoration: none; transition-duration: 0.3s;">Windows</a><a class="plink" href="https://doc.qt.io/qt-6/supported-platforms.html#windows" title="Direct link to this headline" style="margin: 0px; padding: 0px 0px 0px 8px; border: 0px; font-size: 0.8em; vertical-align: baseline; color: var(--link-color); text-decoration: none; transition: opacity 180ms ease-in-out 0s; opacity: 0; font-weight: 600;"></a></h3><div class="table" style="margin: 0px; padding: 0px; border: 0px; font-size: 16px; vertical-align: baseline; overflow-x: auto; color: rgb(193, 193, 196); font-family: &quot;Titillium Web&quot;, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(18, 18, 18); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Operating System | Architecture | Compiler
-- | -- | --
Windows 10 (1809 or later) | x86_64 | MSVC 2019, MinGW 11.2 |  
Windows on ARM | arm64 | MSVC 2019 | Technology Preview

</div>

**Comment by darkdragon-001** [comment]
Please also add Linux arm64 (see #1425).
