### ISSUE TITLE
Feature request: SeaDrive macOS - native support for FileProvider

### ISSUE THREAD

**Issue by soliujing** [haiwen/seafile-client#1398]
Despite SeaDrive can run with additional kernel extention loaded, it would be essential to suport FileProvider API as native OS fille management system, like other public cloud client , DropBox / Box / OneDrive.

FileProvider Explained
https://developer.apple.com/documentation/fileprovider

Box support
https://support.box.com/hc/en-us/articles/4407737091219-Using-Box-Drive-on-macOS-File-Provider-Extension-FPE-mode

Any plan for SeaDrive?

**Comment by killing** [comment]
We'll look at this feature this year.

**Comment by soliujing** [comment]
KERNEL support being deprecated since macOS 12.3 and public release is approaching.
This issue needs higher priority, otherwise customers will be impacted :)

**Comment by killing** [comment]
I don't see any news about deprecating all kernel extensions. The only recent news is that kexts used by Dropbox and Box will be deprecated in 12.3. SeaDrive uses macFuse, which is a file system extension. It's not listed in the apple official page about deprecated extensions: https://developer.apple.com/support/kernel-extensions/ .

Anyway we're working on file provider already. Not sure how much efforts it will take to implement it. Hopefully we will support this before macOS 13 is released.

**Comment by zacnoo** [comment]
> Anyway we're working on file provider already. Not sure how much efforts it will take to implement it. Hopefully we will support this before macOS 13 is released.
Any update?

**Comment by killing** [comment]
3.0 version uses File Provider. This issue can be closed.
