### ISSUE TITLE
PreconfigureShibbolethLoginUrl no longer works in version 8.0.5

### ISSUE THREAD

**Issue by LenzWinkler** [haiwen/seafile-client#1399]
While in 7.0.10 the predefined Single Sign-On url is pre-entered on the first run, this is unfortunately no longer the case in 8.0.5.

HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Seafile "PreconfigureShibbolethLoginUrl=<URL>" (REG_SZ)

**Comment by killing** [comment]
According to the latest documentation: https://help.seafile.com/faq/#using-windows-registry you should use HKEY_LOCAL_MACHINE\\SOFTWARE\\Seafile . This is because in 8.0 version we updated the client to 64-bit executable.
