### ISSUE TITLE
Ubuntu does not support QT6

### ISSUE THREAD

**Issue by jhonny-oliveira** [haiwen/seafile-client#1401]
Hi!

I'm trying to build seafile-client 8.0.6 for Ubuntu focal +. Unfortunately the build breaks due to several changes part of commit f4582b32a10c85029dc4ceb3240a534f016aed62.

I managed to solve some of them, by putting back lines like: "#if (QT_VERSION >= QT_VERSION_CHECK(5, 14, 0))", but the task seems to be endless.

Can you please assist?

Thank you!
Jhonny Oliveira
https://xtradeb.net

**Comment by killing** [comment]
The current code only support Qt 5.15 or newer.

**Comment by jhonny-oliveira** [comment]
Dear @killing ,

Thank you for the answer.

Ubuntu Impish meets your requirements:
qtbase5-dev 5.15.2
qttools5-dev 5.15.2
qttools5-dev-tools 5.15.2
qtwebengine5-dev 5.15.6
libqt5webkit5-dev 5.212.0

However, I'm still unable to build the code due to the following error:

CMake Error at CMakeLists.txt:613 (FIND_PACKAGE):
  By not providing "FindQuaZip5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "QuaZip5", but
  CMake did not find one.

  Could not find a package configuration file provided by "QuaZip5" with any
  of the following names:

    QuaZip5Config.cmake
    quazip5-config.cmake

  Add the installation prefix of "QuaZip5" to CMAKE_PREFIX_PATH or set
  "QuaZip5_DIR" to a directory containing one of the above files.  If
  "QuaZip5" provides a separate development package or SDK, be sure it has
  been installed.

I'm using the system QuaZip5 with the patch you can find attached [0002-Don-t-use-bundled-QuaZip.txt](https://github.com/haiwen/seafile-client/files/8265305/0002-Don-t-use-bundled-QuaZip.txt). I suspect this patch needs to be updated in order to properly detect and use QuaZip. Attempting to use the bundled QuaZip results in several other errors.

Can you help?

Thank you!
Jhonny Oliveira
