### ISSUE TITLE
Error building seafile-client 8.0.8 on Ubuntu Jammy

### ISSUE THREAD

**Issue by jhonny-oliveira** [haiwen/seafile-client#1419]
Hi!

I'm getting this error while getting while building seafile-client 8.0.8 on Ubuntu Jammy:

./build/./src/rpc/rpc-client.cpp:1017: undefined reference to `searpc_client_call__int(_SearpcClient*, char const*, _GError**, int, ...)'
collect2: error: ld returned 1 exit status
make[3]: *** [CMakeFiles/seafile-applet.dir/build.make:3991: seafile-applet] Error 1

You can find the full log here:[build_log.txt](https://github.com/haiwen/seafile-client/files/9101214/build_log.txt).

Thank you for your help!

**Comment by jhonny-oliveira** [comment]
I was able to workaround the problem with: [0005-Fix_undefined_reference_to.txt](https://github.com/haiwen/seafile-client/files/9102171/0005-Fix_undefined_reference_to.txt).

Can you please confirm this is an acceptable fix?

**Comment by feiniks** [comment]
Hello, you need to fetch and compile the latest libsearpc.

**Comment by jhonny-oliveira** [comment]
Thank you! I will look into it.
