### ISSUE TITLE
Seafile Linux Client: Network Error SSL Handshake Failed

### ISSUE THREAD

**Issue by artforlife** [haiwen/seafile-client#1427]
I set up the Seafile via Docker container on a home server. It appears to work. I can log into the web interface and upload files. In addition, I was able to set up the client on MacOS successfully. It is able to sync files with the server.

However, when I attempt to set up the client on Ubuntu, I get the following error when trying to add the account:

`Network Error: SSL Handshake Failed`
What could be the cause of this and how can I fix it? Is this a bug with the Linux client?

**Comment by killing** [comment]
Please post usage questions on the forum.
