### ISSUE TITLE
Failed to connect to named pipe: All pipe instances are busy

### ISSUE THREAD

**Issue by DymOK93** [haiwen/seafile-client#1439]
The problem arises from a race condition between the creation of two named pipe instances in [`SeafileRpcClient::connectDaemon()` ](https://github.com/haiwen/seafile-client/blob/8c0548eb4537e04f83bfc7759ab450d338f7f156/src/rpc/rpc-client.cpp#L90) and the [creation of the daemon thread](https://github.com/haiwen/libsearpc/blob/e889dbcb507dc470da640d8b0efcc343715ad576/lib/searpc-named-pipe-transport.c#L237).

1. Client [creates a pipe instance](https://github.com/haiwen/seafile-client/blob/8c0548eb4537e04f83bfc7759ab450d338f7f156/src/rpc/rpc-client.cpp#L94) for `kSeafileRpcService`.
2. The daemon main worker [is trying to spawns a new thread](https://github.com/haiwen/libsearpc/blob/e889dbcb507dc470da640d8b0efcc343715ad576/lib/searpc-named-pipe-transport.c#L237) and may stuck in the kernel for some considerable time (for example, due to antivirus or EDR activity, or simply under heavy load)
3. The client sees that the connection is successful and [creates a second instance of the same pipe](https://github.com/haiwen/seafile-client/blob/8c0548eb4537e04f83bfc7759ab450d338f7f156/src/rpc/rpc-client.cpp#L106) for `kSeafileThreadedRpcService`.
4. If the time the worker daemon spends in the kernel exceeds 1-2ms (experimental), the client is **very** likely to get `ERROR_PIPE_BUSY` from `CreateFile()`.
5. In this case, the client [writes to the log "Failed to connect to named pipe: All pipe instances are busy."](https://github.com/haiwen/libsearpc/blob/e889dbcb507dc470da640d8b0efcc343715ad576/lib/searpc-named-pipe-transport.c#L352) and closes the instance from p.1.
6. Now daemon has spawned a new thread and [trying to read the pipe](https://github.com/haiwen/libsearpc/blob/e889dbcb507dc470da640d8b0efcc343715ad576/lib/searpc-named-pipe-transport.c#L269), but pipe is already closed.
7. `pipe_read_n()` [returns 0](https://github.com/haiwen/libsearpc/blob/e889dbcb507dc470da640d8b0efcc343715ad576/lib/searpc-named-pipe-transport.c#L548) for `ERROR_BROKEN_PIPE` so the daemon thread [silently terminates](https://github.com/haiwen/libsearpc/blob/e889dbcb507dc470da640d8b0efcc343715ad576/lib/searpc-named-pipe-transport.c#L275).
Then the situation repeats up to [20](https://github.com/haiwen/seafile-client/blob/8c0548eb4537e04f83bfc7759ab450d338f7f156/src/rpc/rpc-client.cpp#L96) * [16](https://github.com/haiwen/seafile-client/blob/837be8efd5cab4aea8fc1138ab91e93539a4e010/src/daemon-mgr.cpp#L21) times in total, after which the client [exits with an error](https://github.com/haiwen/seafile-client/blob/837be8efd5cab4aea8fc1138ab91e93539a4e010/src/daemon-mgr.cpp#L157).

The bug was already mentioned (but not actually fixed) in https://github.com/haiwen/seafile-client/issues/1284.

My solution is similar to the [Named Pipe Client example](https://learn.microsoft.com/en-us/windows/win32/ipc/named-pipe-client) on the Microsoft website: using `WaitNamedPipe()` if `CreateFile()` fails with `ERROR_PIPE_BUSY`.

**Comment by killing** [comment]
Thank you for the nice patch! It's been merged.
