### ISSUE TITLE
tunnel data transfers through HTTPS connection

### ISSUE THREAD

**Issue by elanfer** [haiwen/seafile-client#144]
Is it possible to tunnel file transfers through https (443)? So that we are not in need of Port 10001 and others. In some cases like hotel or company wifis the default data transfer port of seafile is blocked and you are only allowed to leave the network by 80 and 443.  Seafile Windows Client is not working properly and is not able to sync in such networks.

I think this feature is already implemented in iOS client because Filetransfer here is working.

**Comment by Chilledheart** [comment]
it is already landed
