### ISSUE TITLE
Bulk deleting files apparently causes the client to download files in a loop

### ISSUE THREAD

**Issue by gschnitzler** [haiwen/seafile-client#1449]
I sync a VSCode portable installation. It seems like after a recent update, VSCode deletes some 5000 files on startup. The Seafile client (v8 and v9) asks me if i want to bulk delete those files or go into settings to change the threshold. Clicking on the settings button makes the dialog box go away, so i can't choose yes/no anymore. Regardless of what I then set as a threshold, the client keeps 'downloading files' over and over. Deleting the seafile-data folder is the only thing i found to stop that behaviour.

**Comment by killing** [comment]
You should choose "Yes" or "No" in the dialog to tell the client to delete the folder or not. Opening the settings will by default choose "No". But you can still choose when this dialog appears the next time you remove many files.

**Comment by gschnitzler** [comment]
So far the theory. Clicking settings once (and maybe changing the threshold) prevents me from seeing this dialog ever again, as the client is stuck in a 'downloading files' loop from then on, from which it does not recover. So the client needs to be reset by deleting the seafile-data folder.

**Comment by killing** [comment]
This has been fixed. It's a bug for encrypted libraries.
