### ISSUE TITLE
"Failed to index file" [9.0.2]

### ISSUE THREAD

**Issue by politikundbildung** [haiwen/seafile-client#1466]
See [here](https://forum.seafile.com/t/failed-to-index-file-seafile-9-0-16-with-seafile-client-9-0-2-1/17994). 
The latest client update seems to have created a problem with syncing files, possibly related to special characters in the file path.

I'm happy to help troubleshoot this if you tell me how.

**Comment by feiniks** [comment]
@politikundbildung hello, we will look into it.

**Comment by politikundbildung** [comment]
The issue appears to be fixed in 9.0.2.1. Thank you!
