### ISSUE TITLE
Ubuntu上使用单点登录，提示“SSL握手失败”

### ISSUE THREAD

**Issue by zhang-guanghao** [haiwen/seafile-client#1490]
使用Ubuntu23.04操作系统，用点的登录方式，登录学校云盘。提示SSL握手失败。如下图。

![image](https://github.com/haiwen/seafile-client/assets/7907975/c1353c4b-0513-40f6-a051-97396966cb4d)

**Comment by killing** [comment]
这个可能跟学校的证书有关，不支持这个操作系统。可以联系学校解决一下。也可以试一下用浏览器访问是否能成功。

**Comment by zhang-guanghao** [comment]
> 这个可能跟学校的证书有关，不支持这个操作系统。可以联系学校解决一下。也可以试一下用浏览器访问是否能成功。

浏览器能访问成功。谢谢。我再试试其他办法吧
