### ISSUE TITLE
Tag GitHub releases

### ISSUE THREAD

**Issue by FriesischScott** [haiwen/seafile-client#1491]
Would it be possible for you to start making GitHub releases again? For some reason you stopped making them with `v6.2.4-testing`.

I maintain the `seafile` package for *Solus*. Without GitHub releases I have to manually check if new releases were made, because I can only subscribe to be notified of releases not tags. I am sure the maintainers of the `seafile` package for other distributions would appreciate this as well.

**Comment by killing** [comment]
Thanks for the suggestion. We'll update and maintain the releases from now on. For now we just use the vx.y.z tags to tag the releases.
