### ISSUE TITLE
seafile client failed in ssl verification

### ISSUE THREAD

**Issue by Makarov3821** [haiwen/seafile-client#1497]
I used to use seadrive 2.0.x in windows 10, and it worked fine. But I download the latest seafile client in a new windows 10 desktop, it complained:
![1](https://github.com/haiwen/seafile-client/assets/73375808/4a743fb2-6027-49a3-ac5d-3d5f4dc69d47)
I use Let's Encrypt certificate renewed lately, and I checked in my browser, which worked fine:
![2](https://github.com/haiwen/seafile-client/assets/73375808/f79b76a9-0fd0-48fb-892d-e1a9812fdaa4)
I have no idea why new client don't work, and I doubt it is libcurl to blame which does not trust Let's Encrypt cert. 
My log file looks like:
[11/20/23 13:34:59] libcurl failed to GET https://xxxxxxxx/seafhttp/protocol-version: SSL peer certificate or SSH remote key was not OK.

**Comment by killing** [comment]
This is usage issue. Please ask on the forum.
