### ISSUE TITLE
Seadrive + Windows Server 2019, Failed to delete file in explorer

### ISSUE THREAD

**Issue by rorschach-py** [haiwen/seafile-client#1500]
Windows Server2019 Desktop, Seadrive 3.0.7

Explorer warn and refuse to delete **any** file: 
`Invalid file handle. `

but deleting a file via command line works. Create/Copy/Move a file in Explorer also works well.

seadrive-gui.log:
`failed to read request from shell extension: ??????????`

Works well in Windows 10 LTSC and Windows Server2022.

**Comment by killing** [comment]
You can refer to this  FAQ: https://cloud.seatable.io/dtable/external-links/7b976c85f504491cbe8e/?tid=78wK&vid=0000&row-id=ZWA0DbigSKGWtnnGivkFmw

**Comment by killing** [comment]
Perhaps the error in Windows Explorer is not related to the message in seadriv-gui.log. Deleting a file doesn't involve the extension.

**Comment by rorschach-py** [comment]
I tried Seadrive 3.0.7 in Windows 10 LTSC, Explorer delete files on the same server with no error. After that, Explorer on Server2019 removed the placeholder file in time.

I'm sure files on server are not cropted, they're just several txt file with a few bytes.
I'll paste some screenshots later.

**Comment by feiniks** [comment]
Hello @rorschach-py , do you install third party antivirus? If you stop the antivirus software, are you able to delete the files under seadrive properly?

**Comment by rorschach-py** [comment]
> Hello @rorschach-py , do you install third party antivirus? If you stop the antivirus software, are you able to delete the files under seadrive properly?

I tried Windows Server2022 and everything works well, there maybe some bugs in Server2019.
