### ISSUE TITLE
[Bug/FR] Can't re-configure SeaDrive MacOS

### ISSUE THREAD

**Issue by maof97** [haiwen/seafile-client#1502]
Hello,

I added the wrong server URL to SeaDrive on MacOS and now I am unable to change it after the fact.
I dont find any settings and uninstalling and installing SeaDrive again will do nothing (no GUI asking for server address etc.). 

Also I found nothing about it in any documentation besides the following: 
https://cloud.seatable.io/dtable/external-links/7b976c85f504491cbe8e/?tid=78wK&vid=0000&row-id=Cw-0oXlRQ32wjClFYSbcAQ
`defaults delete ~/Library/Preferences/com.seafile.Seafile\ Drive\ Client.plist`
But even doing that doesnt change anything.

**Expected Behavior:**
I am able to change the SeaDrive settings or at least able to reset them after re-installing it.

**Actual Behavior**
The old config can't be changed.

Please fix / implement this or at least point me to the documentation where it states how this is achieved if I missed it.

Greetings and Happy Holidays
Martin

**Comment by killing** [comment]
You can remove the account and re-add it. There is no option to change the URL of an account.

**Comment by maof97** [comment]
>You can remove the account and re-add it.
How tho?
