### ISSUE TITLE
[seadrive] [windows] Unable to build seadrive daemon on windows

### ISSUE THREAD

**Issue by anndro** [haiwen/seafile-client#1503]
I am trying to rebuild seadrive.exe on windows. I am not sure where is the source code of seadrive. https://github.com/haiwen/seadrive-gui doesn't have daemon source code. When I check https://github.com/haiwen/seadrive-fuse it seems this repo is only for linux. I am unable to build this repo on windows. Please can you help me on that?

**Comment by killing** [comment]
SeaDrive is not open source. So you cannot build for Windows.
