### ISSUE TITLE
macOS menu bar icons

### ISSUE THREAD

**Issue by davidrudlstorfer** [haiwen/seafile-client#1505]
Similar to #1269 I'd like to once again report about the menu bar icons in macOS within the Seafile drive client. Currently, Seafile is the only app I use which does not align with the remaining menu bar icons concerning the style.

Light Mode
<img width="520" alt="Screenshot 2024-01-02 at 12 04 03" src="https://github.com/haiwen/seafile-client/assets/106265296/81b07f5e-6437-402a-bbc6-b80177259675">

Dark Mode
<img width="520" alt="Screenshot 2024-01-02 at 12 04 14" src="https://github.com/haiwen/seafile-client/assets/106265296/d8a24eb4-f3e9-4caf-9a9c-6e42cf7e0024">

According to the latest macOS versions, the icon should stay white at all times and do not switch to black. Solutions would include to either let the user switch between different menu bar icons or update the icons to only use the white one.

Thanks in advance!

**Comment by davidrudlstorfer** [comment]
If I am not mistaken the logic regarding dark mode could be removed entirely as currently no distinction between the dark and light mode is made on macOS

https://github.com/haiwen/seafile-client/blob/189d1a48f4c75a0baaae2ea6e73d9c25087e117f/src/ui/tray-icon.cpp#L446C1-L474C71

**Comment by killing** [comment]
Thanks we'll look into this again.

**Comment by davidrudlstorfer** [comment]
I discovered one more thing - within the current macOS releases (Sonoma, Monterey) the system's menu bar icons actually depend on the background color.

Therefore, the optimal thing would be a toggle to individually choose the icon or get the icon color from the system in some way.

**Comment by killing** [comment]
This is fixed in https://github.com/haiwen/seafile-client/pull/1508
