### ISSUE TITLE
[New Feature Request] Seafile Client - Placeholder files and on-demand syncing

### ISSUE THREAD

**Issue by dperenic** [haiwen/seafile-client#1514]
I really like functionality of OneDrive/Dropbox etc, where all my files are in cloud, but only placeholders (and some files) on my hard drive. Notebooks don't have large hard drives and my working environment is not that big. But any file I need, will be downloaded ad-hoc. I can also sync certain folders to be always available locally.

Syncing/Unsycing whole libraries in Seafile is not convenient nor practical. Often I may only need a file, not whole library. Besides, I cannot browse file structure as files are not visible until they are fully synced.

**Comment by killing** [comment]
You can install SeaDrive client.

**Comment by dperenic** [comment]
@killing I don't consider this alternative solution. SeaDrive is nice on a Desktop, always connected. I use placeholders a lot on the notebook. Download the files I will need on the plane. When I land and connect to Wi-Fi everything is synced again. At the same time, my Surface does not have terabytes of storage to use SeaFile Client. Placeholder concept really works well for such use cases.
