### ISSUE TITLE
UI : Merge new and existing directory to sync a library

### ISSUE THREAD

**Issue by camlafit** [haiwen/seafile-client#152]
Hi

Now I've some differents users, I see a mistake usage. When people want synchronize a library, they don't see difference between target a new directory and an existing directory.
It's looks possible to merge on one behavior. If desktop client propose to target directly the directory where store data library.

If it's a new directory, the directory is empty and only data must retrieve from server. 
If it's an existing directory, client cant detect this state and do synchronize between local computer and server.

Note : As is some people can choose a specific directory different from library name, case encountered when people share same named libraries as "My Documents", "Personal", ..

With this behavior, UI usage will be more intuitive.

**Comment by Jip-Hop** [comment]
I agree, this case could be handled more intuitively.

**Comment by camlafit** [comment]
Hi

After client update, i see merge with theses behaviours. Now we have only to target a repository if library and repository are same then it's merged.

Problem is with naming, a library can have a different name as this local repository. Then now for any reason if a sync was last and names are differents, we can't renable sync.

Idea would be a checkbox : "sync this repository with his content"

**Comment by shoeper** [comment]
This is possible as it was before. You can enable it in the extended settings. It is only there because it wasn't intuitive enough for the average user but may be usefull for more advanced users.

**Comment by camlafit** [comment]
Hi
I propose this change, it's french version but you can see two changes : 
* First **import in** term when we want add library in a directory in this example "/home/km" selection give "/home/km/pm" library sync
* Second a check box to specify "import this content directory in the library" , "/home/km" will be merged to PM library.


![seafile-select-repository](https://cloud.githubusercontent.com/assets/209915/8902604/6ee3bb7a-3452-11e5-830f-76e205fdf6b8.png)

**Comment by shoeper** [comment]
If that folder exists files will always be merged by default.

**Comment by camlafit** [comment]
Hi

yes, my example is bad. The use case is store PM library in existing
repository "/home/km/minerepo/"

In this case checkbox looks better as UI evolve.

**Comment by shoeper** [comment]
Right, got it. Nice idea imho.
