### ISSUE TITLE
Symlinks in seafile-ignore.txt

### ISSUE THREAD

**Issue by de-es** [haiwen/seafile-client#1520]
I sync my Firefox profile with Seafile client. There are some temporary files which should be ignored in this context, e.g. the `lock` file/symlink:

```
lrwxrwxrwx  1 user user       13  6. Mär 16:54 lock -> 127.0.0.1:+16
```

It is in my library specific `seafile-ignore.txt` with

```
*/lock
```

Even though there always has been a stat error in `seafile.log`

```
[03/06/24 17:21:36] sync-mgr.c(603): Repo 'Firefox' sync state transition from 'synchronized' to 'committing'.
[03/06/24 17:21:36] repo-mgr.c(1734): Failed to stat /home/user/.mozilla/firefox/k7ic3mz1.default-release/lock: No such file or directory.
```

it was working like this for years without a visible error in the client itself.

Since 9.0.5 the client is complaining about the symlink in `File Sync Errors` with the error message `Error when indexing`.

Is there any chance to ignore this symlink again?

**Comment by feiniks** [comment]
> I sync my Firefox profile with Seafile client. There are some temporary files which should be ignored in this context, e.g. the `lock` file/symlink:
> 
> ```
> lrwxrwxrwx  1 user user       13  6. Mär 16:54 lock -> 127.0.0.1:+16
> ```
> 
> It is in my library specific `seafile-ignore.txt` with
> 
> ```
> */lock
> ```
> 
> Even though there always has been a stat error in `seafile.log`
> 
> ```
> [03/06/24 17:21:36] sync-mgr.c(603): Repo 'Firefox' sync state transition from 'synchronized' to 'committing'.
> [03/06/24 17:21:36] repo-mgr.c(1734): Failed to stat /home/user/.mozilla/firefox/k7ic3mz1.default-release/lock: No such file or directory.
> ```
> 
> it was working like this for years without a visible error in the client itself.
> 
> Since 9.0.5 the client is complaining about the symlink in `File Sync Errors` with the error message `Error when indexing`.
> 
> Is there any chance to ignore this symlink again?

Hello @de-es , the error `Error when indexing` is a bug, which will be fixed in the next release.

**Comment by de-es** [comment]
Did a rebuild with https://github.com/haiwen/seafile-client/pull/1518 and the errors are gone.
