### ISSUE TITLE
Feature request: Search box in the Cloud File Browser

### ISSUE THREAD

**Issue by inacioverto** [haiwen/seafile-client#1527]
Hi,

At times, I find myself needing to locate a file within a Library that hasn't been synced to my PC. However, the Cloud File Browser lacks a search box, necessitating a visit and login to the webpage for searching.

Is it possible to incorporate a search box into the Cloud File Browser?

**Comment by killing** [comment]
If you use Pro Edition server, there will be a search box in the client.
