### ISSUE TITLE
Seafile Flatpak-Client 9.0.6 without SSO support?

### ISSUE THREAD

**Issue by r4dh4l** [haiwen/seafile-client#1552]
Hi,

under Manjaro I use flatpak/flathub to install Seafile: https://flathub.org/apps/com.seafile.Client

Unfortunately there is no Single Sign-on login method:

![Screenshot_2024-07-30_23-48-43](https://github.com/user-attachments/assets/8c649a7a-76e4-40d5-81f7-1cd9e73dcb2e)

**Comment by killing** [comment]
This should be a package issue of the flatpack package. Since it's not maintained by us we cannot fix it. Please contact the provider of this package.
