### ISSUE TITLE
AppImage on Linux - Provide a way for automatic updates

### ISSUE THREAD

**Issue by deragon** [haiwen/seafile-client#1553]
I understand the reason why going forward, only AppImage will be supported on Linux.

However, from a user's point of view, loosing the ability to have automatic updates is less than ideal.  Please provide a mean for automatic updates using AppImage.

This issue is somewhat related to issue [Flatpak support?](https://github.com/haiwen/seafile-client/issues/847).

**Comment by killing** [comment]
From 9.0.8 version on, the AppImage package will support using AppImageUpdate to check for updates.
