### ISSUE TITLE
Seafile client fetches profile picture over http even though server link is https

### ISSUE THREAD

**Issue by bertvandepoel** [haiwen/seafile-client#1554]
I noticed after installing a new PC with Seafile Client 9.0.6 that it would start with a tick on the tray icon and would then change to a v. It would sync fine but still show a problem in the tray and in the left bottom corner it would indicate a connection problem. Looking at the logs I noticed the following:
`[28-07-24 14:49:05][api] network error for http://my_seafile_server/media/avatars/default.png: Connection refused`

This is weird because my server is configured in the seafile client with https. Therefore my server doesn't have port 80 open. Once I opened up port 80 with a redirect to https, the problem went away.

My other devices never reported any problems, but they're using Seafile Client 8 still. I'm therefore guessing this is a regression bug where some code was rewritten and somehow http got hardcoded somewhere.

**Comment by killing** [comment]
What address do you use when you create the account on the client? It it http or https? If you use http in the account, the requests will be sent in http.

**Comment by bertvandepoel** [comment]
This is a relatively new install that never had access to port 80. I used the docker image and https to create the account.

**Comment by imwhatiam** [comment]
@bertvandepoel Hello, what is your SERVICE_URL  configuration? Is it starts with https?
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/e1bf0df3-13ce-43ff-b94d-cfde81cde758">

**Comment by bertvandepoel** [comment]
Oh that's odd. It's indeed http, even though the FILE_SERVER_ROOT is with https. I wonder how that could've happened when I installed completely over https.

**Comment by imwhatiam** [comment]
The `SERVICE_URL` needs to be configured manually; it will not be automatically configured based on whether you have deployed HTTPS.
