### ISSUE TITLE
Not uploading files / synchronizing with seafile-client 9.0.8.

### ISSUE THREAD

**Issue by dassystem** [haiwen/seafile-client#1566]
I cannot upload files with seafile-client 9.0.8. Connecting to the server and downloading files is working.

While my investigations I updated the server to newest version (latest / 11.0.12) but still was not able to upload files via the client. Upload per web interface and Android app were working so it must have been the desktop client. On my old laptop that I don't use that much I still had seafile-client 9.0.6 installed and it was working.

With AppImage version seafile-client 9.0.7 I can confirm the issue does not occur.

Edit: I'm taking about Linux version. Previously I have installed 9.0.8-1 via the AUR on Manjaro Linux.

**Comment by feiniks** [comment]
Hello @dassystem, currently, for seafile client, we only provide AppImage type package, you can try to download the latest version of AppImage package from [here](https://s3.eu-central-1.amazonaws.com/download.seadrive.org/Seafile-x86_64-9.0.8.AppImage). The seafile client downloaded through AUR should be maintained by the community, you can feedback this issue to AUR community.

**Comment by hp-pepster** [comment]
Same problem here. Seems to be a problem with curl version 8.10.0-1, currently shipped e.g. by manjaro
Arch already has curl 8.10.1-1, which fixes this problem for me.

**Comment by feiniks** [comment]
Hello @hp-pepster , do you mean that the client of AppImage will not be able to upload files either? AppImage itself packages libcurl as a dynamic library, so it shouldn't use the system's libcurl. And seafile 9.0.7 and 9.0.8 use the same packaging environment. When you upload a file, can you check if there are logs in seafile.log and events.log?

**Comment by hp-pepster** [comment]
Manjaro updated to curl 8.10.1-1, so the problem should be solved.
@feiniks this is only related to the native client, the AppImage worked before and is still working.

**Comment by dassystem** [comment]
I can confirm that AppImage 9.0.8 seafile-client is working and also that curl-8.10.1-1 solves the problem with the native build. Closing this issue.
