### ISSUE TITLE
Appimage misses an icon.

### ISSUE THREAD

**Issue by deragon** [haiwen/seafile-client#1568]
Appimage for Seafile client 9.0.8 Rev 1 does not contain an icon that can be used by Gnome (and probably other desktop environment (DE) such as KDE Plasma).  The DE must then use a generic icon as show below.

The  screenshot has been made on Gnome 46 running under Wayland in Ubuntu 24.04 LTS.

The screenshot also shows other application missing an icon, thus the reason why three applications are shown with the same icon.

![image](https://github.com/user-attachments/assets/9a29a616-1b92-423a-964c-6340a5c25362)

**Comment by killing** [comment]
Please refer to https://docs.appimage.org/user-guide/run-appimages.html#ref-desktop-integration for desktop integration to display AppImage's application icons.
