### ISSUE TITLE
"Seafile exited unexpectedly" on Ubuntu 22.04

### ISSUE THREAD

**Issue by JAQuent** [haiwen/seafile-client#1571]
I've tried removing and re-installing it but Seafile doesn't open at all on my system. When I try, I am greeted with

![image](https://github.com/user-attachments/assets/fb483464-14f6-4175-9434-fe11bfbbfdae)

My system is

```
uname -a
Linux systemname 6.8.0-48-generic #48~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  7 11:24:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

I even tried compiling the application myself but following the instructions in the README didn't work either. I am not sure which further information I need to provide. Please let me know and advise me how I can use Seafile on Ubuntu.

**Comment by killing** [comment]
Which version of Seafile client do you use? From where you installed it?

**Comment by JAQuent** [comment]
Hello, sorry for the late reply. I actually fixed it in the end but unfortunately I don't know what "fixed" it exactly. I first successfully compiled the CLI app and then installed Seafile via snap and now it works. I am not sure if the snap version would have worked the whole time.
