### ISSUE TITLE
Set sync timer

### ISSUE THREAD

**Issue by ghost** [haiwen/seafile-client#170]
Hello,

thanks for your marvellous work that I've been following since the 1.x versions. So far, Seafile fully replaced my SVN repository to write papers with Latex.

However, one issue for me is that the Seafile client syncs files immediately after they change which results in unreadable histories of the files (i.e., they are several pages long). Wouldn't it be good to have the possibility to define a "grace time" for synchronization per filetype, in order to avoid traffic for frequently changing files (e.g., like Latex files during editing with a just-in-time preview editor that saves the files for compilation very often)? Something like seafile-ignore.txt in the format

```
*/*.tex 60
```

that indicates that *.tex files should only be synced if they didn't change in the last 60 seconds?

That would be of great help the next time I am looking for an older version of a file while writing a paper!

Thanks a lot! All the Best to you and this project!

**Comment by shoeper** [comment]
A sync timer has been implemented on per library basis.
