### ISSUE TITLE
Move .seafile-data directory to the standard cache directory

### ISSUE THREAD

**Issue by rominf** [haiwen/seafile-client#192]
I suggest you to follow FreeDesktop XDG Base Directory Specification (http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html):

> There is a single base directory relative to which user-specific non-essential (cached) data should be written. This directory is defined by the environment variable $XDG_CACHE_HOME. 

There is a special python lib for this, I would recommend for you (because there are other systems besides GNU/Linux): https://pypi.python.org/pypi/appdirs/

**Comment by freeplant** [comment]
The issue is too old. We don't have such a plan.
