### ISSUE TITLE
[Request] Sort Libraries

### ISSUE THREAD

**Issue by mathieu-mp** [haiwen/seafile-client#206]
Allow user to sort libraries by their name.
Remember sort over sessions, or add a user preference to make this the default behaviour.

**Comment by lins05** [comment]
We have added the feature to filter repos by keyword, which should serve the same purpose of quickly locate the library the user wants to see.

**Comment by Chilledheart** [comment]
fixed in b572ffd200eca4e8997128e93db67f27c719334d by @lins05
