### ISSUE TITLE
SSL Certificate not trusted while valid

### ISSUE THREAD

**Issue by mathieu-mp** [haiwen/seafile-client#208]
Error message is:
https://secure.domain.com/ uses an invalid security certificate. The connection may be insecure. Do you want to continue?

Validation chain is:
UTN-USERFirst-Hardware => Gandi Standard SSL CA (gandi.net) => secure.domain.com
See: https://www.gandi.net/ssl/documentation

Certificate is:
SHA-1 2048 bits

**Comment by mathieu-mp** [comment]
Issue still exists. Valid certificate is not recongnized as valid in seafile-client and seadroid.

Certificate is SHA-1 / SHA-256.
Certificate path is:
1-
CN = AddTrust External CA Root
OU = AddTrust External TTP Network
O = AddTrust AB
C = SE
2-
CN = UTN-USERFirst-Hardware
OU = http://www.usertrust.com
O = The USERTRUST Network
L = Salt Lake City
ST = UT
C = US
3-
CN = Gandi Standard SSL CA
O = GANDI SAS
C = FR
4-
CN = <url>
OU = Gandi Standard SSL
OU = Domain Control Validated

**Comment by shoeper** [comment]
Does it require chain certificates?

**Comment by mathieu-mp** [comment]
Yes

**Comment by lins05** [comment]
You need to gave nginx/apache the correct certs chain so that seafile client can trust your cert.

I have a seafile server with a SSL cert purchased from Gandi, and this is the content of the cert file I gave nginx:

```
-----BEGIN CERTIFICATE-----
Your cert signed by Gandi
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
GANDI Intermidiate Cert
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
UserTrust Cert
-----END CERTIFICATE-----
```

Check http://wiki.gandi.net/en/ssl/intermediate

**Comment by mathieu-mp** [comment]
OK, I was not expecting a server-side conf issue as other browser did recognize the certificate.
I applied the conf suggested and it works under Seafile client (BUT breaks Seadroid).

But this is for obsolete browsers, so:
Could the Root CA for SHA2 certificates be implemented in Seafile so that Seafile behaves like a recent browser?

**Comment by lins05** [comment]
Since this can be solved on the server side, I don't think we would do that.

**Comment by Dvalin21** [comment]
> OK, I was not expecting a server-side conf issue as other browser did recognize the certificate. I applied the conf suggested and it works under Seafile client (BUT breaks Seadroid).
> 
> But this is for obsolete browsers, so: Could the Root CA for SHA2 certificates be implemented in Seafile so that Seafile behaves like a recent browser?

I'm having the same issue, what did you place in your conf file to get this to work? And is seadroid still breaking when you do it?  Thanks
