### ISSUE TITLE
Seafile on HDPI devices

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-client#230]
I've just bought a Surface Pro 3 (Windows 8.1) with a resolution of 2160x1440 and there are some bugs or at least ugly things.

The most important one is, when syncing a new library it's possible to select an existing folder. If you don't know that you can not use this feature on (at least the Surface Pro 3) because it's so small that you have to know that the option must be there.
In addition the UI showing the librarys and so on is small (it is usable but rly small) and the status icon is pixelated.

I can upload screenshots if wanted. Would be nice if you could fix this.

**Comment by mathieu-mp** [comment]
Same issue on Windows 7 in FullHD resolution.

**Comment by Chilledheart** [comment]
I think the qt5 can save this. Some progress on the prerelease build of our qt5 branch is made https://github.com/haiwen/seafile-client/pull/260#issuecomment-69706731 
- win build (20150113) https://seacloud.cc/f/1823808832/

**Comment by freeplant** [comment]
You can try:  https://bitbucket.org/haiwen/seafile/downloads/seafile-4.1.0-en.msi

**Comment by Chilledheart** [comment]
related: https://github.com/haiwen/seafile/issues/895#issuecomment-72356357

**Comment by shoeper** [comment]
Although it seems not to be perfect all the time this is more a QT issue which is getting continously worked on.

On a Surface Pro 3 having a relatively high resolution it works well since 5.1.
