### ISSUE TITLE
Use a file chooser instead of the folder chooser?

### ISSUE THREAD

**Issue by allo-** [haiwen/seafile-client#238]
I find it hard to use the folder chooser for creating new sync folder, as the whole tree layout is not very convenient. many other applications use the file chooser dialog to choose folders, which provides a better navigation and an option to choose and create folders as well.

This is a question of personal preference, but you may consider using the other one.

**Comment by allo-** [comment]
Hi. It would be great, if you could mention why you're closing issues.
Even when it's just a short word like "implemented", "worksforme", "wontfix". 

For example i do not see a commit implementing it currently, but it may be on a branch (as there are strangly two commits bumping the micro version without anything in between?)

**Comment by freeplant** [comment]
In this case, it won't be changed. The current chooser works fine and the feature is not a frequent used feature.

**Comment by allo-** [comment]
okay. Just good to know. It would be nice if you add such a short comment on closing issues, i saw quite a few closed without knowing the reason.
