### ISSUE TITLE
Closing the client via tray icon context menu crashs the app

### ISSUE THREAD

**Issue by liayn** [haiwen/seafile-client#240]
Having the main windows open and using the menu item of the tray icon's context menu to close the application removes the icon from tray, but leaves the stale main window open.
Clicking into the windows finally freezes the application complete.
=> one has to kill the application via task manager

OS: Windows 7

**Comment by lins05** [comment]
Have you tried the latest version of seafile-client? Does this problem still happen?

**Comment by liayn** [comment]
Resolved in version 4.0.6!

Thanks, closed.
