### ISSUE TITLE
[Windows] Syncing whole partition, slash cut off

### ISSUE THREAD

**Issue by Pro** [haiwen/seafile-client#26]
I want to sync my whole data partition ("D:\") on Windows using the most recent client 2.0.5.
- I created a Libryary on the Web Interface.
- Then opened the client, selected the library and chose "Download library".
- Then I clicked on "Advanced: synchronize with existing folder"
- Selected "D:\" as path (also tried with "D:/"
- Entered the encryption password
- Confirmed with OK
  But then I got the error that the directory couldn't be initialized:
  ![unbenannt](https://f.cloud.github.com/assets/251973/1424335/e8302324-401b-11e3-93c5-9f8bd1d282b5.PNG)

I think the problem is that the ending slash of the local path "D:\" is cut off to "D:" which isn't a valid path and thus the client can't find the directory.

Can you please fix this, it should be fixable very fast. Thanks for your great work!

**Comment by AudiMax** [comment]
Any updates on this issue? I'm using the latest client 4.0.7. and also want to sync a whole partition, but get the same error..

**Comment by Pro** [comment]
@killing could you please please fix this issue.
It should be very quick to fix. I already tried to find the corresponding lines in the code to submit a pull request, but unfortunately I had no luck.

**Comment by killing** [comment]
It may involve more changes to the code than you think. I'll have a try.
This may be supported in some version of 4.1 client.

2015-02-07 22:31 GMT+08:00 Stefan Profanter <notifications@github.com>:

**Comment by yjeanrenaud** [comment]
seems not to be solved yet. Even though the slash does not get stripped any more.
I made a workaround by using NTFS junctions: first, I added the sync profile to a folder called D under c:\users\my user\seafile\Seafile\D
then, I quit the seafile client and deleted that folder D.
now I started cmd with administrative privileges and entered: "mklink /J c:\users\my user\seafile\Seafile\D D:\"
opened seafile client and all is good :)

**Comment by jult** [comment]
Still not working. Come on guys! This is easy to fix.
And the size of the volume is irrelevant. If you use TrueCrypt, it can be an opened encrypted volume, which can be any (small) size you would want. I can't sync an opened TrueCrypt volume now because of this. Very annoying. We need to be able to sync drive-letters. In my case that's M:\

**Comment by ydylla** [comment]
Bump after more than a year, with version 6.1.0
Please fix this, users should be able to sync whole drives. Because the symbolic link hack is very ugly. But at least I found this and it is working for me now, even with big librarys.

**Comment by jult** [comment]
I gave up seafile entirely. Left it for syncthing. Much better options, very configurable.

**Comment by shoeper** [comment]
> It may involve more changes to the code than you think. I'll have a try.
> This may be supported in some version of 4.1 client.

@killing

**Comment by freeplant** [comment]
We don't have a plan to support this feature now.

**Comment by Pro** [comment]
Just closing an issue for the sake of reducing the numer of open issue count does not solve it...

That's a major still open bug and it should stay open until there is a good solution for it!

**Comment by shoeper** [comment]
It is a feature request. Those used to be kept at https://forum.seafile.com/c/feature, but it has not strictly been enforced all the time.
