### ISSUE TITLE
OS X Support for Dark Menu Bar

### ISSUE THREAD

**Issue by xortim** [haiwen/seafile-client#261]
A new feature in OS X is to have a dark menu bar and dock. When this is selected, the Seafile client icon is practically invisible.
![screen shot 2014-10-31 at 08 30 36](https://cloud.githubusercontent.com/assets/901298/4860586/cd7e4f10-60f9-11e4-9c9a-ea90627130ac.png)

**Comment by Chilledheart** [comment]
landed at b7bd5a5
