### ISSUE TITLE
Mac OS 10.9.5 Finder do not refresh properly

### ISSUE THREAD

**Issue by amorce** [haiwen/seafile-client#273]
From client, create a folder on a library root with 1 file inside.
Wait for it to be synced.
Keep finder window open on the synced library.
Delete this folder from seahub.
Return to the finder window.
Wait for seafile client sync (display message, 1 folder deleted)
See that the folder is stiil displayed in finder, and can be accessed.

This also occur with created folders

**Comment by Chilledheart** [comment]
duplicated with #67
