### ISSUE TITLE
Problems on the terminal server

### ISSUE THREAD

**Issue by kama3** [haiwen/seafile-client#29]
We use seafile client on a terminal server with multiple users. When the first user launch client, seaf-daemon.exe starts on his behalf. On other users seaf-daemon.exe doesn't start. Synchronization task run as first user who does not have access to the resources of others. Task list of all users available to others.

**Comment by nascheme** [comment]
It this port number sharing still an issue with the current software (version 6.0.0)?  It seems like on a multi-user Windows system, the seaf-daemon port still gets shared between users by default (port 13419).  That seems really bad.  Isn't there a security issue if every user is allowed to connect to the default port and issue commands to the daemon?  I'm not familiar with the daemon's protocol but it seems like a security problem.

I can think of a few improvements.  First, at least the seaf-daemon process could remember the user ID of the user starting it.  If the connecting GUI client doesn't match the user ID, show a warning or disallow it from using the daemon.

Better would be to generate a random unused port and save it to the ccnet folder somewhere.  Then the client to read the file to find which port to connect to.
