### ISSUE TITLE
Seafile Client 4.0.1 bundles broken libcurl on OS X

### ISSUE THREAD

**Issue by smarsching** [haiwen/seafile-client#313]
When using HTTP sync with the Seafile Client 4.0.1 (Beta) on OS X, I get the following error message in `seafile.log`, even though the server-certificate is valid (and the rest of the Seafile client does not complain):
```
[11/20/14 13:09:08] http-tx-mgr.c(325): libcurl failed to GET https://seafile.ma
rsching.com/seafhttp/protocol-version: Problem with the SSL CA cert (path? acces
s rights?).
```

This seems to be caused by a broken version of libcurl that is bundled with the Seafile client: This version looks for the trusted CA certificates in the wrong path. Unfortunately, it cannot be replaced with the version of `libcurl.4.dylib` that is distributed with OS X 10.9. However, I successfully replaced it with the `libcurl.4.dylib` that is build as part of the `curl-7.39.0` formula in Homebrew. Using this version of libcurl fixed the problem for me.

Therefore, I suggest to either fix the CA path in the version of libcurl bundled with the Seafile Client or to bundle the version of libcurl that is provided by Homebrew.

**Comment by Chilledheart** [comment]
this issue is already fixed

**Comment by thewilli** [comment]
@Chilledheart is the issue @kevinsky25 mentioned above fixed as well? I've tested the CLI client on Ubuntu and Debian, and  it refuses to work with the same error message. 

@killing Do you know where this directory is? If there can't be a generic solution, then there should at least be a Debian/Ubuntu specific package, as it is probably used on these platforms even more than on CentOS..

**Comment by Chilledheart** [comment]
Hi @thewilli, the curl bug on Mac OS X is fixed now. If you have some similar issue with ubuntu, debian or any other linux distribution, it is better to open a new issue to trace it.

Much appreciated.

**Comment by killing** [comment]
Yeah I think it's better to build CLI client for Debian/Ubuntu and Centos
separately. We'll do it when we have the time.

2015-03-14 23:21 GMT+08:00 Willi Eggeling <notifications@github.com>:
