### ISSUE TITLE
"Sync Now" not working as expected

### ISSUE THREAD

**Issue by kimhanse** [haiwen/seafile-client#353]
I have disabled auto sync for a library and added a file to it locally. When I select "Sync Now" in the context menu on the library I expected the file to be uploaded but nothing happens.

I use client version 4.0.1 and have checked the log files, and they don't change either when I choose "Sync Now".

**Comment by FireROR** [comment]
any updates?

**Comment by freeplant** [comment]
Please try v4.0.6

**Comment by FireROR** [comment]
Yes. It looks fixing the issue.

Thanks
