### ISSUE TITLE
Sync speed not shown correctly on "hover" of tray icon

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-client#358]
see image:
![0762](https://cloud.githubusercontent.com/assets/5340585/5463498/e506725e-857d-11e4-9068-db1a1a74f7a8.png)

shows for instance 0 KB/s instead of 2100 KB/s. In the bottom of the clinet it is shown correctly. And the German translation is also not the best. Better would be `Lädt $bib hoch`.
Client version: 4.0.4

 Not an important issue but still a bug.

**Comment by shoeper** [comment]
any update on this?

**Comment by freeplant** [comment]
@Chilledheart

**Comment by Chilledheart** [comment]
Sure, I will look into it soon. Probably apply a fix before the next release.
