### ISSUE TITLE
Why the folder size shows 0 byte?

### ISSUE THREAD

**Issue by FireROR** [haiwen/seafile-client#374]
![screenshot 2014-12-22 15 27 13](https://cloud.githubusercontent.com/assets/8516814/5530848/ef104e68-89f2-11e4-92af-21e9a8e93fa7.png)

Not sure why but other folder looks fine... And it does content couple hundred MB data in it.

**Comment by lins05** [comment]
Fixed in haiwen/seafile@d78f5b535b5d266f5ad8d8f0b06cf87754e3a208
