### ISSUE TITLE
Seafile Terminal Client  4.0.4 fails to start on generic linux

### ISSUE THREAD

**Issue by rcoss** [haiwen/seafile-client#381]
On Ubuntu Lucid ( 10.04 LTS) seaf-cli fails to start:

system@cual:~$ seaf-cli start
starting ccnet daemon ...
Started: ccnet daemon ...
starting seafile daemon ...
seaf-daemon: /lib/libc.so.6: version `GLIBC_2.12' not found (required by /usr/local/seafile-cli-4.0.4/lib/libldap-2.4.so.2)
Failed to start seafile daemon

Ubuntu 10.04 LTS 64bit
Seafile version 4.0.4 64bit

**Comment by linamu** [comment]
Hi, it's possible to build seafile-client without GUI ??
