### ISSUE TITLE
Syncing to external HDD doesn't work

### ISSUE THREAD

**Issue by oal** [haiwen/seafile-client#39]
I tried setting up a library, and set its sync destination to my external hard drive. It syncs as expected, but after rebooting my computer, it's desynced. I think this may be because the external drive isn't spinning when the Seafile client is started, and Seafile doesn't see it immediately. If I sync libraries to my internal hard drive, everything works as expected. Maybe the Seacloud client should try looking for the sync destination a few times before giving up, so that the sleeping HDD has time to spin up.

I'm running the latest version of Seafile (server and client), in Ubuntu.

**Comment by moritzschaefer** [comment]
@killing Did you improve this? I am planning to setup a system with external hard drive..

**Comment by shoeper** [comment]
Afaik yes. Go to settings -> advanced and enable the first option (Something like 'do not usync if local device is unavailable').

**Comment by ggkitsas** [comment]
What is the reason of not having this option enabled by default?

**Comment by lins05** [comment]
Seafile client may not be able to access the local folder of a library in
two cases:

- The user has deleted the folder from your local drive, or
- The library is synced to a usb disk or network shared drive, and the usb
disk or network drive is unavailable (e.g. seafile client is started but
network drive has not been mounted) at that moment.

For the former case the user would like the library to be "desynced"
automatically. For the latter they don't want that.

Sinc seafile client can't tell between the two cases and the former case is
more common, we make it the default behavior to "desync" the library when
seafile client can't access the local folder of a library, and offer a
settings option to change the behavior.

**Comment by simmbiote** [comment]
@shoeper Where do I find the Settings menu?

> Afaik yes. Go to settings -> advanced and enable the first option (Something like 'do not usync if local device is unavailable').
