### ISSUE TITLE
Huge Log Files

### ISSUE THREAD

**Issue by alvonellos** [haiwen/seafile-client#393]
I have log files in C:\Users\<user>\ccnet\logs that are so big that I can't open them with notepad++ to find out what the issue is. 

Here's the directory listing: 
   -- applet.txt 735M
   -- ccnet.txt   1.206G
   -- seafile.txt 991KB

Shouldn't there be an option to intuitively rotate log files?

**Comment by dhmetros** [comment]
I was wondering about this when looking over the logs after a client had been in use for roughly little over a month.  It seems this is still open.  Does the client still not support log rotation?  Seems like an oversight that should be pretty easy to resolve.

Can't expect end users to hunt down and clean up the client's logs all the time.  Especially when they probably won't figure it out until they run out of storage space.
