### ISSUE TITLE
seaf-cli desync command doesn't support pathes with spaces

### ISSUE THREAD

**Issue by denis-b** [haiwen/seafile-client#4]
seaf-cli desync -d "/path/seafile/name_with space" doesn't works : 

command result : 
seaf-cli.py desync: error: unrecognized arguments: space

**Comment by landure** [comment]
i confirm this issue with Seafile CLI client 4.3.2.
Here is a patched seaf-cli script that fix the issue:

https://raw.githubusercontent.com/biapy/howto.biapy.com/master/seafile/seaf-cli
