### ISSUE TITLE
Seafile does not log out users on password change (Seafile user management and LDAP).

### ISSUE THREAD

**Issue by antares2001** [haiwen/seafile-client#416]
Hello everybody,

this seems like a major security hole: I do user management in Seafile through LDAP. When I change a user's password now in LDAP, the Seafile client is still able to synchronize the user's library with the old password. Also, when I set the "pwdAccountLock" or "pwdAccountLockTime" attribute, Seafile still does not reject users that logged in before. Obviously the system things "once authorized is good for always" which is a wrong approach (think of somebody copying the Seafile directory with settings from ones USB stick).

The only moment, when Seafile asks for a fresh login is when I change the username in LDAP, so the user does not exist anymore.

This happens also when I change the password for a local user in the Seafile web frontend (who is not authorized via LDAP).

Please fix this issue, since it imposes a major threat to infrastructure and allows non-authorized access to Seafile. Seafile Web-UI and Seafile client should make sure to check whether the user credentials are still valid. On pwd change, Seafile client should stop syncing immediately.

_EDIT_
Even worse: if I delete a user in Seafile, the client still syncs files to somewhere, when I add new files in the local directory. It does not notice that the user is deleted and non-existent.

**Comment by killing** [comment]
AFAIK, there is no portable way to monitor changes in a whole sub-tree in LDAP or AD.
So the easiest way to fix this issue is to provide a button in the Seafile admin interface to disable a LDAP user. This should clear all the access tokens for file syncing too. The same should apply to deleting a user from database.
We'll fix this as soon as possible.

**Comment by killing** [comment]
Right now you can manually remove the access tokens from the database.
Use seafile-db;
delete from RepoUserToken where email=xxxx;

**Comment by antares2001** [comment]
The problem (PW change) exists for local users as well. Not only LDAP. 

It seems that Seafile checks the username to exist but not whether the password is still correct. Same for mobile client.

**Comment by killing** [comment]
When log in, Seafile checks the password. I think the problem is that when the password is changed, the server doesn't log out the client automatically.

**Comment by antares2001** [comment]
This seems to be the case. But obviously Seafile checks the username for existance. Can't it check the password as well upon access? I think it's a bad idea that the Web-UI, 
desktop client and mobile client keep a user authenticated, while their credentials have changed. As I said, the flaws apply for LDAP *and* local users.

Maybe group membership checking would also be a good idea to solve the LDAP issue. The Atlassian products, e.g., stop working immediately for a user when I remove him from the corresponding groups. Since the idea of LDAP/AD is centralized user management, I don't want to remove access tokens in each single application but want to be able to lock an account immediately.

**Comment by killing** [comment]
We're really interested in making LDAP user management better. Can you provide more details about how Atlassian products find a user is disabled in LDAP? Perhaps some pointers to documentation would be helpful. I read some of their documentation but can't find related topics.

**Comment by antares2001** [comment]
Actually I'm a bit limited on time, but what I found out is that you're actually right about the problem of instant propagation of changes from LDAP. What the Atlassian products do, however, is to provide the possibility to set a synchronization timer that refreshes the LDAP information every n seconds. So it would be very helpful if it was at least possible to set a timer which makes Seafile check the credentials for validity after a period defined by the administrator.

The Atlassian products restrict access right to group memberships. So you have, e.g., atlassian-users and atlassian-admin groups which are checked and if I withdraw a user from atlassian-users he has no access to the content any more.

Yet, I see the issue that Seafile for now only checks the username being correct but not the password (local account).

**Comment by shoeper** [comment]
Yes, because the client only sends the password on login. This is a good mechanism because the password mustn't be saved anywhere on the client side. Instead the client gets a token on login which it uses to login. So on password change all tokens for the user should get removed from database. And this is the point where seafile must know when a password of an ldap account is changed. This would require an event on change or a last changed property.

**Comment by killing** [comment]
@shoeper I did some research and found that AD has an attribute 'pwdLastSet', which is the last update time a user's password. We can use this feature to detect password change. Other LDAP server may have different mechanism. But AD is the most used LDAP server, so we'll support it first.

**Comment by antares2001** [comment]
There's a "modifyTimestamp" attribute for inetOrgPerson in ApacheDS. Maybe you can also incorporate that the same time, as it shouldn't add significant overhead.

Value format is like this: 20150113103312.014Z

**Comment by languitar** [comment]
This still seems to be a problem even for local accounts. Even after deleting all tokens, restarting the server and clients, existing clients can still continue to sync. What do I have to delete to get a full reset?

**Comment by freeplant** [comment]
Currently you can unlink all devices in the "Devices" tab (Some old clients may don't show in this Devices tab. So you can't revoke the tokens)

Anyway, this problem will be solved in version 4.2.
