### ISSUE TITLE
"Show main window" shouldn't change to "Hide main window"

### ISSUE THREAD

**Issue by amorce** [haiwen/seafile-client#417]
This is a UI enhancement proposal. (For OS X, may be other OS concerned)
The tray icon has a "Show main window" entry when the window is hidden, which allow to display the window on top. So the entry menu change to "Hide main window".
But on OS X at least, when we switch to another app without closing the window, the entry menu remain "Hide main window". At this moment, to re-show the main window, we have to click to "hide main window", then click on tray, and click on "Show main window".
I suggest to have a single menu entry "Show main window" which just display the window on top and don't change to "Hide main window". If we want to hide the window we can just close it as it is possible to do actually.

**Comment by lins05** [comment]
Sounds reasonable. @Chilledheart can you do this?

**Comment by Chilledheart** [comment]
Sure, I will start working on 4.0 branch.
