### ISSUE TITLE
Make cloud file browser available for synced libs

### ISSUE THREAD

**Issue by dakira** [haiwen/seafile-client#418]
The cloud file browser allows me to quickly generate a link to share files. There should be a way to open it for libraries that are synced locally.

Right now the cloud file browser only opens when I double-click libraries that are *not* synced locally.

**Comment by shoeper** [comment]
+1 - this was also requested in another issue (not sure in wich one)

**Comment by bthoem** [comment]
+1 - would really appreciate this functionality.

**Comment by GITchristoph** [comment]
Newly available Windows beta client 4.1 already offers the option to generate links via context menu directly in the Explorer Window.
It's on the roadmap for Mac client 4.1 as well.

I would assume once that option is fully integrated it would make this request redundant?

**Comment by dakira** [comment]
> I would assume once that option is fully integrated it would make this request redundant?

With a Linux option, yes. Otherwise no. 90% of the clients here are Linux.

**Comment by Chilledheart** [comment]
Available in 4.2.0 release

Fixed in #523.

**Comment by Chilledheart** [comment]
@dakira you can create a new issue for nautilus-integration if you really want it! Thanks in advance.

**Comment by abandholm** [comment]
While we wait, I have made a quick-and-dirty solution (bash + sqlite3 + zenity) that can do this:

https://bitbucket.org/abandholm/seafile-share-link/

The solution has one script that can create share links from the command line and a simple wrapper for Nautilus that works with "Nautilus scripts".

I am sure this can be done better, but I wanted something like this and created a simple hack. It is brand new which means nobody else has tested it yet ;-) (It works on my Ubuntu 12.04)

**Comment by dakira** [comment]
@abandholm hey, looks nice, thanks. I'll definately check it out!
