### ISSUE TITLE
Seafile client keeps modifying files

### ISSUE THREAD

**Issue by Jip-Hop** [haiwen/seafile-client#463]
I'm having issues where Seafile makes modifications to my files, or at least it thinks files have been modified. Look at the example in the attached image. The Seafile Linux client just downloaded a png file from the server. Immediately after, it notifies me that the same file (which was just downloaded) has been modified....

![screenshot](https://cloud.githubusercontent.com/assets/2871973/6212815/6874af3e-b5e9-11e4-8cea-edb7de8b02c6.png)

This is rather strange and annoying. Every time my client syncs a library, the library reset the "Recently Updated" value to "just now". Even when nothing is actually updated, just some content downloaded by a client.

But above all, I'm worried about my file integrity when I keep getting notifications that my files have been notified when I'm 100% sure I haven't been making modifications.

I have no idea where to look for the source of this problem. Does this sound familiar to somebody? Anybody who can walk me trough a debugging process?

I am able to re-produce this by adding a file from the OS X client. Wait a few minutes. Start the Linux client. Wait for it to sync. Then I see the popups: A file is added. A file is modified.

The modification that has been synced by the Linux client is then synced back to my OS X client where I get another popup that a file has been modified. So If I add 1 file on OS X, it is uploaded. Downloaded on Linux. Modified on Linux. Uploaded from Linux and the modification is then downloaded by the OS X client.

Setup:
Seafile server 4.0.5 on Lubuntu
Seafile GUI Linux client 4.0.6 on Lubuntu (Same machine as server, syncs to external NTFS USB HDD)
Seafile GUI OS X client 4.0.6 on Yosemite

**Comment by freeplant** [comment]
Maybe this is modification of file permission?

**Comment by lins05** [comment]
> syncs to external NTFS USB HDD

I agree with @freeplant. I used to have a lot of annoying troubles with file permissions when using an external NTFS HDD with my ubuntu laptop. 

When your seafile mac client changes a file, your linux client downloads the changes, but the file permisson is changed due to deficiency of linux NTFS support, so the change is synced back to mac os, and so forth.

If you search ["dropbox linux ntfs"](https://www.google.com/search?q=dropbox+linux+ntfs&ie=utf-8) you would also see many people reporting similar problems.

**Comment by Jip-Hop** [comment]
I think you could be right! I briefly tested with a library that syncs to an internal ext4 volume. The same behavior doesn't show with that library.




I really need the NTFS external drive for compatibility and portability. 




Any advice on how to manage the permissions properly in this scenario?




Thanks for the reply!

**Comment by Jip-Hop** [comment]
Seems to have been fixed with these fstab options for NTFS-3g: defaults,uid=1000,gid=1000,locale=en_US.UTF-8,umask=0000,fmask=0133,rw,x-gvfs-show.

By default, NTFS-3g mounts with permissions 777. I checked what permissions the files have that Seafile syncs to my local ext4 folder. That was read-write for owner and the rest has only read permission. Nobody has executable permission. So That's where the fmask of 0133 comes from. Drop permissions to 644. Now Seafile doesn't upload a 'modified' file after syncing.

Hopefully these settings don't have any negative secondary effects. But so far syncing seems fixed.

**Comment by timonoj** [comment]
Thanks, Jip-Hop, having the same issue and I was also imagining poor NTFS permission handling...But wasn't sure how to fix it. Will try your solution.

**Comment by Jip-Hop** [comment]
timonoj I'm sorry but my proposed solution didn't work in the end. The fstab settings will ignore file permissions and set all file permissions and ownerships according to the specified options: uid=1000, gid=1000, umask=0000, fmask=0133.

In the following scenario this causes problems. I chmod +x a file on my MacBook. This modification is synced to the Seafile server. The Seafile server syncs this change to the Externa NTFS drive. According the the fmask the file can not have executable rights, so the file is saved without +x. This modification is synced back to the Seafile server and eventually to my MacBook where I end up with a file without executable rights.

The other method I've tried is NTFS user mapping. That way file permissions are preserved. This works almost like I wanted. It would sync without problems and when I connect the external NTFS drive to my MacBook I could open and modify files. However, if I were to connect the external drive to someone else's Windows machine I would only have read permission because the specific Linux user I've mapped permissions to is not on that computer. So for portability and flexibility this is again a no go for me.

I have given up on syncing to my external NTFS drive from Linux. I think it would have worked if I'd have had a Windows server to sync from. This is not a problem with Seafile itself though.

**Comment by timonoj** [comment]
Hmmm...That's interesting. Sorry I'm not too exposed to the permissions correlation between NTFS and Linux...Is there a way with the NTFS mapping to get the permission to 'everyone' as NTFS allows? How does software like dropbox get around this?
