### ISSUE TITLE
4.1.1 shows two window bars and no tray icon for GNOME-shell

### ISSUE THREAD

**Issue by silberzwiebel** [haiwen/seafile-client#485]
Hi,

I am using the seafile client version 4.1.1 with Fedora 21 and GNOME 3.14.3. After the latest update to version 4.1.1 the client window now shows two window titles: 
![Screenshot](http://kartoffelsalat.ddns.net:8082/files/9ccdb103-9714-45e0-9cb8-be6c1436e175/seafile-client-bug.png)
Furthermore, there is no icon in the message tray any longer.

Thanks for fixing,
silberzwiebel

**Comment by Chilledheart** [comment]
Hi silberzwiebel,

   It is nice to see that your are under the exactly the same environment as mine. It seems we have some issues with qt5 support under linux. In fact there is an option for linux users to choose use qt4 or qt5, and it seems seafile-client with qt4 works just out of box, with correct tray icon and exact one windows title there.
   I think you build seafile-client with qt5, right? And we are still working on fixing qt5 support for linux. Let me know if my guess is incorrect.

  Cheers,
Chilledheart

**Comment by silberzwiebel** [comment]
I'm using seafile from this repo, not sure what qt version is used over
there...: https://copr.fedoraproject.org/coprs/pkerling/seafile/

Am 12.03.2015 um 03:25 schrieb Chilledheart:

**Comment by Chilledheart** [comment]
I see. It is a known bug with Qt5's Tray Icon support for GNOME3 (known as https://bugreports.qt.io/browse/QTBUG-35658).

**Comment by Chilledheart** [comment]
Qt5's Tray Icon support on Linux would be fixed in Qt 5.4.2. I hope Fedora will adopt it from the upstream soon.
