### ISSUE TITLE
compile the client on windows error

### ISSUE THREAD

**Issue by gjunp** [haiwen/seafile-client#500]
when I compile the client source code  on windows ,the error happens:
CMake Error at D:/cmake-3.2.1-win32-x86/cmake-3.2.1-win32-x86/share/cmake-3.2/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "5.4.1" from
  C:/Qt2/5.4/mingw491_32/bin/qmake.exe, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:60 (FIND_PACKAGE)

Must  use Qt 4?

**Comment by Chilledheart** [comment]
You might want to pass `-DUSE_QT5=on` to cmake here.
