### ISSUE TITLE
Impossible to uninstall silently in windows

### ISSUE THREAD

**Issue by msilvoso** [haiwen/seafile-client#504]
Hello,

When trying to uninstall silently the windows client (msiexec /qn /x {product code} there is still a dialog appearing about removal of the account info.
Would it be possible to define a default behaviour when the uninstall is silent? For instance a default "yes remove everything"?

Manu

**Comment by octomike** [comment]
Has this been closed because there is a fix that I missed?
I also get a dialog when uninstalling with chocolatey.
