### ISSUE TITLE
Reported latest version is wrong

### ISSUE THREAD

**Issue by liayn** [haiwen/seafile-client#505]
The applet.log file contains a line

```
[03/31/15 13:53:29]The latest version is 4.0.5
```

But the current version is 4.1.3

Platform: Windows

**Comment by liayn** [comment]
Still an issue.
Running 4.2.1 now.
The reported latest stable in the applet.log is 4.1.4!

(Currently available on the website 4.1.6 and 4.2.1)

**Comment by shoeper** [comment]
Can confirm this.

```
[05/15/15 20:47:34]The latest version is 4.1.4
```

**Comment by liayn** [comment]
Running 5.0.1 now:
```
[01/06/16 00:07:16]The latest version is 4.3.4
```

**Comment by shoeper** [comment]
same here.

**Comment by liayn** [comment]
Running 5.0.7 now and the log reports:
```
[04/16/16 01:34:57]The latest version is 5.0.4
```

**Comment by shoeper** [comment]
On Fedora I don't have the issue. Maybe the version wasn't raised before building the Windows package.

**Comment by liayn** [comment]
Not sure what you mean. To my understanding this version number is fetched from some server to make thr update check. How should that be related to the current build of my installed version?

**Comment by shoeper** [comment]
Sorry, that's correct. I'd look at the wrong line.

**Comment by moschlar** [comment]
https://github.com/haiwen/seafile-client/blob/master/src/auto-update-service.cpp#L19-L28
