### ISSUE TITLE
Unable to sync a library with a folder if this folder was synced before

### ISSUE THREAD

**Issue by Jenselme** [haiwen/seafile-client#518]
I recently reinstalled my Seafile server. In order to use the sync client, I had to delete my account and add a new one with the new server. However, when I tried to sync some folder, I have the following error message:

```
Failed to add download task:
 Worktree conflicts existing repo
```

The `.seafile-data` folder is at the same location for both the old and new account. What is strange is that I don't have this problem for all my folders.

I tried the solution proposed in #117 but it didn't work. I also tried to rename the folder, do the sync and then rename the folder but it only caused the client to lose track of the library. I tried to sync the library with the existing folder, but I had the same error as before.

- Client version: 4.1.5
- System version: Fedora 21
- Server: 4.1.2

Do you have any idea about how to solve this issue?

**Comment by mnott** [comment]
Same issue over here.

**Comment by PocketSam** [comment]
Problem still exist here in 2019. :(
