### ISSUE TITLE
make cloud file browser resizable

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-client#530]
At least on windows resizing is currently not possible. 
Furthermore at least on my device there is always a scrollbar at the bottem. Maybe you've to adjust the default width.
![0812](https://cloud.githubusercontent.com/assets/5340585/7321095/88ac0b80-eaa0-11e4-81cc-ddeb0e864a78.png)

**Comment by freeplant** [comment]
What Windows version do you use?

**Comment by shoeper** [comment]
4.1.6

**Comment by Chilledheart** [comment]
it should be fixed in #531
