### ISSUE TITLE
Cloud File Browser faster than normal sync

### ISSUE THREAD

**Issue by matpat996** [haiwen/seafile-client#532]
When I'm using the cloud file browser i have arround 3,5MB/s upload speed and when I use normal sync, I have arround 1,5-2MB/s upload.

Server Version 4.1.2 / Client Version 4.1.6 / Raspberry Pi B+ with connected 500GB HDD

Edit: When I'm using the web-interface i have arround 3,7-4MB/s upload speed.

**Comment by shoeper** [comment]
I'm not sure about the cloud file browser, but client end web interface use different methods. Uploading through webinterface moves cpu load to the server side. Uploading with the client calculates everything on client side and uploads data in a way it just has to be saved by the server.
Could it be that you have a slow client (e.g. slow hdd)?

**Comment by matpat996** [comment]
Yes, that could be. I've a 2,5" 500GB HDD bulit in my desktop-pc on which the entire seafile folder is synced on to. I'll try to move the seafile folder onto my SSD.

**Comment by shoeper** [comment]
In the Seafile folder is a hidden folder named seafile-data which is used for data about your libraries and as temporary storage (it does not need much storage but it contains very much files). So moving your seafile folder on the ssd could help a lot (it is still possible to sync libraries where you want, so the space consuming data can remian on your HDD).
Let me know your results, please.

**Comment by matpat996** [comment]
Sorry for the late answer. I tested it on my notebook which has built in a SSD. It run there a bit faster than on my desktop, where seafile is located on a HDD.
