### ISSUE TITLE
right click on tray icon win7

### ISSUE THREAD

**Issue by ftribrunn** [haiwen/seafile-client#537]
right clicking on tray icon opens the program. clicking again opens the menu with "help, quit" and so on.

thats distracting. in past versions the menu comes with one right click. 
double /or one left click and the program opended.

thx for help.
greets
fabian

**Comment by Chilledheart** [comment]
hmm, that is odd. I'll try to fix it soon (before next release, probably).

**Comment by shoeper** [comment]
Can confirm this behaviour on Windows 8.1.

**Comment by ftribrunn** [comment]
many thanks!!! @Chilledheart
