### ISSUE TITLE
Disable stand by/suspend mode during sync processus

### ISSUE THREAD

**Issue by camlafit** [haiwen/seafile-client#539]
Hi

Was wrotten first on https://github.com/haiwen/seafile/issues/1166, in wrong repository.

The purpose is to stop suspend/hibernate if a sync/update/change process is in progress. 
Seen on windows plateform

**Comment by shoeper** [comment]
+1
Also had the issue that first sync failed and library had to be setup multiple times because it got interrupted by standby mode.
