### ISSUE TITLE
seafile-applet switches screens

### ISSUE THREAD

**Issue by vulder** [haiwen/seafile-client#545]
in the case that i put my seafile-applet to my second monitor and switch to a new tag (https://awesome.naquadah.org/doc/api/modules/awful.tag.html), virtual desktop, and back. The applet changes from screen 2 to screen 1(monitor 1).

**Comment by vulder** [comment]
in src/ui/main-window.cpp
my guess is:
when i switch to another tag; there is no closeEvent. So writeSettings() within hide() is never called.
But switching back to to a tag results in some qt event telling the application to draw again. This function then reads the old position and draws the applet at the wrong location.

**Comment by Chilledheart** [comment]
Hi @vulder:
I am not sure whether it is a issue. Currently I don't have a machine with multi screens running windows, but on OS X, at least, the saved settings is good and restores the applet window to the exact screen where it closes.

Anyway, if you want to do something to prevent `writeSettings` or do your own hacks, you might want to check the code inside `MainWindow::event`.

**Comment by vulder** [comment]
it think it should be enough to handle the qtHide event with calling MainWindow::hide()
if i find time i'll write a patch, and create a pull-request. But i can only test the code on my machine, so the rest would be up to you :D
