### ISSUE TITLE
main windows not visible

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-client#548]
While syncing a library I can not get the main window. Neither clicking on it in the Windows taskbar nor using the try icon and clicking on "show main window" has any effect.

I'm currently using version 4.1.6 on Windows 8.1.

**Comment by shoeper** [comment]
Ok sync has finished, but I'm still not able to bring the window to front.

Seems like it is out of field of view. But how can I get it back to fov?

**Comment by Chilledheart** [comment]
Hmm, I think it should be fixed (partially, at least) at #535 . For a temporary solution, you can try the following steps:
- Right Click the seafile tray icon
- Click "show main windows" in the popped-up context menu
- Press "Alt + Space" using your keyboard
- Press "m" using your keyboard
- Press "Up" and "Left" repeatedly to adjust the main window's position towards the left top point of your screen.

**Comment by shoeper** [comment]
Thank you very much! Don't know how exactly, but I got the windows back in fov.
