### ISSUE TITLE
Seafile Client allows weak ciphers in SSL/TLS Client Hello

### ISSUE THREAD

**Issue by ssd63** [haiwen/seafile-client#555]
Hi!
Using wireshark I found out that the Ubuntu Seafile Client (ver. 4.1.6) seems to accept some weak cipher suites like

> Cipher Suite: TLS_RSA_EXPORT_WITH_DES40_CBC_SHA (0x0008)
> Cipher Suite: TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5 (0x0006)
> Cipher Suite: TLS_RSA_EXPORT_WITH_RC4_40_MD5 (0x0003)

so the Client could be susceptible to protocol downgrade attacks.

Please remove those cipher suites as they could possibly pose a threat to the users of the Seafile Client on Ubuntu.

ssd63

**Comment by Chilledheart** [comment]
Can you tell which OS are you using, windows or linux?

**Comment by ssd63** [comment]
I'm running Ubuntu 14.10.

Today, I also tested Seafile Client 4.2.0 running on Windows 7. I didn't find any proven weak Cipher being used. Just some uncommon ciphers als SEED or IDEA and Hashing with MD5.

> Cipher Suite: TLS_RSA_WITH_RC4_128_MD5 (0x0004)

Ceterum censeo: Following [RFC 7465](https://tools.ietf.org/html/rfc7465 ) you should also disable all Cipher Suites that use the RC4 Cipher.
