### ISSUE TITLE
New library wizard opens up in the background

### ISSUE THREAD

**Issue by may-bee** [haiwen/seafile-client#559]
When dragging a new folder to be synchronized into the seafile client on Windows 7 (64bit), the "new library" wizard pops up as usual in the middle of the main screen.
But, if the the explorer window you have got the folder from is also in the middle of your main screen, the "new library" wizard will be hidden by the explorer window.

I do not know, whether this is a restriction or whether you have simply set again the layout of the wizard. Currently, this might be confusing for some users.

**Comment by Chilledheart** [comment]
Confirmed on Windows 7 and Mac OS X
