### ISSUE TITLE
how to build deb using the latest source

### ISSUE THREAD

**Issue by hnuzhoulin** [haiwen/seafile-client#565]
Hello，I noticed that the source version is 4.2.0 now.

But the ubuntu client version is just 4.1.6

so I want to build deb package from source...

But I can not find any documents.

Thanks for such a wonderful software.

**Comment by allo-** [comment]
Have a look here: https://github.com/haiwen/seafile/tree/master/scripts/build

AFAIK there is no proper support to build it just with dpkg-buildpackage in some way you can put it into an repo easily.

**Comment by Shanto** [comment]
Here's an attempt to package [Seafile (server suite) for ReadyNAS](https://github.com/Shanto/seafile-readynas) (Debian Wheezy) systems. ReadyNAS requires all files to be under /apps/<appname>. But you can probably make it work for you by:

- [ ] Setting APPDIR=/opt/seafile (see https://github.com/Shanto/seafile-readynas/blob/master/src/Makefile#L11) before building.
- [ ] Removing ReadyNAS specific static files in https://github.com/Shanto/seafile-readynas/tree/master/files
- [ ] Move https://github.com/Shanto/seafile-readynas/blob/master/files/apps/seafile/fvapp-seafile.service to standard Debian location; Also adopt it for standard Debian systems– including but not limited to fixing hardcoded paths in it for your chosen path (e.g. /opt/seafile)
- [ ] Adding symlinks to /opt/seafile/bin/* from /usr/bin/* and add ld.conf rules to include libs from /opt/seafile/lib/.

However, note that although I got it barely working for ReadyNAS, it is not thoroughly tested, and probably a lot more patches are needed than existing to address/undo Seafile's assumption on a complex and fixed directory layout.

To build this for your architecture, change directory to your git clone, and do:

```bash
mk-build-deps -i
dpkg -i <generated-package> && apt-get -f install
dpkg-buildpackage -b
```
Hope this helps.

**Comment by allo-** [comment]
with the different scripts to install to a custom prefix a real debian package with everything in one might be possible with the usual build process.

The debian project itself says the packages and build-process are too much linked together and they would like to see an option to package libsearpc, ccnet, seafile and seafile-client in seperate independent packages.

**Comment by shoeper** [comment]
https://packages.debian.org/search?keywords=seafile

**Comment by allo-** [comment]
By the way: The Ubuntu PPA does not contain a version for Ubuntu "cosmic", yet.
Is this PPA updated by the seafile project itself?
