### ISSUE TITLE
upgraded to new client (4.2.0) bad response 404 for protocol version

### ISSUE THREAD

**Issue by alvonellos** [haiwen/seafile-client#570]
[05/12/15 16:30:08] http-tx-mgr.c(774): Bad response code for GET http:/xxx:8000/seafhttp/protocol-version: 404.

in the new client I receive the above error, nothing is syncing now. The server is running on windows. perhaps I need to upgrade the server to the new version?

**Comment by killing** [comment]
Have you opened port 8082 on the server? That error message won't prevent
you from syncing. The new client uses http syncing only. It first tries to
sync with Nginx/Apache, if not available, it'll fall back to sync on port
8082.

2015-05-13 10:24 GMT+08:00 Alexander Alvonellos <notifications@github.com>:

**Comment by alvonellos** [comment]
The server is running on windows 3.1.6, I checked and it appears that something is is listening on 8082. Netstat -ab gives this: 
```
  TCP    0.0.0.0:21             titan:0                LISTENING
 [FileZilla Server.exe]
  TCP    0.0.0.0:80             titan:0                LISTENING
 Can not obtain ownership information
  TCP    0.0.0.0:135            titan:0                LISTENING
  RpcSs
 [svchost.exe]
  TCP    0.0.0.0:445            titan:0                LISTENING
 Can not obtain ownership information
  TCP    0.0.0.0:1025           titan:0                LISTENING
 [wininit.exe]
  TCP    0.0.0.0:1026           titan:0                LISTENING
  eventlog
 [svchost.exe]
  TCP    0.0.0.0:1027           titan:0                LISTENING
 [lsass.exe]
  TCP    0.0.0.0:1028           titan:0                LISTENING
  Schedule
 [svchost.exe]
  TCP    0.0.0.0:1092           titan:0                LISTENING
 [services.exe]
  TCP    0.0.0.0:1155           titan:0                LISTENING
  PolicyAgent
 [svchost.exe]
  TCP    0.0.0.0:3389           titan:0                LISTENING
  TermService
 [svchost.exe]
  TCP    0.0.0.0:8000           titan:0                LISTENING
 [python.exe]
  TCP    0.0.0.0:8082           titan:0                LISTENING
 [fileserver.exe]
  TCP    0.0.0.0:10001          titan:0                LISTENING
 [ccnet-server.exe]
  TCP    0.0.0.0:12001          titan:0                LISTENING
 [seaf-server.exe]
  TCP    0.0.0.0:47001          titan:0                LISTENING
 Can not obtain ownership information
  TCP    x.x.x.x:139       titan:0                LISTENING
```
I portscanned using t1shopper and received the following: 
```
Scanning ports on x.x.x.x

x.x.x.x is responding on port 21 (ftp).

x.x.x.x is responding on port 80 (http).

x.x.x.x is responding on port 135 (epmap).

x.x.x.x is responding on port 139 (netbios-ssn).

x.x.x.x is responding on port 445 (microsoft-ds).

x.x.x.x is responding on port 1025 (blackjack).

x.x.x.x is responding on port 1026 (cap).

x.x.x.x is responding on port 1027 ().

x.x.x.x is responding on port 1028 ().

x.x.x.x is responding on port 1092 (obrpd).

x.x.x.x is responding on port 1155 (nfa).

x.x.x.x is responding on port 3389 (ms-wbt-server).

x.x.x.x is responding on port 8000 (irdmi).

x.x.x.x is responding on port 8082 (us-cli).

x.x.x.x is responding on port 10001 (scp-config).

x.x.x.x is responding on port 12001 (entextnetwk).

x.x.x.x is responding on port 47001 ().
```

Any other ideas? Should I go ahead and attempt upgrading the server?

**Comment by killing** [comment]
I mean do you open the port 8082 in the server's firewall.

2015-05-14 21:04 GMT+08:00 Alexander Alvonellos <notifications@github.com>:

**Comment by killing** [comment]
Server 3.1.6 doesn't support http sync. And client 4.2 only use http sync.
That's why you can't sync. Please upgrade the server to 4.0+.

2015-05-14 21:26 GMT+08:00 JiaQiang Xu <xjqkilling@gmail.com>:

**Comment by dhbolthausen** [comment]
I am having a similar issue on a lxc install of seafile. I have two containers, (both seafile) one syncs fine, folder/files, the other can upload files only, if I select a folder it puts folder name on my seahub interface, but none of the recursive directories copy.  I am using 8083 for the port on this install - is this somehow effecting the uploads? But if so why do files upload? Any help would be appreciated.

**Comment by killing** [comment]
I suppose you don't configure https? Then you must use port 8082 instead of
8083. Or you can set up Nginx/Apache with or without https.

2015-06-06 5:31 GMT+08:00 dhbolthausen <notifications@github.com>:

**Comment by dhbolthausen** [comment]
Thanks for the response. I was thinking I could designate the port number
via seafile.conf . If that is not a possibility, I suppose https will have
to do.
Thanks

**Comment by alvonellos** [comment]
I upgraded the seafile server to 4.1.6 and the client to 4.1.6 and they both work just fine. Great work you guys.

**Comment by allo-** [comment]
Same Problem here, but i do not have 8082 open, but use a reverse proxy on the subdomain seafile-data, and have set ``SERVICE_URL`` in ccnet.conf on the server.
It seems, that the new client is not respecting this, as it tries to use ``http://seahub-domain/seafhttp/protocol-version`` as URL (without port 8082).

**Comment by shoeper** [comment]
see http://manual.seafile.com/deploy/deploy_http_sync.html

**Comment by allo-** [comment]
I reconfigured it, but while i get ``{version: 1}`` on console for http://localhost:8082
i just get ``If you see this page, Seafile HTTP syncing component works.`` on ``https://server/seafhttp/protocol-version`` at the reverse proxy.
