### ISSUE TITLE
client 4.2.0 sync folder choosen bug

### ISSUE THREAD

**Issue by linuxhenhao** [haiwen/seafile-client#571]
I've installed client 4.2.0 on my windows pc.I think i found a bug about the choosen of the sync folder of  
the library. For example,the name of one lib is A,and I have a folder B, contains the contens of lib A.
I set the sync folder of lib A to B and the result is client 4.2.0 create a new folder named A under B,and 
downloaded all the thing to that folder.
In the past ,It's not working in this way,It should just compare the contents of lib A and folder B,sync them.
Is that a bug?
Best wishes to you

**Comment by freeplant** [comment]
In old version, there is an option "syncing with existing folder". This option is removed. And if you want to sync with existing folder, in your case, you have to change name 'B' into 'A', and select the parent folder.

**Comment by shoeper** [comment]
Why has the option been removed?
I've always used it.

**Comment by freeplant** [comment]
Because as feedback to us, many non-tech users find it confusing to sync a library 'A' to 'A-1' automatically when there is an old folder 'A'. So in the new version, we prompt a dialog and notify the user library 'A' will be merged with local folder 'A'.

We think syncing a library 'A' with folder with another name 'B' is very rare. 'A' can only sync with 'A' makes the concept simple.

**Comment by shoeper** [comment]
Ok I understand. Maybe you could also check if the selected folder has the same name as the library and sync directly in it in that case.

All in all as the tech user I think the implementition before was quite good. It was clear what happens in which case an there couldn't be any conflicts.

**Comment by linuxhenhao** [comment]
@freeplant on the contrary,I think what the new client do is confusing>LET US　SEE
I choose library A to sync to E:\B
the result is A<=>E:\B\A
But in the old one,
A to sync to E:\a folder
then A<=>E:\such that folder 

But You have the rights to do the decision thougt.
Also ,I'am wondering what the main code about this change?maybe I should change it back and compile a new client.Could you please give me some commit about change or where the decision code is located? Thanks!

**Comment by shoeper** [comment]
haiwen/seafile#1245

**Comment by Exceff** [comment]
I don't really like the new behaviour as it results in more confusion, at least for me.

Let's assume I want to sync a fictional program (let's call it "Awesome") and its data across multiple devices.

This program, Awesome, creates multiple folders in which it stores its data, in my fictional example this would be %AppData%\Awesome and %ProgramData%\Awesome (and, if I also want to sync the program's binaries, %ProgramFiles%\Awesome).

If I want to sync these three folders the program uses, I now have to create three libraries and name all of them "Awesome" to sync them to their parent folders (%AppData% etc.).
Before, I could name them "Awesome_AppData" or something like that and sync them directly to their respective folders which, in my opinion, was more convenient and tidy than the current situation.

There should definitely be an option for pro users to bring back the old behaviour as this recent chance takes away a fundamental feature of the software.

**Comment by killing** [comment]
Yeah quite a few expert users holds the same opinion. We'll add an option to enable this feature in 4.2.4 version.

**Comment by Chilledheart** [comment]
the new option is added in #601
