### ISSUE TITLE
compile error on ubuntu 15.04 / Qt 5.4

### ISSUE THREAD

**Issue by maxoodf** [haiwen/seafile-client#572]
Can not compile seafile-client with the following error -
make[2]: *** No rule to make target '../i18n/seafile_ca.qm', needed by 'qrc_seafile-client.cpp'.  Stop.

**Comment by Chilledheart** [comment]
@maxoodf it seems some Qt devtools are missing from your system. Can you install them by something like `sudo apt-get install qtbase5-dev-tools qttools5-dev-tools ` and retry compiling?

**Comment by maxoodf** [comment]
@Chilledheart thanks for your reply. I have complete Qt5 installation from qt-project.org, not from ubuntu packages. Could you suggest which devtools are missed?

**Comment by maxoodf** [comment]
@Chilledheart the same error with qt5 from ubuntu packages...

**Comment by Chilledheart** [comment]
@maxoodf you can try with this command `which lrelease` to confirm if these tools are visible to `cmake`. Anyway you need to set `PATH` before you invoke `cmake`:

`export PATH=$HOME/Qt5.4.1/5.4/gcc_64/bin:$PATH`

(suppose you have Qt 5.4 binary from `download.qt.io` installed at `$HOME/Qt5.4.1)

**Comment by Eduard90** [comment]
I have similar problem:
```
[  4%] Built target utils
make[2]: *** No rule to make target '/home/eduard/Develop/Cpp/Qt/Seafile/seafile-client/i18n/seafile_ca.qm', needed by 'qrc_seafile-client.cpp'.  Stop.
CMakeFiles/Makefile2:835: recipe for target 'CMakeFiles/seafile-applet.dir/all' failed
make[1]: *** [CMakeFiles/seafile-applet.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

Qt 5.4 installed in Ubuntu (through package manager apt-get).
Have any ideas?

**Comment by maxoodf** [comment]
@Chilledheart @Eduard90 lrelease and Qt tools are visible to cmake. But this error occurs on both - Qt5.4 from Ubuntu packages and Qt5.4 installation from qt.io.

**Comment by Eduard90** [comment]
```
eduard@eduard-VirtualBox:~/Develop/Cpp/Qt/Seafile/build$ which lrelease 
/usr/bin/lrelease
```

Well, how to make it work?

**Comment by Chilledheart** [comment]
@maxoodf @Eduard90 have you passed `-DUSE_QT5=on` flag to `cmake` to enable Qt5 build instead of Qt4 build. And what's more, can you check lrelease version by `lrelease -version` which should be something like `5.4.0`?

**Comment by maxoodf** [comment]
@Chilledheart yes, Qt5 is on, release version 5.4.1

**Comment by Chilledheart** [comment]
@maxoodf @Eduard90 I think I get your point now. Do you build client under the subdirectory such `build` folder instead of the top directory? Currently we need to build client in top of source directory due to some issue.

**Comment by Eduard90** [comment]
@Chilledheart All right! (when i run ```make``` in directory with sources)

**Comment by maxoodf** [comment]
@Chilledheart yes, I was trying to build client in a subdirectory. And now I've successfully built client in the project root directory.
