### ISSUE TITLE
Client 4.2.1 for Mac OS X doesn't open due to "can't be opened because it is from an unidentified developer"

### ISSUE THREAD

**Issue by darkcircle** [haiwen/seafile-client#576]
I have download client for mac os x at now, 
I can't open client due to blockage message.

I think that mac os x users wouldn't use until this issue is fixed.

**Comment by Chilledheart** [comment]
Hi @darkcircle 
Did you download the latest seafile client from official site `http://www.seafile.com/en/download/` ? Please double-check it before you want to open the downloaded package!
> You can check your package's sha1sum checksum if you have `sha1sum` tool installed, release 4.2.1 package's checksum is `36e80b676121db14282abc80ca99193872881b08`

You also need to change "Allow apps downloaded from" option in "Security &Privacy" to 
"Mac App Store and identified developers" before opening 
Seafile application. It is no harm but necessary to open Seafile application.

![screen shot 2015-05-17 at 10 33 45 pm](https://cloud.githubusercontent.com/assets/2123461/7670849/aa9c7f14-fce7-11e4-9b4e-2efcaa63b259.png)

**Comment by darkcircle** [comment]
ok. I'll try it now and reply for the result, again. Thank you ;-)

**Comment by darkcircle** [comment]
@Chilledheart Thank you for your advise. I set my system settings as you said,

and I resolved my problem by following the way of below url. It was little bit weird :S

http://osxdaily.com/2012/07/27/app-cant-be-opened-because-it-is-from-an-unidentified-developer/
