### ISSUE TITLE
Preconfigure not work

### ISSUE THREAD

**Issue by hokum13** [haiwen/seafile-client#578]
Try preconfigure for "%homepath%\seafile", but seafile return "unable to create preconfigure directory '%homepath%\seafile' ".
%homepath% - standart environment variable.

https://en.wikipedia.org/wiki/Environment_variable#Windows
https://github.com/haiwen/seafile-client-manual/blob/master/faq.md#faq

**Comment by Chilledheart** [comment]
Currently we don't support environment variable in preconfigure (only absolute path is allowed). Anyway we will add this support asap.

**Comment by hokum13** [comment]
Please, add this comment in FAQ.

**Comment by Chilledheart** [comment]
@hokum13 it should be corrected in https://github.com/haiwen/seafile-client-manual/pull/2
