### ISSUE TITLE
How to compile seafile-client on windows?

### ISSUE THREAD

**Issue by DeadWish** [haiwen/seafile-client#579]
checking for module 'libsearpc>=1.0'
  package 'libsearpc>=1.0' not found
CMake Error at D:/Program Files (x86)/cmake-3.2.2-win32-x86/cmake-3.2.2-win32-x86/share/cmake-3.2/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
CMake needs package 'libsearpc','libseafile' and so on.
How can I get the correct lib for windows?

**Comment by andrey-str** [comment]
In case you have ubuntu linux newar you and you don't need QtWebKit support you may check out this repo: https://github.com/andrey-str/seafile-mxe
There is a set of scripts for building seafile-client and it's deps on Linux using MXE toolchain.
QtWebKit doesn't work though after building with MXE(would like to know why)

**Comment by andrey-str** [comment]
It uses forked repos for building though, I had to make some very minor changes in source like de-captalize characters in names of some of included files.
