### ISSUE TITLE
Proxy settings support

### ISSUE THREAD

**Issue by MichiMunich** [haiwen/seafile-client#582]
Hi,

i have to roam through different networks. So i frequently have to change the proxy settings for the client. Is it possible to store the settings in a config file or the registry for windows users? So i can change the settings easily with a script. At the moment i have to reenter the settings all the time. Another option is to use the system settings (like firefox use for proxy settigns).

thanks
MichiDoe

**Comment by vascorppor** [comment]
I can confirm this issue. It would be best if the "system settings" (as set in Internet Explorer's preference menu) were used by default.

This may require retrieving and parsing a wpad file, which is in place in many corporate networks (https://en.wikipedia.org/wiki/Web_Proxy_Autodiscovery_Protocol)

**Comment by killing** [comment]
We'll add system proxy support into our plan.

**Comment by vascorppor** [comment]
Great, thanks!
