### ISSUE TITLE
OS X client 4.2.1 CPU consumption

### ISSUE THREAD

**Issue by stranak** [haiwen/seafile-client#594]
This is what my CPU Time stats look like. Seafile client CPU consumption spikes for several seconds maybe every 30 seconds.
![screen shot 2015-05-26 at 17 25 45](https://cloud.githubusercontent.com/assets/371106/7816130/d87e2cd4-03cc-11e5-9772-044dab5a9c7e.png)

As you can see it is the most energy sucking app on my computer and I have to turn it off when using the notebook without a power cord.

![screen shot 2015-05-26 at 17 15 49](https://cloud.githubusercontent.com/assets/371106/7816124/d379520e-03cc-11e5-9bac-20fd549f17ac.png)

**Comment by killing** [comment]
Do you use seafile to sync a large folder that have regular file changes?
The current file indexing procedure for Mac client is not very efficient.
So it may consume more CPU time if the folder is large.

2015-05-26 23:31 GMT+08:00 Pavel Stranak <notifications@github.com>:

**Comment by stranak** [comment]
I am not sure what qualifies as big. My current sync folder is about 2.2 GB and 5900 items. All that CPU time is consumed to determine that nothing has changed. I make changes very rarely.

**Comment by shoeper** [comment]
Do you use links? E.g. symblic links?

**Comment by stranak** [comment]
No files inside my sync folder are symbolic links, I just checked. I am pretty sure there are no hardlinks either.

**Comment by Chilledheart** [comment]
@stranak Yeah, I found another possible reason for this issue. In fact, I made a test package to fix it. Can you test this package?  the download link is below:

package: https://seacloud.cc/f/c280fa972b/
sha1sum: cb7cbde1ebf45a094f814bbb30b7baeffb6595ac

**Comment by stranak** [comment]
@Chilledheart Now this looks much better. After a quick test I can't see Finder sync status icons, but the CPU load is an order of magnitude better: stays bellow 1, spikes to 2-5 perc. while syncing.

I will report if anything changes, but this looks very good. What was the issue?

**Comment by Chilledheart** [comment]
@stranak yes, the extra cpu consumption is due to Qt bearer plugin which is totally unused in our project. Now we have removed it now.

**Comment by Chilledheart** [comment]
fixed in v4.2.3
