### ISSUE TITLE
Allow #recycle ignore directory

### ISSUE THREAD

**Issue by camlafit** [haiwen/seafile-client#597]
Hi

On a share, seafile act some pb to sync because a _#recycle_ directory is present. Looks loop on this directory too many changed.
Then I've tried to dissallow this directory as explained on ignore page : http://seafile.com/en/help/ignore/

The problem this directory start with a # then I tried with the rule _?recycle/_ but it's not really same.

After a try _?recycle/_ doesn't look ok 

was https://github.com/haiwen/seafile/issues/1244

**Comment by camlafit** [comment]
To complete, theses rules don't work :
?recycle/
?recycle/*
*recycle/
*recycle/*

#recycle directory is sent to seafile server.

**Comment by shoeper** [comment]
what about `#recycle/*`?
Is you seafile-ignore.txt in the root directory of the library?

**Comment by camlafit** [comment]
Hi

I've not tried #recycle/* as said in documentation # acts as a comment.
seafile-ignore.txt is in root directory and library (it's a sub library) is an empty directory to prevent pb as described in notes. Then I send an existing directory to empty library.

**Comment by shoeper** [comment]
Ok, sorry. Ignore what I've written.

?recycle/* should be right then, but seafile-ignore.txt ist quite buggy. I think the team should really improve it and add symlink support in addition.

**Comment by camlafit** [comment]
Hi

Then is not my fault :) Will be nice to have a regex rules in this file. 
Maybe will be nice to move to a standard regex solution, I presume exists some library to manage this and maybe less buggy. 
As seen on the documentation usage, regression will be limited (only * and ? as used) and maybe better in long time to maintened
