### ISSUE TITLE
Better progress indication

### ISSUE THREAD

**Issue by TimWolla** [haiwen/seafile-client#60]
I'd like to see better progress indication, if possible. For example when a library is indexing files (I suspect that this is: Adding to `blocks` folder?) there is no indicator of the progress.
The user has no idea, whether it's going fine or stuck somewhere, whether it will finish in a few seconds or in several hours.

So in this case a progress indication like 64% finished or indexed 42 of 1337 files would be great.

**Comment by timonoj** [comment]
So...is there any updates? We are past v3 now right?

**Comment by freeplant** [comment]
Since the feature is required by only very few users, we removed it from plan.
