### ISSUE TITLE
[OSX] Crash if 'Cancel'-button clicked in library password prompt

### ISSUE THREAD

**Issue by andi98** [haiwen/seafile-client#605]
Hi,
if I click Cancel or try to close this window, the OS X Client crashes:
![screen shot 2015-06-04 at 12 42 19](https://cloud.githubusercontent.com/assets/6323836/7982412/42c78dce-0ab7-11e5-99cb-9aab25579875.png)

Here are the log output: http://pastebin.com/bVefkEQ8

**Comment by Chilledheart** [comment]
fixed in https://github.com/haiwen/seafile-client/commit/fb6efca77bbdc7495973c1dda9dbbcad1b46fe1e
