### ISSUE TITLE
Feature request:  No sync when on battery.

### ISSUE THREAD

**Issue by deragon** [haiwen/seafile-client#608]
seafile-client takes a lot of io and cpu.  When on battery, there should be an option to ask it to suspend sync and allow manual sync.

For instance, if resuming from suspend and on battery, seafile-client should disable momentarily all syncs.  If plugged, then syncing could start automatically.  However, if the user desires, he could select a library and ask it to sync.

Linux Ubuntu 14.04 LTS Trusty Thar.

**Comment by thewilli** [comment]
:+1:

**Comment by shoeper** [comment]
even better would be a smart algorithm.

It could work like this: Seafile monitors changes, but does not index files immdiately. Instead it does index and upload data after a defined intervall.

**Comment by Shanto** [comment]
I have my projects/source code directory synced (with 100s of projects). Seafile is great from many points, but the only shortcoming is that whenever I launch my editor or do any modification to this large tree of small files, it takes Seafile quite a bit of time and CPU power to pick up changes. So, until proper support for ignoring (from indexing altogether) specific folders/patterns, a delay setting key would be very helpful as @shoeper suggests.
