### ISSUE TITLE
Tiny UI on linux retina displays

### ISSUE THREAD

**Issue by traverseda** [haiwen/seafile-client#614]
Need to scale on retina display on linux as well. Generally done by looking at the xserver's DPI.

Not a super important issue, it's still usable, just ugly.

**Comment by Chilledheart** [comment]
@traverseda You need to build seafile-client against Qt5.4 or later. See more https://github.com/haiwen/seafile/issues/895

**Comment by traverseda** [comment]
Ah, damn. Though you guys were running something custom.

Didn't show up in a cursory google of seafile on retina display. Thanks

**Comment by Chilledheart** [comment]
@traverseda perhaps we should add this to our faq. Anyway, thanks for reporting it!
