### ISSUE TITLE
Client always tries /seafhttp/protocol-version 

### ISSUE THREAD

**Issue by sinni800** [haiwen/seafile-client#616]
On my server I have used /sf for the reverse proxy to the seafile file server.

Seahub works fine with this, but the seafile client doesn't seem to have a way to tell it to use a different "File Server Root".

    #seahub_settings.py:
    FILE_SERVER_ROOT = 'https://yourseafile.com/sf/'

This is an oversight IMHO, now I have to change to seafhttp because otherwise it just wouldn't work.

**Comment by shoeper** [comment]
As written in the documentation this is hardcoded.

http://manual.seafile.com/deploy/deploy_http_sync.html

**Comment by sinni800** [comment]
It wasn't there when I first installed Seafile a bunch of versions ago, before HTTP sync even came up, heh. Maybe put it somewhere in the upgrading notices around where http sync was put into the client?

**Comment by shoeper** [comment]
You can upload a PR here if you like to
https://github.com/haiwen/seafile-docs

**Comment by sinni800** [comment]
@shoeper I would almost either put it into https://seacloud.cc/group/3/wiki/server-changelog/ or the client-changelog... Which isn't accessible to me.

Or this: https://github.com/haiwen/seafile-docs/blob/master/changelog.md as a "4.x" notice. Would you agree putting it there as a warning? "from Version 4.x on, the "FILE_SERVER_ROOT" should never be anything different than `/seafhttp` and reverse proxies should only originate from a path like this", something like this, better wording of course.

**Comment by shoeper** [comment]
I'm "just" user.
To be honest it is in the changelog: https://seacloud.cc/group/3/wiki/client-changelog/

I'd advice all people running servers and updating software to read the changelog. But maybe the manual could get an update. I'm going to have a look at it later.

**Comment by sinni800** [comment]
@shoeper Where is it in the changelog? Sorry if I was just blind, but I read the changelogs always.

**Comment by shoeper** [comment]
```
[..]
4.2.0 (2015/05/07)
[win] Support overlay icons for files based on the sync status
Use http syncing only
[..]
```

**Comment by sinni800** [comment]
@shoeper My argument is it says "http syncing only" but doesn't tell me that I should be aware that `/seafhttp` is the hardcoded path it uses. I know I never set that path anywhere but seahub, so it is, in a way logical not to mention it, heh, but people forget.
