### ISSUE TITLE
OS X 10.6.8 (32bit) should be oficially supported

### ISSUE THREAD

**Issue by dakira** [haiwen/seafile-client#619]
OS X 10.6.8 is still wildly popular and the most current version you can install on lots of hardware that is still working perfectly good in many offices around the world.

Clients of mine have lots of older generation Mac minis that can only update to 10.6.8 and thus have no option to use Seafile. Same as all the people who still have love for their 2007 Macbooks.

So it would be great if you could look into supporting that version again.

@Chilledheart and @simsasaile have done [some great work](https://github.com/haiwen/seafile-client/issues/140) to make older versions available. As soon as the servers force us to use HTTPS for syncing, those clients will be left out. So lets make this happen! ;-)

**Comment by simsasaile** [comment]
I just noticed that the seafile client 3.1.3 still works with the newest server version 4.3.0.
Here is the version I builded with great support from chilledheard for mac OSX 10.6 32bit: https://seacloud.cc/f/444afdc78a/?raw=1

Make sure the ports 10001 and 120001 are opened and configured under ccnet.conf and seafile.conf.
More infos here: https://forum.seafile-server.org/t/server-4-3-0-and-ports-10001-and-12001/2297
