### ISSUE TITLE
[Feature regression] Local name for synced libraries

### ISSUE THREAD

**Issue by Calrama** [haiwen/seafile-client#621]
In versions of seafile-client <= 4.1.6 is was possible to sync a library to a differently named folder, e.g. sync the library "sql" to the local folder "Structured Query Language". This way was a feature I consider very important as while I want all libraries on the server to have short, unique names, I want the synced folders to have verbose, longer names. Starting with seafile-client 4.2.4 I can only seem to be able to sync a library to a folder of the same name. This is a regression. I humbly ask you to please either restore this feature, or - if is was not removed but moved and I just cannot find it anymore - where it was moved.

Thank you for your time.

**Comment by shoeper** [comment]
+1

**Comment by freeplant** [comment]
In the settings->advanced, you can turn on the feature of syncing with existing folder with a different name.

**Comment by shoeper** [comment]
Ok, thanks for bringing this option back :)

**Comment by Calrama** [comment]
@freeplant I could've sworn that I looked at every option on that panel. Sorry for the wasted time and thank you for the fast reply.
