### ISSUE TITLE
4.2.4: libcurl failed / Couldn't resolve host name

### ISSUE THREAD

**Issue by torrentkino** [haiwen/seafile-client#631]
Hello,

we have at least one client, which fails to download any library when using the 4.2.4 version.

While digging in the client logs, I found:
> [06/19/15 13:44:48] http-tx-mgr.c(639): libcurl failed to GET https://docs.abc.de/seafhttp/protocol-version: Couldn't resolve host name.

The webpage is reachable from any webbrowser. I removed the software and all the ccnet and Seafile directories. Didn't help. Our Seafile server has a AAAA record while the affected client only has IPv4 connectivity. Removing the AAAA record didn't help either.

Installing the 4.2.4.1 from here[1] fixed the issue. I found this solution here[2].

Shall I upgrade all the clients to 4.2.4.1 or is it better to downgrade to 4.2.3 in case there are more people with this issue?

Kind regards,
Aiko

[1]: https://bintray.com/seafile-org/seafile/seafile-client-windows/4.2.4.1/view#files
[2]: https://forum.seafile-server.org/t/ccnet-not-resolving-host/1412/21

**Comment by ranger81** [comment]
Hi,
I just want to let you know that I experience a similar issue with the 4.2.4 client on Mac! Please also fix this in the Mac client.
Thanks

**Comment by Chilledheart** [comment]
Thanks for reporting it. I will look into this issue soon.

**Comment by Chilledheart** [comment]
@torrentkino In your case, you'd better upgrade to the latest version i.e. 4.2.4.1 currently.

**Comment by Chilledheart** [comment]
@ranger81 Can you open `https://server:8001/` with your browser? or use curl to visit it such as `curl  https://server:8001/api2/ping -v`

**Comment by ranger81** [comment]
@Chilledheart Yes, I can open https://server:8001 in my browser.
This is the output of curl `https://raspberrypi.fritz.box:8001/api2/ping -v -k`
```
* Hostname was NOT found in DNS cache
*   Trying 192.168.171.22...
* Connected to server (192.168.171.22) port 8001 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: blabla.no-ip.org
> GET /api2/ping HTTP/1.1
> User-Agent: curl/7.37.1
> Host: server:8001
> Accept: */*
> 
< HTTP/1.1 301 MOVED PERMANENTLY
* Server nginx/1.2.1 is not blacklisted
< Server: nginx/1.2.1
< Date: Wed, 24 Jun 2015 06:03:31 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Language, Cookie
< Location: https://server:8001/api2/ping/
< Content-Language: en
< 
* Connection #0 to host server left intact
```

**Comment by torrentkino** [comment]
@Chilledheart Ok.
 
There is only a little problem with 4.2.4.1. It has not been released officially yet. And it seems to be labeled as 4.2.4. This makes the automatic MSI deployment impossible because 4.2.4 has been installed already... You need to uninstall 4.2.4 manually first.

Kind regards,
Aiko

**Comment by Chilledheart** [comment]
@torrentkino that would be a blocking issue. Anyway version 4.2.5 is released today which you can upgrade for directly.

**Comment by torrentkino** [comment]
The automatic deployment of 4.2.5 is working smoothly. I close this issue.

**Comment by ranger81** [comment]
@Chilledheart Just to let you know, the problem still occurs for Mac users with client 4.2.5

**Comment by ranger81** [comment]
@torrentkino Please reopen this topic because for Mac users it's still not working properly

**Comment by Chilledheart** [comment]
Thanks for reporting it, @ranger81. Could you mail your log (including `seafile.log` and `applet.log`)  to my email rwindz0@gmail.com for further investigation?

**Comment by torrentkino** [comment]
I think it is better to create a new issue, because the windows issue is explicitly addressed in the changelog and really seems to fix my problem.
> [win] fix broken local DNS resolve

**Comment by ranger81** [comment]
@Chilledheart Good news, seems like I can't reproduce the issue anymore. I'll let you know once the issue occurs again.
Thanks for your support!

**Comment by ranger81** [comment]
@Chilledheart Sorry for bothering you again, but today the issue occured again. I have sent you my client logs. Please let me know if you need additional support.
Thanks

**Comment by Chilledheart** [comment]
@ranger81 After looking into your log files, I don't think it is related to dns resolving issue. Maybe you should try to look up your network settings (such as proxy settings or others possible issues). If your problem persists, you would better open a new issue for it. Thanks!
