### ISSUE TITLE
can't interact with system tray icon

### ISSUE THREAD

**Issue by valeth** [haiwen/seafile-client#634]
I can't open the context menu when right clicking the system tray icon and a left klick does not open the client window. As a result of that I have to terminate the client if I want to close it. Also, the settings menu is not acessible.

I'm using KDE Plasma version 5.3.1 on Arch Linux x86_64

**Comment by dndesigns** [comment]
Experiencing the same issue. Manjaro (Arch derivative) and KDE Plasma 5.3.2.

**Comment by Astate** [comment]
same probleme here

**Comment by MyerSmith** [comment]
Really annoying!

seafile-client-qt5 5.0.4-1 is under plasma-workspace 5.5.4-1 (archlinux) not rightclickable but visible.

qt4 Version works but is also not usable because xembedsniproxy is a KDE bughell..

**Comment by hcmh** [comment]
Is there any update on how to fix this? Since qt4 might become (or is already?) unsupported, it'd be very nice to have a functional client on KDE Plasma...

([here](https://aur.archlinux.org/packages/seafile-client/) someone claiming to be from the seafile team says that qt4 will become unsupported)

**Comment by src386** [comment]
Up.
Really annoying bug on Kubuntu 16.04 with Plasma 5...
I need to pkill seafile then start it each time I want to interact with it. And it seems impossible to access the parameters...

**Comment by nidico** [comment]
I just ran into that issue on kubuntu 16.04 and it's a major dealbreaker in our company, so it'd be great if this could be fixed soon!

**Comment by Astate** [comment]
Same problem here
Le 20 mai 2016 07:42, "Nicolas Dietrich" <notifications@github.com> a
écrit :

**Comment by nidico** [comment]
FYI: It's also broken on Plasma 5.6 and Qt 5.6 (from KDE neon repositories) on top of kubuntu xenial.

**Comment by lins05** [comment]
I tried the latest fedora 23 (KDE5 + qt5.6), and it seems to work without a problem.

![e](https://cloud.githubusercontent.com/assets/717363/15571993/aeb25b72-2370-11e6-82b4-38c224db4331.png)

I'll check ubuntu 16.04 + KDE5 later.

**Comment by lins05** [comment]
Fxied in https://github.com/haiwen/seafile-client/pull/802

**Comment by nidico** [comment]
Confirmed - works nicely in 5.1.2.
