### ISSUE TITLE
Viewing odf files in Chrome not working...

### ISSUE THREAD

**Issue by mhaze4** [haiwen/seafile-client#635]
By default there is an error  in the javascript console in the webodf.js file:
`Uncaught InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer').`
This error still persists in 4.2.3.

I was able to solve this issue by adding a newer version of webodf.
Not testet in other browsers, neither if the error also exists nor if my solution also works.
But if, maybe you can add a newer Version of webodf.

**Comment by freeplant** [comment]
Thanks for reporting. We will look into the problem.
