### ISSUE TITLE
FinderSync improvement: files inside synced libraries are not individually badged

### ISSUE THREAD

**Issue by Tycan** [haiwen/seafile-client#637]
On OS X, only the synced library has a status badge, whilst the files it contains have none.

Example:
![screen shot 2015-06-25 at 12 16 11](https://cloud.githubusercontent.com/assets/9666427/8352287/46f87dd0-1b34-11e5-802f-04a26c0050e4.png)

For comparison, the Windows client badges each file:
![capture](https://cloud.githubusercontent.com/assets/9666427/8352693/47ed40ce-1b37-11e5-964b-87fb30a9acf0.PNG)

**Comment by Chilledheart** [comment]
this part is not implemented yet.
related: #573

**Comment by Tycan** [comment]
All right, thanks for the attention.

**Comment by Chilledheart** [comment]
this part is done and the new release is out. you can try it now from http://www.seafile.com/download/
