### ISSUE TITLE
Add "check for updates" menu item

### ISSUE THREAD

**Issue by liayn** [haiwen/seafile-client#638]
There is no way (at least in the Win client 4.2.6) to manually check for updates.
Additionally I'm not sure, if the update check on application startup really works, as I never got any update info since I use this client.

**Comment by mathieu-mp** [comment]
Similar to #216 , plus a way to manually trigger the check that would be great.

**Comment by shoeper** [comment]
I'd also add server version on check.
E.g. right version for 4.1.1 Server seems to be 4.1.6 and 4.1.1 is still used at many places.

Furthermore I'm not sure if the client is already able to handle different versions for different operating systems (currently newest win version is 4.2.6 and linux 4.2.5).

Imho the check for a new version should be done on starting Seafile once per day and while running every few days (not sure if there are people out running it 24/7 but could be the case).

**Comment by liayn** [comment]
Ping

**Comment by liayn** [comment]
@shoeper I'm running it 24/7 since I my laptop is only on standby and is only rebooted rarely.
