### ISSUE TITLE
Sync error while cert is valid

### ISSUE THREAD

**Issue by mathieu-mp** [haiwen/seafile-client#641]
My server uses a valid certificate:
- I use Windows 8.1 x64, and Internet Explorer (System CA Store) considers the certificate as valid.
- I checked my certificate via digicert.com, sslshopper.com, various web browsers, and it is valid.

Up to 4.2.1, my client works great.
Since v4.2.2:
- I can add an account, no error
- I cannot resume a sync, or trigger a desync/resync, or add a new library: it hangs on "connecting to server". seafile.log says: "http-tx-mgr.c(639): libcurl failed to GET https://XXX/seafhttp/protocol-version: Peer certificate cannot be authenticated with given CA certificates". Connections to port 10001 are still triggered (aren't we supposed to sync only via https?).

Only way to bypass: to check "do not check cert"... I just can't ask every client to check this.
Isn't it a bug in cert check at a certain point of the process, while the bug doesn't appear when adding a new account? Is LibCurl using its own CA Store, or the System CA Store?

**Comment by killing** [comment]
The GUI uses Qt, while the syncing engine uses libcurl. They're different.
The client extracts system CA store (on your machine) to a file and use the
CA certs in that file. So we're using system CA store.
Does your server certificate includes complete certificate chain? The
client only extracts the root CA certs. So if your certificate uses
intermediate CA it won't work unless you include them into your server cert
file.

2015-06-30 1:52 GMT+08:00 mathieu-mp <notifications@github.com>:

**Comment by mathieu-mp** [comment]
Hey, thank you for answering.

I just can't understand why would libcurl only extract the root CA certs.
It seems to lead to errors, and this is not the common behaviors.

Any other client considers the cert as valid.
Is it really all about my cert? Can't we consider to improve the client?

**Comment by shoeper** [comment]
Whom did you get your cert from?

**Comment by mathieu-mp** [comment]
Gandi, 1st french domain reseller, 6th european, 1.7M domains.
Official Intermediate CA, certified by Comodo.

...so, are we sure about our way to check certificates?

**Comment by shoeper** [comment]
See: https://wiki.gandi.net/en/ssl/intermediate
Gandi uses an intermediate certificate so you MUST provide the full chain.

**Comment by mathieu-mp** [comment]
I did read the Gandi and Apache docs and double-check my conf.
I do provide the full chain via SSLCertificateChainFile (as advised in the official Apache documentation) and my cert is considered as valid by digicert.com, sslshopper.com and symantec.com

I got a warning about my SHA-1 signature, but that shouldn't break compatibility before the end of this year. Would libCurl be a bit too strict?
I repeat that even the Seafile QT interface considers the cert as valid.

**Comment by killing** [comment]
@mathieu-mp Can you provide me with an account on your server for testing? You can send information to my mail address.

**Comment by mathieu-mp** [comment]
@killing Thank you, but please understand that I am reluctant to give access to my server.

I dived into SSL exchanges via Wireshark and I could confirm that the intermediate certificate is provided by the server. Even when LibCurl tries to trigger a sync/resync.

![certificate_paquet_from_server](https://cloud.githubusercontent.com/assets/8644213/8488524/72fe6db0-2113-11e5-8e66-97b4ffadc9a3.jpg)

And the client keeps looping on SSL Alert "Unknown CA". So it's definetly something wrong with the client.
This is just a guess and I am no expert, but: Doesn't the import of system CA store override the intermediate certificate which is provided by the server? You might have much better ideas than mine...

**Comment by killing** [comment]
Well the GUI code use Qt's http library. I read the code and find one thing we may have to do. For Window Vista or upper, the local root CA store is just minimal. I can't find Comodo root CA on a Windows 7 machine. Additional CA can be fetched from Windows update server. Qt's http library does that and we don't.
We'll try to do this and make a package for you to test.

**Comment by killing** [comment]
Further explanation can be found here: https://social.technet.microsoft.com/Forums/windows/en-US/06d2ab2c-d296-4e82-bb9b-9a0476e0cecb/incomplete-list-of-root-certificates
Actually you can try to use IE to access your Seafile website and the root CA may be downloaded to your computer automatically. Then you can use Seafile client without problem.

**Comment by mathieu-mp** [comment]
I did try to access to my website via IE, but it won't improve seafile-client behavior.

Is the version of LibCurl used in seafile-client able to validate a certificate using an intermediate CA provided by the server?

**Comment by shoeper** [comment]
It works here with StartSSL,  they also use an intermediate certificate.

**Comment by killing** [comment]
No it's not related to libcurl. The root CA list libcurl uses is passed in
by our code. Our code just extracts root CA list from system store. So the
problem is that your CA is not in the system store. Can you check that?

2015-07-04 0:18 GMT+08:00 mathieu-mp <notifications@github.com>:

**Comment by mathieu-mp** [comment]
Hey,

I can confirm IE (which uses System CA Store) validates the cert and all the chain:
![validation ie](https://cloud.githubusercontent.com/assets/8644213/8527572/91495332-240d-11e5-8243-d203f9f4f067.jpg)

Top CA issuer is AddTrust:
![top ca issuer](https://cloud.githubusercontent.com/assets/8644213/8527713/5ec0f64e-240e-11e5-9e5e-a6f150b58f98.jpg)

And AddTrust is in the system CA Store:
![root ca store](https://cloud.githubusercontent.com/assets/8644213/8527729/7060b3e4-240e-11e5-84fd-4621c8f5beee.jpg)

And you kept telling me that the only part extracted by the client was system **root** CA store and nothing more... Hell yeah, there is another **intermediate** cert in CA Store involved in my case:
![intermediate-userfirst](https://cloud.githubusercontent.com/assets/8644213/8528240/684a488a-2401-11e5-95d5-3126fdb2f5f1.jpg)

So, wow... I changed my SSLCertificateChainFile to include the other intermediate cert... And it works!

First of all, **thank you for your support**.
Then, I still wonder why the client wouldn't extract root **and** intermediate cert store?!? This is so uncommon, I do repeat that even digicert and sslhopper did validate my cert without any warning, which means I had a production-proof https service! The very first link you provided guys was the recommendation from Gandi who don't even care of telling people about this intermediate cert (and they have tons of clients) So... You helped me to find a way to bypass the lack of versatility of seafile-client, but I am pretty sure that this behavior could be enhanced for future users, who might fast get into trouble. Or at least a specific section in the docs, urging people to check that their server provides the **very full intermediate CA cert chain**, which is not that straightforward.

Again, thank you.

**Comment by shoeper** [comment]
By the way: Many android devices do not have intermediate certificates (at least mine from startssl works in chrome on desktop but only works on android (samsung s4) with chrome when configuring full chain).

**Comment by mathieu-mp** [comment]
You're right and I can confirm that explains and solves the cert error I had on Android seafile client.
Great! From this point of view, I will suggest to Gandi to mention the intermediate cert in their howto.

**Comment by killing** [comment]
@mathieu-mp Glad it works. We'll extract intermediate CA too in the next version.

**Comment by mathieu-mp** [comment]
@killing Hey. I might be solved by now. Can you confirm the intermediate CA is extracted in the current versions? So we can close the case. Thanks.
