### ISSUE TITLE
How to restore data on system crash?

### ISSUE THREAD

**Issue by ghost** [haiwen/seafile-client#65]
Hello,

how can I recover data from the seafile-data directory if I have lost the rest of my server installation (web, user database, ...). I need to help a colleague with this who cannot even tell which version of Seafile was used.

Is there a way to restore the content from the seafile-data directory? Unfortunately, there is only a backup of "blocks" and "commits" available.

**Comment by zenusarcadi** [comment]
Hello same issue here - but i have still have the seafile.db - mine just went corrupt during a upgrade to 7.1
