### ISSUE TITLE
linux client can't log in via Shibboleth SSO

### ISSUE THREAD

**Issue by khorkin** [haiwen/seafile-client#650]
Hi, 
I use Seafile Pro version with Shibboleth SSO. In Windows both browser and client works perfectly.
In Linux browser works - ok, but client doesn't log in via Shibboleth.
Client connect to Seafile server (nginx), receive redirect to ADFS identity provider, connect to identity provider and receive 401 Authorization Required. Seafile client doesn't sent any auth data (kerberos) to identity provider.

**Comment by lins05** [comment]
@khorkin Thanks for reporting, we'll look into this.

**Comment by lins05** [comment]
@khorkin I have tried with two seafile servers with shibboleth login, but I can't reproduce this problem. 

- What's the linux distro and seafile client version you use?  (I'm using ubuntu 14.04 with the latest 4.2.6 version)
- Can you create a temporary account on your server and send the credentials to `shuai@seafile.com` so that I can do futher testing?

**Comment by khorkin** [comment]
@lins05 I use the latest version from here "http://seafile.com/downloads/" - 4.2.5 64bit on Ubuntu 14.04.2 64 bit
Unfortunately I can't create temporary account in our AD. Anyway you can't reproduce the problem outside local network, so as no kerberos.
I can provide more information, like kerberos trace
export KRB5_TRACE='/tmp/trace_krb5'
$ seafile-applet
...
...
but its empty.
Wireshark and nginx logs on Seafile server show me
SSL connection to seafile server, HTTP requests

4.1.6:
IP - - [06/Jul/2015:13:12:20 +0300] "GET /shib-login?shib_client_version=4.1.6&shib_platform_version=&shib_platform=linux&shib_device_name=ekhorkin&shib_device_id=82fe11d65d0d8bd9d7f7da5ca2a4a17b9591759b HTTP/1.1" 301 178 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.21 (KHTML, like Gecko) Seafile Client Safari/537.21"
IP - - [06/Jul/2015:13:12:20 +0300] "GET /shib-login/?shib_client_version=4.1.6&shib_platform_version=&shib_platform=linux&shib_device_name=ekhorkin&shib_device_id=82fe11d65d0d8bd9d7f7da5ca2a4a17b9591759b HTTP/1.1" 302 154 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.21 (KHTML, like Gecko) Seafile Client Safari/537.21"


4.2.5
IP - - [07/Jul/2015:07:54:18 +0300] "GET /shib-login?shib_client_version=4.2.5&shib_platform_version=&shib_platform=linux&shib_device_name=ekhorkin&shib_device_id=82fe11d65d0d8bd9d7f7da5ca2a4a17b9591759b HTTP/1.1" 301 178 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.21 (KHTML, like Gecko) Seafile Client Safari/537.21"
IP - - [07/Jul/2015:07:54:18 +0300] "GET /shib-login?shib_client_version=4.2.5&shib_platform_version=&shib_platform=linux&shib_device_name=ekhorkin&shib_device_id=82fe11d65d0d8bd9d7f7da5ca2a4a17b9591759b HTTP/1.1" 301 178 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.21 (KHTML, like Gecko) Seafile Client Safari/537.21"
IP - - [07/Jul/2015:07:54:18 +0300] "GET /shib-login/?shib_client_version=4.2.5&shib_platform_version=&shib_platform=linux&shib_device_name=ekhorkin&shib_device_id=82fe11d65d0d8bd9d7f7da5ca2a4a17b9591759b HTTP/1.1" 302 154 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.21 (KHTML, like Gecko) Seafile Client Safari/537.21"


than SSL connection to identity provider and one HTTP request to it with 401 answer. Identity provider, as I know support Kerberos and NTLM auth. In browser when kerberos disable I may authentificate via NTLM.

**Comment by khorkin** [comment]
UPD:
linux client receive 401 Auth requied with Headers:
GET /adfs/ls/?SAMLRequest=.... HTTP/1.1
User-Agent: curl/7.35.0
Host: Identity provider hostname
Accept: */*

< HTTP/1.1 401 Unauthorized ( The server requires authorization to fulfill the request. Access to the Web server is denied. Contact the server administrator.  )
< WWW-Authenticate: Negotiate
< WWW-Authenticate: Kerberos
< WWW-Authenticate: NTLM
< Connection: Keep-Alive
< Pragma: no-cache
< Cache-Control: no-cache
< Content-Type: text/html
< Content-Length: 2073  

And client return this instead retry request with Kerberos, as an example.

**Comment by killing** [comment]
Since the Windows client works, I think it's not a problem in our code. One possibility is that the Qt library on your Linux system doesn't support Kerberos or NTLM authentication. @lins05 Can you have confirm this guess?

**Comment by khorkin** [comment]
I suppose that problem may in this line:
api/api-client.cpp
const int kMaxRedirects = 3;
As I can see, client get 2 redirects to Identity Provider and 1 on Identity Provider. I'll try to build version with increased number of redirects.

**Comment by lins05** [comment]
>  As I can see, client get 2 redirects to Identity Provider and 1 on Identity Provider. I'll try to build version with increased number of redirects.

@khorkin I don't think so. That code (api/api-client.cpp) is only used to send api requests, which is not relevant to the shibboleth login procedure. Besides, even if they are related,  the code should fail on both windows and linux, but as you said, the windows client can login successfully.

**Comment by khorkin** [comment]
@lins05 I look out for information about support kerberos by Qt but can't find any data. Also I look into your code:
src/shib/shib-login-dialog.cpp
```
ShibLoginDialog::ShibLoginDialog(const QUrl& url,
                                 const QString& computer_name,
                                 QWidget *parent)
```
in this class (function) you connect and handle only ssl error:
```
connect(mgr, SIGNAL(sslErrors(QNetworkReply *reply, const QList<QSslError>&)),
            this, SLOT(sslErrorHandler(QNetworkReply*, const QList<QSslError>&)));
```
and don't handle auth errors
```
SIGNAL(authenticationRequired(QNetworkReply*, QAuthenticator*)
```
How do you think is it possible reason?

**Comment by lins05** [comment]
@khorkin emm, that makes sense, but I wonder how could the windows client login your server without this problem? Does it prompt a dialog to let you enter the kerberos credentials?

**Comment by khorkin** [comment]
In the latest Windows version I see Web-dialog where I can enter login and password or put "Shibboleth" button. In the latest linux version (4.2.8) and earliest too, I received the window with 401 Authorization Required error. If I click right mouse button and reload page I see white window.
I don't know why there are no problem in windows client, it's may be due to "deep windows integration" - Windows computer in AD domain.

**Comment by lins05** [comment]
> In the latest Windows version I see Web-dialog where I can enter login and password or put "Shibboleth" button. In the latest linux version (4.2.8) and earliest too, I received the window with 401 Authorization Required error. If I click right mouse button and reload page I see white window.

Can you take two screenshots for me on windows and linux?

**Comment by lins05** [comment]
@khorkin I have received your email and the attached screenshots. So the windows client can load

What's the version of the qt library on your linux machine? Also as I noted in the screenshot of the windows client (seafile-windows-client-2.png), the webview is not redirected to the provider page, so I wonder how is your apache server configured?

**Comment by khorkin** [comment]
@lins05 I use Ubuntu 14.04, so my qt is 4:4.8.5+git192-g085f851+dfsg-2ubuntu4.1

I use nginx: webview has been redirected:
```
IP - - [28/Jul/2015:10:34:11 +0300] "GET /shib-login?shib_client_version=4.2.8&shib_platform=windows&shib_platform_version=&shib_device_id=4621d9914a739af5837e5aed4fcbe57248649a24&shib_device_name=win8-vbox HTTP/1.1" 301 178 "-" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) Seafile Client Safari/538.1"
IP - - [28/Jul/2015:10:34:11 +0300] "GET /shib-login/?shib_client_version=4.2.8&shib_platform=windows&shib_platform_version=&shib_device_id=4621d9914a739af5837e5aed4fcbe57248649a24&shib_device_name=win8-vbox HTTP/1.1" 302 154 "-" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) Seafile Client Safari/538.1"
IP - - [28/Jul/2015:10:34:11 +0300] "POST /Shibboleth.sso/SAML2/POST HTTP/1.1" 302 40 "https://www.IDP.com/adfs/ls/auth/integrated/?SAMLRequest=..." "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) Seafile Client Safari/538.1"
IP - - [28/Jul/2015:10:34:11 +0300] "GET /shib-login/?shib_client_version=4.2.8&shib_platform=windows&shib_platform_version=&shib_device_id=4621d9914a739af5837e5aed4fcbe57248649a24&shib_device_name=win8-vbox HTTP/1.1" 302 5 "https://www.IDP.com/adfs/ls/auth/integrated/?SAMLRequest=..." "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) Seafile Client Safari/538.1"
IP - - [28/Jul/2015:10:34:11 +0300] "GET /home/my/ HTTP/1.1" 302 5 "https://www.IDP.com/adfs/ls/auth/integrated/?SAMLRequest="..."Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) Seafile Client Safari/538.1"
IP - - [28/Jul/2015:10:34:11 +0300] "GET /accounts/login?next=/home/my/ HTTP/1.1" 301 5 "https://www.IDP.com/adfs/ls/auth/integrated/?SAMLRequest=..." "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) Seafile Client Safari/538.1"
IP - - [28/Jul/2015:10:34:11 +0300] "GET /accounts/login/?next=/home/my/ HTTP/1.1" 200 3811 "https://www.IDP.com/adfs/ls/auth/integrated/?SAMLRequest=..." "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) Seafile Client Safari/538.1"
IP - - [28/Jul/2015:10:34:12 +0300] "POST /seafhttp/repo/folder-perm HTTP/1.1" 200 2 "-" "-"
```

There are part of nginx.conf:
```
    location / {
        include /etc/nginx/conf.d/fcgi.cfg;
    }

    location /seafhttp {
        rewrite ^/seafhttp(.*)$ $1 break;
        proxy_pass              http://127.0.0.1:8082;
        proxy_connect_timeout   600s;
        proxy_read_timeout      600s;
    }
    location = /shibauthorizer {
        internal;
        include         /etc/nginx/fastcgi_params;
        fastcgi_pass    unix:/opt/shibboleth/shibauthorizer.sock;
    }
    location /Shibboleth.sso { # FastCGI responder for Shibboleth data
        include         /etc/nginx/fastcgi_params;
        fastcgi_pass    unix:/opt/shibboleth/shibresponder.sock;
    }
    location = /shib-login/ { # Shibboleth handled location
        more_clear_input_headers 'Variable-*' 'Shib-*' 'Remote-User' 'REMOTE_USER' 'Auth-Type' 'AUTH_TYPE' 'Http-Eppn' 'HTTP_EPPN' 'Http-Remote-User' 'HTTP_REMOTE_USER';
        shib_request /shibauthorizer;
        include /etc/nginx/conf.d/fcgi.cfg;
    }
```

and fcgi.cfg:
```
fastcgi_pass    127.0.0.1:8000;
fastcgi_read_timeout 600s;
fastcgi_send_timeout 600s;
fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
fastcgi_param   PATH_INFO           $fastcgi_script_name;

fastcgi_param   HTTPS               on;
fastcgi_param   HTTP_SCHEME         https;
fastcgi_param   SERVER_PROTOCOL     $server_protocol;
fastcgi_param   QUERY_STRING        $query_string;
fastcgi_param   REQUEST_METHOD      $request_method;
fastcgi_param   CONTENT_TYPE        $content_type;
fastcgi_param   CONTENT_LENGTH      $content_length;
fastcgi_param   SERVER_ADDR         $server_addr;
fastcgi_param   SERVER_PORT         $server_port;
fastcgi_param   SERVER_NAME         $server_name;
fastcgi_param   CLIENT_CERTIFICATE  $ssl_client_cert;
fastcgi_param   REMOTE_ADDR         $remote_addr;
fastcgi_param	REMOTE_USER         $http_remote_user if_not_empty;
```

**Comment by heis2201** [comment]
Referencing #845 (for ver 5.1.1 rpm package)
