### ISSUE TITLE
4.2.x client hangs on "waiting for sync" with a "Parse response failed" error

### ISSUE THREAD

**Issue by tehXor** [haiwen/seafile-client#651]
Hi there,

I'm using a seafile server behind a nginx proxy (HTTPS only with a valid signed certificate) for about 2 years now. And now all my users who upgraded their client to a 4.2.x version cannot sync their libraries anymore. The client shows a green icon and says that all servers are connected in the bottom left corner, however every library is stuck with the gray cloud icon with the three dots "waiting for sync". Manual resyncing is not working either. I upgraded the server from it's old 3.x.x version to 4.2.6 (Seafile behind the nginx proxy is running on a Windows Server) but this didn't change anything as well. When the clients downgrade to a 4.1.x client version everything starts to work as expected again at once.

My only clue so far is this frequent error message in the seafile.log of the faultily 4.2.x clients:
`http-tx-mgr.c(970): Parse response failed: '[' or '{' expected near '<'.`
All other seafile logs (also server-side) seem to look exactly the same compared to when 4.1.x clients are connecting/syncing/whatsoever.

Any ideas what's going on? Is this a bug and/or can I work around it with a server-side configuration change? 

Thanks for any help.

**Comment by killing** [comment]
The error message you see is irrelevant. Actually for newer server, the
error message won't appear any more. It's just a false alarm. However
Windows server hasn't been updated to latest yet.
Are you sure this message is the only error you can see in the client log?
I suspect it's a problem with your https configuration. You can check this
manual: http://manual.seafile.com/deploy/deploy_http_sync.html
Can you post your complete client seafile.log?

2015-07-06 20:39 GMT+08:00 Till <notifications@github.com>:

**Comment by tehXor** [comment]
Thanks for the fast answer.

 `seafhttp` was configured as sub directory in my case as seafile is running as one, too: `location /seafile/seafhttp {...}`.
And I was under the impression that as the Seafile server is only reachable through the nginx proxy and the `location /seafile {...}`, `location /media {...}` and `location /seafile/seafhttp {...}` directives from the outside world, that HTTPS sync would work properly already. But maybe it didn't or maybe something changed with the server upgrade from my quite old version I did now to evaluate the problem, too... If you have the time, it would be nice if you could give me a short info regarding how it was possible for old clients and server to work with these location configurations.

In any case I figured from your answer that the clients actually are requesting `/seafhttp` and not `/seafile/seafhttp`, so I copied the `location /seafile/seafhttp {...}` directive to `location /seafhttp {...}` and now everything seems to work.
Do you think I can safely use this configuration and drop the `location /seafile/seafhttp {...}` now?

**Comment by killing** [comment]
The client requires the URLs for syncing to be under /seafhttp, nothing
else. Yes, you can safely drop the /seafile/seafhttp location.

2015-07-06 21:48 GMT+08:00 Till <notifications@github.com>:

**Comment by tehXor** [comment]
All right. Thanks for the help!
