### ISSUE TITLE
Sync Data folder on network share

### ISSUE THREAD

**Issue by Semmelbroesel24** [haiwen/seafile-client#656]
HI,

if i want to sync a folder that is on an network share it doesn't work.
I connect the folder and the first sync work, now i changed something the client do nothing.
If i say sync now then it works. \\server\share\ or z:\share\ all the same.

Windows Client 4.2.7 Ubuntu Server 4.2.3

Greetings Mario

**Comment by shoeper** [comment]
Seafile cannot monitor changes of network shares.
I'm also not sure if it is supportet by network shares. This would require the server to notify all currently connected clients about changes being made on the server or by other clients.

**Comment by moobyfr** [comment]
I used several months seafile-client (3.X) with a network share, it was working fine except the reconnect/unsync issue which is adressed now in the parameters.

**Comment by killing** [comment]
You can now set periodic sync on network shares.
