### ISSUE TITLE
Client caches first added server and never let it go

### ISSUE THREAD

**Issue by UnAfraid** [haiwen/seafile-client#658]
Hello,

Today i've decided to try seafile i've installed both server and the client.
After some hours of unsuccessful attempts to get it working with ssl and windows server i notice that once i put the url of the server whatever changes i made to client it still sticks to the first i added and refuses to update the new.
I uninstalled it and installed it again and once i start it logs displays that it connects to the first address..
Before i even added one!

I cleaned my registry, deleted ccnet folder from my account nothing helps it still remembers it from somewhere and i cant find where it kept it.

**Comment by freeplant** [comment]
Just uninstall the client, during the uninstallation, when a dialog popup asking "whether to delete all configs", choose Yes.

**Comment by UnAfraid** [comment]
I tried that, didn't worked.

**Comment by Chilledheart** [comment]
@UnAfraid could you try to delete the key `HKEY_CURRENT_USER\Software\Seafile\Seafile Client\UsedServerAddresses` manually and restart the client?

**Comment by UnAfraid** [comment]
I tried that as well, didn't helped at all

**Comment by Chilledheart** [comment]
@UnAfraid or do you have `PreconfigureServerAddrOnly` set as the [faq manual][faq] describes?

[faq]: https://github.com/haiwen/seafile-user-manual/blob/master/en/faq.md

**Comment by UnAfraid** [comment]
I Deleted the entire "HKEY_CURRENT_USER\Software\Seafile" package

**Comment by Plumarh** [comment]
https://github.com/haiwen/seafile-client/issues/826
