### ISSUE TITLE
sync status icon overlay differs on some files

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-client#663]
Some files get a wrong icon. I do have this "problem" mainly on the desktop. I think it has been introduced with 4.2.7 release.
See the following screenshot for details (first icon is the "good" one, second a wrong one):

![](https://mno.pw/0833)
(this only appears from time to time)

**Comment by freeplant** [comment]
We don't have such icon in Seafile. It should come from another software. Maybe a conflict with another software?

**Comment by shoeper** [comment]
Strange, I don't have another sync software/software with status icons. Will have another look later on.
Could be that windows has the icon by default.

**Comment by shoeper** [comment]
By the way there is still an issue with the icons. From time to time there are totally wrong icons.
