### ISSUE TITLE
Seafile client Mac OSX - Files downloaded but not appearing on the Finder window

### ISSUE THREAD

**Issue by mathieuchenebit** [haiwen/seafile-client#67]
Hello,

I installed a server yesterday and I downloaded a client on my two macs. 

I put some files on my Libray on the first mac. Then, on the second one, My Library has the check meaning it's synchronized but I can't see my files on the finder. After some tries, I found the issue. The files are downloaded, but not appearing on the Finder WIndow. Strange issue?

![seafile-client-issue](https://f.cloud.github.com/assets/5978444/1940775/07a19c2c-7f7f-11e3-9312-0c4b11c467a4.png)

**Comment by fabien-michel** [comment]
I'm pretty sure this bug is the same as #524

**Comment by davidfdriscoll** [comment]
Any word on this? I'm having the same problem. It's kinda irritating.

**Comment by shoeper** [comment]
> Any word on this? I'm having the same problem.
ask apple to fix their software.

**Comment by fabien-michel** [comment]
@shoeper as you can read here https://github.com/bdkjones/fseventsbug/wiki/realpath%28%29-And-FSEvents
this is a major bug that occure on OS X 10.6 to 10.10. A lot of seafile users (and other syncing software) are concerned. Apple recognized this bug and it concern a core part os OS X. They will fix it but I don't thinks the fix will be applied in older versions (Yosemite and before). I thinks Seafile devs should look at the  workaround mentioned in #524

**Comment by shoeper** [comment]
Yeah I've already read that issue. There is a fix would be nice to integrate it but that's not the way to go. Apple has failed very hard regarding this and they should correct their missbehaviour but as usual selling products and having nice design is more importand than fixing major issues the average apple user isn't able to identify and won't report any missbehaviour to apple but instead to Software developers.
