### ISSUE TITLE
[OS X] Sync File/Folder Tags

### ISSUE THREAD

**Issue by andi98** [haiwen/seafile-client#674]
Since OS X 10.9 Finder supports Tags for files and folders. It would be nice, if Seafile syncs them through all my machines :)

**Comment by fablarosa** [comment]
Dropbox and other sync clients do support both Finder and Openmeta tags from a long time, any plan to add this feature?

**Comment by rmrnc** [comment]
Any progress on this 3yrs old request?

**Comment by freeplant** [comment]
No, we don't have a plan to support this feature yet.
