### ISSUE TITLE
OSX: seafile-ignore.txt currently broken with wildcards

### ISSUE THREAD

**Issue by tokred** [haiwen/seafile-client#680]
Sorry for the duplicate (https://github.com/haiwen/seafile/issues/1308), but actually this is a client-side issue:

I have the following seafile-ignore.txt in the library root directory:
````
# Lightroom Previews directories
*Previews.lrdata/
*/*Previews.lrdata/

# Lightroom Backup directory
Backups/
Backups/*

Temporary Import Data.db
Temporary Import Data.db-journal

*.swp
````
Unfortunately, Seafile completely ignores all of these rules - it keeps syncing e.g. vim's .swp files and Lightroom's `<foo_catalog> Previews.lrdata` directories.

I am almost sure that it worked some versions ago (4.0.x or so?).

Server: Linux@4.2.3
Client: Mac@4.2.7

**Comment by shoeper** [comment]
Have you used the search before opening this?

**Comment by tokred** [comment]
I did, nothing else was related or relevant.

**Comment by nicke** [comment]
i solved this issue for me by compile the latest version for my own.

with latest client (4.3.0) from webside i had the same problem in OSX 10.10.

I did:
```
brew tap Chilledheart/seafile
vi /usr/local/Library/Taps/chilledheart/homebrew-seafile/seafile-client.rb
```
changed line 7:
-  head "https://github.com/haiwen/seafile-client.git", :branch => "4.1"
+  head "https://github.com/haiwen/seafile-client.git", :branch => "master"

```
brew install seafile-client --head
cd /usr/local/Cellar/seafile-client/HEAD
open Seafile\ Client.app
```

**Comment by killing** [comment]
The current client version fails to ignore folders. The result is that the folders are synced, but the files inside the folders are ignored. This will be fixed in the next client update.

I cannot confirm the problem with "*.swp" rule. It works on my machine.
