### ISSUE TITLE
Windows 8.1 - Can't rename in left panel of explorer

### ISSUE THREAD

**Issue by mathieu-mp** [haiwen/seafile-client#685]
For some versions now, when seafile-client is open, I can't rename a folder in the left panel of Win8.1 explorer.
Letters typed to rename the folder erase the previous ones without letting the whole directory name to be written, then Seafile hastes itself to sync the freak rename. (Exemple: "ry" instead of "Directory")
Looks like seafile interferes with the name of the directory even before the renaming is confirmed.

I got to understand that it does not happen right at seafile-client start, but happens after some work into the directories. If I close seafile-client it stops instantly.

Could you investigate? Thanks.

**Comment by shoeper** [comment]
It does work here.
