### ISSUE TITLE
OSX: Cannot start client

### ISSUE THREAD

**Issue by themisanthrope** [haiwen/seafile-client#690]
When trying to launch the client (4.2.8), I only get as far as selecting a base directory. After that, the client disappears but still appears to be running (`ps aux | grep seaf`).

Killing the client (plus ccnet and the daemon) and re-launching it shows the client briefly, but it disappears again.

I have tried removing `~/.ccnet` directory, the `~/Seafile` directory and the `com.sea*` files from `~/Libraries/Preferences/`, and I only get as far as selecting a base directory again.

Using El Capitan beta on this Mac, I haven't attempted to upgrade the client on my Yosemite Mac yet, in case it stops working there too.

Is this a known issue? Can I provide any further information for you?

**Comment by killing** [comment]
When you run ps aux | grep seaf, what process can you see?
What can you see in ~/.ccnet/logs/applet.log and seafile.log?
Some people also reported that Seafile doesn't work on El Capitan beta. But
may be it's just the problem with the "beta". In Yosemite it should work.

2015-08-02 0:56 GMT+08:00 Adam Richmond-Gordon <notifications@github.com>:

**Comment by themisanthrope** [comment]
This is after removing all config and preference files;
`$ ps aux | grep seaf`
`adam             2093   0.0  0.0  2480776   6060   ??  S    10:10am   0:00.02 /Applications/Seafile Client.app/Contents/MacOS/../Resources/seaf-daemon -c /Users/adam/.ccnet -d /Users/adam/Seafile/.seafile-data -w /Users/adam/Seafile`
`adam             2091   0.0  0.3  2660720  45764   ??  S    10:10am   0:00.57 /Applications/Seafile Client.app/Contents/MacOS/seafile-applet`
`adam             2099   0.0  0.0  2424596    516 s000  R+   10:11am   0:00.00 grep seaf`

`$ ps aux | grep ccnet`
`adam             2092   0.0  0.0  2470664   5588   ??  S    10:10am   0:00.02 /Applications/Seafile Client.app/Contents/MacOS/../Resources/ccnet -c /Users/adam/.ccnet`
`adam             2101   0.0  0.0  2434836    752 s000  S+   10:11am   0:00.00 grep ccnet`
`adam             2093   0.0  0.0  2480776   6060   ??  S    10:10am   0:00.03 /Applications/Seafile Client.app/Contents/MacOS/../Resources/seaf-daemon -c /Users/adam/.ccnet -d /Users/adam/Seafile/.seafile-data -w /Users/adam/Seafile`

`$ cat ~/.ccnet/logs/applet.log`
`[08/02/15 10:10:47]starting ccnet:  ("-c", "/Users/adam/.ccnet")`
`[08/02/15 10:10:48]trying to connect to ccnet daemon...`
`[08/02/15 10:10:48]connected to ccnet daemon`
`[08/02/15 10:10:48]starting seaf-daemon:  ("-c", "/Users/adam/.ccnet", "-d", "/Users/adam/Seafile/.seafile-data", "-w", "/Users/adam/Seafile")`
`[08/02/15 10:10:48]seafile daemon is now running`
`[08/02/15 10:10:48][Rpc Client] connected to daemon`
`[08/02/15 10:10:48][MessageListener] connected to daemon`
`[08/02/15 10:10:49]Unable to get config (int) value download_limit`
`[08/02/15 10:10:49]Unable to get config (int) value upload_limit`
`[08/02/15 10:10:49]Unable to get config (int) value proxy_port`
`[08/02/15 10:10:49][Rpc Client] connected to daemon`

I had wondered if it was just down to using the OS beta - I will try the same build on my Yosemite Mac shortly and let you know if it works.

**Comment by themisanthrope** [comment]
Latest update has fixed this issue \o/
