### ISSUE TITLE
Linux: CLI client compatibility?

### ISSUE THREAD

**Issue by themisanthrope** [haiwen/seafile-client#691]
I am attempting to use the CLI client (4.0.4) with the server version 4.3.1 - both 64 bit on Ubuntu Server 14.04 LTS.

Client init and start works as expected, but when trying to download (or sync), I get this;
`# ./seaf-cli download -l e86c45a1-xxxx-xxxx-xxxx-885abb60d671 -s https://sync.xxxxxx.co.uk -d /data/localreplica/ -u xxxx@xxxxxx.co.uk -p xxxxxxxx`
`Starting to download ...`
`Library e86c45a1-xxxx-xxxx-xxxx-885abb60d671 will be downloaded to /data/localreplica`
`Traceback (most recent call last):`
`File "/data/seafile-cli-4.0.4/bin/seaf-cli.py", line 791, in <module>`
`main()`
`File "/data/seafile-cli-4.0.4/bin/seaf-cli.py", line 787, in main`
`args.func(args)`
`File "/data/seafile-cli-4.0.4/bin/seaf-cli.py", line 434, in seaf_download`
`email, random_key, enc_version, more_info)`
`File "/data/seafile-cli-4.0.4/lib64/python2.6/site-packages/pysearpc/client.py", line 112, in newfunc`
`return fret(ret_str)`
`File "/data/seafile-cli-4.0.4/lib64/python2.6/site-packages/pysearpc/client.py", line 25, in _fret_string`
`raise SearpcError(dicts['err_msg'])`
`pysearpc.common.SearpcError: Argument can't be NULL'`

I am wondering if there is some compatibility issue between the two - library URLs seem to have changed;
Server 4.0.4 `https://alpha.xxxxxx.co.uk/repo/f172bc12-xxxx-xxxx-xxxx-be494a33b510/`
Server 4.3.1 `https://sync.xxxxxx.co.uk/#my-libs/lib/e86c45a1-xxxx-xxxx-xxxx-885abb60d671`

Any ideas? :)

**Comment by killing** [comment]
The cli client is obviously very out of date. We'll update it soon and fix
the compatibility problem.

2015-08-02 1:10 GMT+08:00 Adam Richmond-Gordon <notifications@github.com>:

**Comment by themisanthrope** [comment]
Okay, great stuff. I will use the graphical client for the time being. 

Let me know if you need any testing doing for new CLI builds when you get chance to update it :)

**Comment by jsl303** [comment]
Any timeline to fix this?
I downloaded seafile-server-4.3.1 and seafile-cli-4.0.4 on Ubuntu 15.04. I'm running on a server, so I have no access to GUI. When I try to download a library, I got:
Starting to download ...
Library 736e5ed8-2e42-4a96-b303-0bd543fb4b1a will be downloaded to /media/seafile
Traceback (most recent call last):
  File "/root/seafile/seafile-cli-4.0.4/bin/seaf-cli.py", line 791, in <module>
    main()
  File "/root/seafile/seafile-cli-4.0.4/bin/seaf-cli.py", line 787, in main
    args.func(args)
  File "/root/seafile/seafile-cli-4.0.4/bin/seaf-cli.py", line 434, in seaf_download
    email, random_key, enc_version, more_info)
  File "/root/seafile/seafile-cli-4.0.4/lib64/python2.6/site-packages/pysearpc/client.py", line 112, in newfunc
    return fret(ret_str)
  File "/root/seafile/seafile-cli-4.0.4/lib64/python2.6/site-packages/pysearpc/client.py", line 25, in _fret_string
    raise SearpcError(dicts['err_msg'])
pysearpc.common.SearpcError: Argument can't be NULL

**Comment by Webunity** [comment]
The page at https://www.seafile.com/en/download/ shows a new client (4.3.2) but the download links are not yet working.

**Comment by shoeper** [comment]
By the way:  Why have uploads been moved to bintray? Imho having them on bitbucket was very nice. One was able to get them from there forever. If it is too much work for you maybe you can give me (https://bitbucket.org/shoeper/) permission to upload the releases there, to have a full release history.

**Comment by lins05** [comment]
@shoeper Bitbucket doesn't provide public api for uploading files, while bintray does. We switched to bintray so that we can upload the packages more automatically by using the api. 

We'll fix the download link soon.

**Comment by qk4l** [comment]
The problem returned with Seafile Server 4.4.6.

I have seaf-cli 4.3.2 and it worked correct but today I noticed that I can't added new new library to sync (via sync or download command). Previously added libraries works correctly. 

Checked with two different Seafile Server 5.0.2 and 4.4.6.

**Comment by diegox80** [comment]
I have legacy server with debian6 (Squeeze) and I have the same issue.
I can't install new cli version: glibc is outdate.
Any workaround?

**Comment by shoeper** [comment]
Can you use an older version? It might not have the newest improvements but should still work.

**Comment by diegox80** [comment]
There is a table of compatibility between client and server versions
or do I have to proceed by trial and error?
A client machine is debian squeeze 6
Thanks for support
