### ISSUE TITLE
Feature: In-Client update

### ISSUE THREAD

**Issue by nilsbyte** [haiwen/seafile-client#692]
I want to suggest a new feature to make updating the client more easy.

If a new version is available, the client should bring up an update window with changelog and the choices to update, skip or abort (similar to the Photosync companion app; the Mac version http://bit.ly/1K18N8T and the Windows version http://bit.ly/1IBosKR).

This would be much more comfortable than opening the Seafile download page, downloading the file, executing it and running the installation.

**Comment by shoeper** [comment]
+1

**Comment by MarcoWue** [comment]
+1
