### ISSUE TITLE
Sync problems with Win10

### ISSUE THREAD

**Issue by irmlerc** [haiwen/seafile-client#693]
Hello,

I'm using seafile for nearly a year, absolutely without problems. But now I've installed a fresh installation of Win10 on my notebook and installed the seafile 4.2.8 client, which doesn't sync :(

I see all the libraries inside the seafile-box, but if I click at "Sync library", it just comes the message "connecting with server..." (messages are translated from German, they will be a little bit else in English, I guess).

And then it tries to connect and connect and connect...
I already tried to disable the windows firewall, but it didn't change the situation.

It works fine with other clients on Win7, Win8.1 and Android, so it's a problem with the client.

Could you please tell me, how I can get run seafile also under Win10?
Oh: I also tried seafile 4.3.0 - it has the same effect...
Server version is "seafile-server-3.1.6"

**Comment by freeplant** [comment]
Does client version 4.3.0 work on your Win7? I suspect it is a server side issue.

**Comment by irmlerc** [comment]
On Win7 I've an older version installed. The Win7 computer is my productive computer. I'd rather not try to install a newer one, if it could occure troubles.
Why you think it's a server-side issue? Version incompatibility?

**Comment by freeplant** [comment]
Seafile client 4.2.8 and 4.3.0 only use HTTP syncing protocol. Old server does not support this feature.

**Comment by irmlerc** [comment]
So the only way is to update the server-version and then update all client versions, right?

**Comment by irmlerc** [comment]
I solved the problem now with upgrading the server to version 4.3.1.
Thank you for your help :)

**Comment by ampkeen** [comment]
Hello!
I have a quite similar problem but the solution doesn't work for me.
After reading this issue I updated the seafile-server to version 4.3.1., my environment is a centos 6 server and as webserver I'm using nginx.
As clients i tried v4.2.8. and 4.3.2. on win10 and 4.3.1. on linux. The clients are displaying 'connecting server...'. All my libraries are correctly shown but not syncing.

On win7 with seafile-server 4.1.2. everything worked fine. With win10 it never worked for me.
I tested everything with a fresh server installation on a test environment and I got the same problem.

Do you have any advice for me? Thank you!

**Comment by ampkeen** [comment]
Hello again!
I got it, it took only a few hours^^.
Everything is described in the seafile manual (http://manual.seafile.com/deploy/deploy_http_sync.html).

I'm using a self-signed SSL certificate and cause of that I had to enable the following client setting:
	Settings->Advanced->Do not verify server certificate in HTTPS sync

Sorry for posting without a real issue and thanks for your awesome project!
