### ISSUE TITLE
Explorer extension status icon stays "syncing" on file overwrite

### ISSUE THREAD

**Issue by DevCybran** [haiwen/seafile-client#695]
This issue affects Seafile client 4.2.8 on windows.

Whenever a already synced file is overwritten (for example by copying another file with the same name in the explorer) and the new file has the same content as the old file (they are identical), the status icon in the explorer changes to "syncing" and will never change to "success".

When a file is overwritten by another file with different content, the icon changes to "success" properly. It looks like Seafile "forgets" to change the icon when no upload is necessary.

**Comment by killing** [comment]
Hi, this issue should have been fixed in 4.3.1 version. Please have a try.

**Comment by DevCybran** [comment]
I have just tested 4.3.1 and can confirm this is fixed now. Thank you very much!
