### ISSUE TITLE
Linux, KDE 5 Plasma: Systray Icon not shown

### ISSUE THREAD

**Issue by 85pando** [haiwen/seafile-client#697]
As stated [on Martin Gräslins Blog](http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/) the KDE 5 Plasma Desktop changes the way it handles the systray.

For Qt4 bases programs a user needs to install [sni-qt](https://launchpad.net/sni-qt) for this to work. For Qt>5.4 is is said to be solved.

For most distros this is available, but the Debian Maintainer(s) [don't seem to want to include it](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=712938). There is a [workaround](http://alien.slackbook.org/blog/support-for-old-school-xembed-system-tray-icons-in-plasma-5/) though (which is still quite ugly).

**Comment by Astate** [comment]
same problem here

**Comment by shoeper** [comment]
https://github.com/haiwen/seafile-client/issues/634
