### ISSUE TITLE
Configurable sync interval in client

### ISSUE THREAD

**Issue by benoit74** [haiwen/seafile-client#703]
Hi,

I would like to be able to configure the sync interval in the client. 

Currently the value seems to be quite agressive and it has the drawback to :
* consume a lot of data (it is a problem when using a limited data usage phone connection for instance)
* create a lot of versions when files are regularly saved on disk without real purpose in most cases (manual sync can always be done if it is something urgent)
Is it something feasible/complex?

**Comment by shoeper** [comment]
* You can actually pause the connection when you're on mobile data.
 * a lot of versions are no problem.

**Comment by benoit74** [comment]
* what if I still want to sync on mobile data but once per hour is sufficient? I have to reactivate sync manually every hour? We are back to svn times of manual "svn update" ... 
* a lot of versions are a not a problem for the software/computer and this is very good. Thanks. But my point is that they are a problem for the human behind it. When I have to scroll 3 pages below to find the version of yesterday, this is not a very lean UX. Not speaking about the version of last week ...

Of course, this is not a mandatory feature, but it would be great to have it and I don't think that the investment would be very high to provide it (but I'm not the software guy)

**Comment by killing** [comment]
This has been added.
