### ISSUE TITLE
Mac client not working if user is not admin

### ISSUE THREAD

**Issue by benoit74** [haiwen/seafile-client#704]
Hi,
The client hangs on first sync of first library (never retrieved any file) on a Mac Client.
The problem seems to be linked to the fact that the user running the client has no admin privileges.
The issue seems to be linked to a refused access to the keychain (at least it is what Mac OS says).
Do you already encountered this / have any clue on its explanation ?

**Comment by lins05** [comment]
Thanks for reporting.

> The issue seems to be linked to a refused access to the keychain (at least it is what Mac OS says).


Can you show us any screenshot?

**Comment by benoit74** [comment]
Indeed you just have to give the right to access the keychain to seafile (as admin of course). Any idea why seafile needs to access the keychain ?

**Comment by siucdude** [comment]
I have the same issue, looks like 4.3.4 and 4.4.0 both Seafile client for MAC start and the application runs but nothing displays, the appellate does not show, when i start it with sudo command I get the window to show up, but in folder root, and permissions are all goofed up.
