### ISSUE TITLE
Add client certificate support

### ISSUE THREAD

**Issue by fabien-of-hill** [haiwen/seafile-client#707]
Having optional client authentication would be great

**Comment by fabien-of-hill** [comment]
See pull request #739

**Comment by freeplant** [comment]
Thanks very much. Is this a feature to only allow a client with a certain certification file to be able to access the server? In the server side, we need to turn on client certification in Nginx/Apache?

**Comment by fabien-of-hill** [comment]
Yes, you can configure your server to allow connection only from client providing a valid certificate (signed by a CA). Here's my apache configuration file, look *client authentication* section.  
  
Careful it's not a production configuration file.  

```
<VirtualHost *:9001>
  ServerName foo.net
  DocumentRoot /var/www
  Alias /media /var/lib/seafile/foo.net/seafile-server-latest/seahub/media

  <Location /media>
    Require all granted
  </Location>

  ErrorLog ${APACHE_LOG_DIR}/error.log
  LogLevel warn
  CustomLog ${APACHE_LOG_DIR}/ssl_access.log combined

  # usual SSL server parameter
  SSLEngine On
  SSLCertificateFile      /etc/ssl/foo.net.crt
  SSLCertificateKeyFile   /etc/ssl/foo.net.key
  SSLCertificateChainFile /etc/ssl/foo.net_chain.crt

  SSLProtocol ALL -SSLv2 -SSLv3

  # client authentication
  SSLVerifyClient require
  SSLverifyDepth 1
  SSLCAcertificateFile /etc/ssl/foo_ca.crt

  RewriteEngine On

  #
  # seafile fileserver
  #
  ProxyPass /seafhttp http://127.0.0.1:8082
  ProxyPassReverse /seafhttp http://127.0.0.1:8082
  RewriteRule ^/seafhttp - [QSA,L]

  #
  # seahub
  #
  RewriteRule ^/(media.*)$ /$1 [QSA,L,PT]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^(.*)$ /seahub.fcgi/$1 [QSA,L,E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</VirtualHost>
```

**Comment by freeplant** [comment]
The file syncing layer (seaf-damon) also need client certification. Your pull request only modified seafile-client (the GUI layer). Can the file syncing work?

**Comment by fabien-of-hill** [comment]
My bad, I'm able to browse but you're right, downloading is failing.  

I've found more about seafile desktop client design on http://manual.seafile.com/develop/server-components.html. It seems the only way to achieve what I wanted (client auth.+only apache port exposed) isn't possible right now.  
If find some free time I could add a mode working like the mobile app (performance isn't an issue).

**Comment by markusweb** [comment]
yes please. Client Certificate in seafile client would be great

**Comment by pos-ei-don** [comment]
I'd be very interested aswell,

**Comment by egofelix** [comment]
Any plans to support this in future releases?

**Comment by freeplant** [comment]
We don't have such a plan.
