### ISSUE TITLE
Dialogs are not diplayed properly on 4k displays

### ISSUE THREAD

**Issue by AuspeXeu** [haiwen/seafile-client#709]
I have a 4k display on my laptop and when I choose to sync a libary the dialog looks like this:

![image](https://cloud.githubusercontent.com/assets/2115696/9698783/dab3ca9c-53c5-11e5-9860-d82647ee5e78.png)

And I cannot resize it.

**Comment by Oter2k** [comment]
I've got the same (oposite) problem as well. The main window (libraries and stuff) of the application is terribly underscaled. Tiny. I need to stick my nose right up to the monitor to be able to see what's there.

**Comment by lins05** [comment]
Have you tried [How to enable HiDPI support on Windows](http://help.seafile.com/en/faq.html#-a-id-enable-windows-hidpi-support-a-how-to-enable-hidpi-support-on-windows)?

**Comment by Oter2k** [comment]
Thanks, that fixed it on my 4K-monitor, though when I drag it over to my 1920x1200-monitor it is quite oversized. Don't know if automagic / adaptive scaling is possible?

I did encounter a bug where UI elements "fell out", i.e. the square around the Star icon, and the star itself, vanished, leaving a hole through which I could see my desktop.

Btw, you might want to update the FAQ with where exactly the "environment variable" is located and how to set it. I faffed about quite a bit before I came on to that is was "Control Panel --> System --> Advanced System Settings --> Advanced tab --> Environment Variables"

**Comment by lins05** [comment]
> when I drag it over to my 1920x1200-monitor it is quite oversized. 
Could you please take a screenshot?

Thanks for the advice of updating the FAQ. Would update it later.

**Comment by Oter2k** [comment]
https://anonm.gr/up/c8d9.gif

Explorer in the bacground for scale.
Be advised that I am running both a 4K and a 1920x1200 HD monitor, which Windows doesn't seem to like very much. There is some scaling issues at play, so the Seafile client is not the only one affected. And it comes and goes a bit. As of writing this, the client is scaled correctly.
