### ISSUE TITLE
4.3.3 syncs MS office .tmp files although disabled in settings

### ISSUE THREAD

**Issue by liayn** [haiwen/seafile-client#712]
The client syncs `.tmp` files even though I disabled sync of temporary Office files.

Generally it would be great to have some sort of "ignore pattern", where I can exclude certain file extensions.

**Comment by shoeper** [comment]
> The client syncs .tmp files even though I disabled sync of temporary Office files.

I don't think .tmp is a tmp office file.

Anyway, have a look at https://www.seafile.com/en/help/ignore/

**Comment by liayn** [comment]
![sync-dialog](https://cloud.githubusercontent.com/assets/222377/9770527/db59c794-5730-11e5-83b1-e97b6303a64a.jpg)

At least this happens every time I save an Excel sheet. Notice the .tmp file and some other file which is moved.

**Comment by shoeper** [comment]
You are right, I've been able to reproduce this with Excel 2013. I also wasn't able to stop this by creating a seafile-ignore.txt with `*.tmp`.

Next I've had a look at the activity stream (this is only in Pro Edition). The tmp file is listed there, but making a double click on it only shows up my excel document and no tmp file.
There is imho also a bug. Looking at all actions lists only changes files. I think it should list all files (changed, created, deleted, moved/renamed).

**Comment by freeplant** [comment]
We will look into the issue.

**Comment by liayn** [comment]
Since I can't reproduce the issue on 5.0.7 and Win10, I'm closing it.
