### ISSUE TITLE
Home folder conflicts with system path

### ISSUE THREAD

**Issue by huegelc** [haiwen/seafile-client#715]
Client 4.3.3 (Linux)
Server 4.3.2 (Linux)

I´m trying to sync my home folder with seafile but everytime I want to add that folder it failes with "conflicts with system path"
I have already moved the seafile-data dir outside /home/user and changed seafile.ini accordingly but still no joy. Is there a hidden value that prevents syncing home folders? 

seafile.ini: /Seafile/.seafile-data
Home folder : /home/user

Thank you

**Comment by shoeper** [comment]
It is quite likely that there is a folder named `.seafile-data` used by the client. I can think of that this folder prevents syncing.

**Comment by huegelc** [comment]
I´ ve checked that; there´s only a .ccnet folder with logs/configs there but I don´ t see how to change the location of that folder.

**Comment by shoeper** [comment]
Ok, in the folder is a file named `seafile.ini` in which the path for the seafile-data folder can be found. Where is it in your case?

**Comment by huegelc** [comment]
Thank you for your reply. 
` /Seafile/.seafile-data`

**Comment by shoeper** [comment]
Ok, so at least that doesn't lead to the conflict.
Is there any folder in your home folder, that is already synced with Seafile?

**Comment by huegelc** [comment]
Oh, yes. There is a folder sync`d  at the moment.

**Comment by shoeper** [comment]
Ok then I'm pretty sure that folder is causing the conflict. You can synchronise each folder only with one library at a time and cannot sync folder which has subfolders already being synced.

**Comment by huegelc** [comment]
got that thank you. I have completely removed that folder from sync but it throws me the same error.

**Comment by shoeper** [comment]
I'd try to restart seafile.

**Comment by huegelc** [comment]
no joy :(

I see in the logs some error but this refer to a repo I have long deleted.
` Failed to access worktree /home/user/mounts/cloud/Top Secret for repo 'Top Secret'(d6b767c0)` 
Is there a way to "resync" seafiles db?

**Comment by shoeper** [comment]
Have you enabled the setting not to unsync unexisting libraries?

**Comment by huegelc** [comment]
*slap* ;) ok that solved issue no.2

**Comment by huegelc** [comment]
here is the exact error message in the log file:

`[09/13/15 18:20:05] clone-mgr.c(1217): Worktree path conflicts with seafile system path.`

**Comment by shoeper** [comment]
Hmm, I don't have further ideas here. Maybe one of the Seafile devs helps you. Good luck.

**Comment by huegelc** [comment]
Thank you for your time.

**Comment by alcinos** [comment]
Hi, 
Just to mention that I'm facing the exact same issue

**Comment by kevinvalk** [comment]
See ticket #723 for temporary fix

**Comment by huegelc** [comment]
Thanks I´ll give it a try.

**Comment by huegelc** [comment]
Thanks, works
