### ISSUE TITLE
Sync progress indicator on the client always hangs at 0%

### ISSUE THREAD

**Issue by MarcoWue** [haiwen/seafile-client#717]
Library sync progress shown on the Seafile client applications always hangs at 0% altough I can follow the sync progress in Windows Explorer, seeing more and more files getting green checkmarks.

Also I would like to see a file sync list in future Seafile client versions that shows which files have been recently transferred, which have are waiting to be synced and which are currently transferred.

Seafile Client 4.3.4 on Windows 8.1 / Seafile Server 4.3.3 via NGINX

**Comment by huegelc** [comment]
Can confirm this behaviour on Linux client 4.3.4

**Comment by shoeper** [comment]
> Also I would like to see a file sync list in future Seafile client versions that shows which files have been recently transferred, which have are waiting to be synced and which are currently transferred.

It is called activity stream and part of the pro edition.

> Library sync progress shown on the Seafile client applications always hangs at 0%
Is it an enrcrypted libary?

**Comment by MarcoWue** [comment]
> Is it an enrcrypted libary?
Yes, I forgot to mention that.
