### ISSUE TITLE
[bug] deleting files in cloud file explorer in a read only library leads to client crash

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-client#719]
It is currently possible to try to delete files within a read only library via cloud file explorer. Doing this leads to a client crash (the files are NOT getting deleted, so that works properly).

At least on 4.3.4 it first shows it cannot delete those files and crashes on confirming the dialog.

Proposed solution: Hide delete action in read only libraries.

Client: 4.3.3 & 4.3.4

**Comment by lins05** [comment]
Thanks for reporting, we'll fix this.

**Comment by lins05** [comment]
@shoeper on double check I found currently the "delete file" menu item is grayed out if the current library is read-only in the cloud file browser.

<img width="636" alt="screen shot 2015-09-17 at 19 29 13" src="https://cloud.githubusercontent.com/assets/717363/9931938/8623f4aa-5d72-11e5-8fd5-871bed03fc77.png">

If I change the share permission from read-write to read-only after the cloud file browser is opened, I can trick seafile client to send a delete file request to server, but server would return the correct 403 Foribdden in this case, so I can't reproduce the crash you described. I have tested it on both windows and mac clients.

What's the OS you use? and the version of your seafile server? Can you reproduce this problem with the seacloud.cc or cloud.seafile.de?

**Comment by shoeper** [comment]
I use the Windows version. The menu is not grayed out there. Server is 4.3.3 Pro (don't think this is the problem). And I had client 4.3.3 and found the bug. Then I upgraded to 4.3.4 and the bug is also there.

**Comment by lins05** [comment]
@shoeper So you get the read-only library from group share, I get it. I was trying with a read-only library shared by another user directly. Would reproduce & fix it.

**Comment by lins05** [comment]
@shoeper I still can't reproduce the bug, the "delete file" menu item is always grayed out in read-only libraries. I tried both with local development server and seacloud.cc, and tried with both unencrypted and encrypted libraries.

I'll ask others to try to reproduce it.

**Comment by lins05** [comment]
@shoeper btw have you tried the latest beta release 4.4.0 on https://www.seafile.com/en/download/?

**Comment by lins05** [comment]
> 3. upload some file with the admin user

@shoeper Do you upload files from web browser or in the cloud file browser?

**Comment by shoeper** [comment]
I did upload them via cloud file browser for the test. But those at home were uploaded by the client (via sync).
