### ISSUE TITLE
client 4.3 on Linux opensuse 13.2 doesnt work as expected

### ISSUE THREAD

**Issue by vpereira** [haiwen/seafile-client#722]
I have my seafile working with the mac client. Everything works as expected 

However on Linux I have the following problem.  I was able to compile the code, but as soon as I start it, calling seafile-applet, I juse see the window to configure the default folder, and after that, I don't see the next options, like to configure my server, user and password.. is that the expected behavior, known problem or regression?

**Comment by vpereira** [comment]
I think there is a problem with QT5.. on Fedora 22, I had the same problem. It just worked after that I updated QT, to QT5.5..

**Comment by tneo** [comment]
The seafile-applet crashes with a segmentation fault error as soon as I try to access it through it tray icon. I've upgrade my opensuse 13.2 to QT5.5 to no avail.

**Comment by vpereira** [comment]
hm thats already something new.. which seafile-applet are you using? we have some compiled on buildserver:

http://download.opensuse.org/repositories/Cloud:/Seafile/openSUSE_Tumbleweed/Cloud:Seafile.repo
http://download.opensuse.org/repositories/Cloud:/Seafile/openSUSE_13.2/Cloud:Seafile.repo
http://download.opensuse.org/repositories/Cloud:/Seafile/openSUSE_13.1/Cloud:Seafile.repo

Note that in fedora it crashed as well with segmentation fault und as soon as i updated my QT to 5.5 it worked as expected..

**Comment by vpereira** [comment]
wow good news. On a tumbleweed box, running QT 5.5 I was able to compile and run the seafile-applet without problems.. I will push it to the buildserver.. I think the problem is to compile seafile-client with a version of QT and run with another..  Like compile with 5.0 and run with 5.5.

**Comment by tneo** [comment]
I'm using the applet as given in the Cloud repo for 13.2. Can you push it to 13.2 Cloud repo as well?

**Comment by vpereira** [comment]
https://build.opensuse.org/project/show/home:vpereirabr:Seafile

however I'm not sure if it will work. I tested on a KDE opensuse 13.2 and
it worked, however on a gnome based 13.2 the problem still there.. maybe
some runtime lib is missing.. dunno.

**Comment by tneo** [comment]
I installed you're compiled file, but the applet is not showing the icon even. Nothing seems to be happening, although ksysguard reports it is running.

**Comment by drhedberg** [comment]
I am using the new Leap 42.1 KDE and would like to use the seafile client.  Please let me know how to stay updated for Leap version.  thanks

**Comment by Gribs** [comment]
It seems that this problem is quite rare. I've got the same symptoms: I've installed seafile frome the http://download.opensuse.org/repositories/Cloud:/Seafile/openSUSE_Tumbleweed/ and it did not work: seafile window did not appear at all. 

So I've decided to convert .deb package from the seafile website into rpm. It was quite easy, but I've installed additional libcrypto and libssl, because converted rpm was requiring libcrypto.so.1.0.0. Those packages did not fix that requirement, so I've just ignored it. After that I've figured out that all libs was installed into /usr/libs, while seafile-applet was looking them into /usr/lib64 (I honestly don't know why), so I've symlinked them. At the end I was able to run seafile, but with corrupted systray icon. 

I think that it is possible to create rpm file for opensuse from the original deb. I almost did it, but I don't have any experience with packaging, and I am quite new in opensuse and rpm distros at all. But I think if someone would be able to package it properly and upload to the opensuse repo, it would be great. If someone need, I can give upload my rpm.

**Comment by yield65** [comment]
@vpereira Hi, are you using the opensuse build service?
Any luck compiling it to target leap or are you focusing on another version and architechture?

**Comment by werneazc** [comment]
You should at the repository to zypper:
```
zypper addrepo http://download.opensuse.org/repositories/Cloud:Seafile/openSUSE_Tumbleweed/Cloud:Seafile.repo
zypper refresh
```
Now install needed packages:
`zypper install seafile seafile-client, ccnet python-pysearcpc`
Append /usr/sbin to your PATH variable (e.g. in fish shell):
`set -x PATH $PATH /usr/sbin`

At least start seafile-client and set up configuration. 
This works for me under Thumbleweed.

**Comment by Loris1123** [comment]
I am having the sameproblems as @Gribs.  
I installed seafile-client via zypper, as @werneazc described, but after I launch it, I see nothing at all. The synchronization is not working aswell.  
I am using Suse Tumbleweed.

**Comment by werneazc** [comment]
Have you added the /usr/sbin path to your PATH variable? 
Add 
`export=PATH=/usr/sbin:$PATH`
into your .bashrc file in your home folder. Restart and it should work.
It's important to edit the PATH. I set up a new PC with Leap 42.2 and my solution worked also there.

**Comment by mhingston** [comment]
@werneazc I've just tried updating my path but still no GUI or output on the console. :(

**Comment by werneazc** [comment]
What package repository did you install? Have you used the right repository which fit to your installed opensuse version?

For Leap 42.2 I used the repository 

> http://download.opensuse.org/repositories/Cloud:/Seafile/openSUSE_Leap_42.1/Cloud:Seafile.repo

Then I continued with the installation as described.

**Comment by mhingston** [comment]
I'm using Tumbleweed.

    sudo zypper addrepo http://download.opensuse.org/repositories/Cloud:Seafile/openSUSE_Tumbleweed/Cloud:Seafile.repo
    sudo zypper refresh
    sudo zypper install seafile-client
    seafile-applet 
   ^C (hangs)

**Comment by werneazc** [comment]
@mhingston I don't understand your comment. Have you also installed all mentioned requirements mentioned above in my first post?

> Now install needed packages:
  `zypper install seafile seafile-client ccnet python-pysearcpc`

**Comment by mhingston** [comment]
@werneazc thanks, I was missing `python-pysearcpc`

**Comment by werneazc** [comment]
@mhingston Don't mention it.
