### ISSUE TITLE
Directory structure uploaded to cloud while parent directory in seafile-ignore.txt

### ISSUE THREAD

**Issue by kevinvalk** [haiwen/seafile-client#726]
I have an extensive ``seafile-ignore.txt``file, but within it I have an ignore for AppData. Because I am syncing my complete user folder (Windows 10) to my private server.
```
AppData/
AppData/*  // Added later as an test, but did not change anything
```
This seems to work and AppData is not updated. But sometimes, some folders are uploaded in AppData. I think this is connected to issue #725 as the folders that are uploaded are very temporary folders.

I am unsure on what information would be handy to track this issue down, so let me know how I can support.

**Comment by killing** [comment]
This should have been fixed in the current version (4.4.2).
