### ISSUE TITLE
Text illegible.

### ISSUE THREAD

**Issue by jmfranck** [haiwen/seafile-client#728]
When I try to sync a new library, the text is improperly sized to the point of being illegible (Windows 8, high resolution).

This is not a problem that I have with other applications, and I cannot resize the window in order to make the text visible.

![seafile_screenshot](https://cloud.githubusercontent.com/assets/8870541/10225377/97772c54-6830-11e5-8042-a2e178866d7b.png)

Thanks in advance!

**Comment by shoeper** [comment]
This has been fixed in the meantime.
