### ISSUE TITLE
Seafile client disappears on OS-X 10.11 (El Capitan) 

### ISSUE THREAD

**Issue by guillaumevincent** [haiwen/seafile-client#730]
Hi,
seafile client disappears on OS-X 10.11 (El Capitan).
I remove icon from the dock (seafile option). Seafile is running but no icon in the top bar. 
I can't launch seafile anymore.

Any solution ?

**Comment by lins05** [comment]
We'll fix the El captain probelm soon, before that you can use the following command to get seafile applet back on your dock:

Open your terminal, and:

- First close your seafile client by `pkill -f seafile-applet seaf-daemon ccnet` (or kill them in activity monitor)
- Then disable the "hide docker icon behavior" by:
```sh
defaults write ~/Library/Preferences/com.seafile.Seafile\ Client.plist Behavior.hideDockIcon -bool FALSE
```
- Finally launch seafile client now, you should see the dock icon again.

**Comment by guillaumevincent** [comment]
@lins05 thank you it works

**Comment by lins05** [comment]
I upgraded my macbook to 10.11 earlier today but it seems to be working fine. 

<img width="443" alt="screen shot 2015-10-09 at 18 18 04" src="https://cloud.githubusercontent.com/assets/717363/10391549/2ebf7788-6eb2-11e5-9e10-631f9f7d91c1.png">

**Comment by stenskjaer** [comment]
Which version of the client do you use? It still doesn't work on my Macbook Air (2010) with the most recent client (downloaded just today).
