### ISSUE TITLE
seafile client skips seafile-ignore.txt entries

### ISSUE THREAD

**Issue by chuegel** [haiwen/seafile-client#732]
Using latest 4.3.4 Linux Client and 4.3.2 Linux Server
Based on this information (https://github.com/haiwen/seafile-client/issues/723) I have moved the CCNET_CONF_DIR outside of my home folder so that I´m able to sync it. This works well, but ignore entries in seafile-ignore.txt are skipped. 
My ignore.txt looks like this:
`./config/teamviewer10/*`
Steps to reproduce:
1. Change the `CCNET_CONF_DIR` location (https://github.com/haiwen/seafile-client/issues/723)
2. Edit seafile.ini to move seafile-data outside your home directory
3. Under `/home/<user>/` create a seafile-ignore.txt file and ignore some hidden directories
4. Restart SF Client, add home dir to a new library and check logs

**Comment by huegelc** [comment]
OK, managed to reproduce it: if a directory is excluded with a wildcard like
` ./test/subfolder* ` 
the folder doesnt get synced. But as soon as I create a symbolic link in that directory the sync starts.

So, why aren´ t symbolic links not excluded when using wildcards like *
