### ISSUE TITLE
Explorer extension bugs

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-client#735]
As we can see in this image the arrow to the right is missing. I think this confuses many users because one cannot know that there is a sub menu.
![seafile bug](https://cloud.githubusercontent.com/assets/5340585/10558907/1bd6546c-74e2-11e5-9b65-fdca512009ed.png)

Furthermore when getting a share link or an internal share link the window containing the link is opened in the background. I think it should come to the front.

I'm using windows 10. At least the missing arrow bug is also there on windows 7 and 8 and 8.1.

**Comment by liayn** [comment]
On current Windows 10 there is no Explorer Extension visible at all anymore.

I checked the registry, it seems to be registered correctly, but for some reason it is not shown at all.

**Comment by shoeper** [comment]
It is shown here.

**Comment by liayn** [comment]
Ok, I just realized that my overlay icons are missing as well, which are handled via the same dll file.
(I also checked that those icons are among the first icon handlers in the registry - the dumb windows 15 limit)
Seems like the dll does not work correctly.

**Comment by shoeper** [comment]
Have you restarted your device since upgrading the client? I had the issue that the icons were missing till next restart.

**Comment by liayn** [comment]
Of course I did. Besides that restarting explorer.exe via taskmgr is usually enough to reload the registry entries.

**Comment by liayn** [comment]
Still no content menu entry for me :-(
(Client version 5.0.7)

**Comment by liayn** [comment]
Client version 5.1.0, same issue.

Anyone a hint how to debug that? Write log messages? Whatever?

**Comment by liayn** [comment]
Found something in the logs:
```
[16/04/29 17:16:46] D:/dev/pkg/seafpkg/build/seafile-msi-build/seafile-client-5.0.7/extensions/ext-utils.cpp(line 183) checkLastError: connection broken with error: Die Pipe wird gerade geschlossen. (Pipe is being closed currently)


[16/04/29 17:16:46] D:/dev/pkg/seafpkg/build/seafile-msi-build/seafile-client-5.0.7/extensions/applet-connection.cpp(line 145) writeRequest: failed to send command: Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist. (A file can't be created, if already existing)
```

**Comment by shoeper** [comment]
The first issue has been solved on Windows 10 in 5.1.2.

This once still exists

>Furthermore when getting a share link or an internal share link the window containing the link is opened in the background. I think it should come to the front.

**Comment by shoeper** [comment]
I currently cannot confirm as I have no windows machine available but am pretty sure that the internal share link bug is still existent. At least I've had it just recently.

**Comment by liayn** [comment]
I can confirm that the context menu is not shown at all... still.
Windows 10 64bit all updates installed.

**Comment by liayn** [comment]
New update: I set up a new laptop and the context menu was working... until I set OneDrive into action.
So the situation with the old latop is back. Seafile, DropBox and OneDrive together make the seafile context menu items vanish. As well as the overlay icons in explorer.

**Comment by liayn** [comment]
This issue is gone for a long time now. So something has been fixed. IMO this can be closed.
