### ISSUE TITLE
Windows Client UI Issue (Minor)

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-client#736]
Able to replicate: Yes

Requirements:

Windows Seafile Client 4.3.*+ (confirmed in these clients)
Multiple Accounts configures.
Windows 7 (Confirmed)
Steps to reproduce

Click the icon to view your accounts.
Load the account by clicking on the account(x@x(server) you wish to load (not the Choose button)
Outcome

The submenu of the selected account will remain, causing you to click Choose should you wish to remove it from your screen.

Reported by r007ed @ https://forum.seafile-server.org/t/windows-client-ui-issue-minor/3099?u=shoeper
I can confirm this bug as well using Windows 10.

**Comment by liayn** [comment]
Related to #746?

**Comment by shoeper** [comment]
yes it is the same issue.

**Comment by liayn** [comment]
Then why not closing it as duplicate?

**Comment by shoeper** [comment]
Because I've reported the issue first.
