### ISSUE TITLE
Fingerprint is missing in SSL/TLS certificate warning dialog

### ISSUE THREAD

**Issue by eriktews** [haiwen/seafile-client#747]
I'm using Seafile 4.3.4 on Debian Linux with LANG=de. One of the Seafile servers I am using doesn't have a correct certificate at the moment, so a warning is shown. However, this warning is supposed to include a fingerprint of the server certificate or the key, but it does not. Attached is a screenshot with the issue:
![seafile](https://cloud.githubusercontent.com/assets/1436802/11242024/13f41062-8df7-11e5-9b3b-c847698b58d5.png)

**Comment by lins05** [comment]
Emm, it's suppose to display the fingerprints of both the old and the new certs in the dialog, not sure why it doesn't in on your case.

**Comment by lins05** [comment]
OK, it turns out to be a UI issue. The size of the dialog is not set correctly. Just increase the size of the dialog by dragging the right bottom corner of it and the remaining text would show.

**Comment by lins05** [comment]
Thanks for reporting. It's fixed and would be included in the next release (5.0.0).
