### ISSUE TITLE
Unable to build client -  'SEAFILE_TYPE_ENCRYPTION_INFO' was not declared in this scope

### ISSUE THREAD

**Issue by jccr** [haiwen/seafile-client#750]
I'm having issues building the client and I get the same error both on master and the 4.4.2 tag.

My build environment is Windows 10, using mysys2 and mingw32.

```
seafile-client-4.4.2/src/rpc/rpc-client.cpp:885:9: error: 'SEAFILE_TYPE_ENCRYPTION_INFO' was not declared in this scope
         SEAFILE_TYPE_ENCRYPTION_INFO,
         ^
```

It looks like this is not being declared anywhere else. I've searched through the dependencies source as well and couldn't find a reference.

**Comment by JCCR** [comment]
This is the line ref: https://github.com/haiwen/seafile-client/blob/master/src/rpc/rpc-client.cpp#L885

**Comment by Ultima1252** [comment]
This maybe due to compiling with a different version of the dependent seafile/ccnet.
Ref: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210165
