### ISSUE TITLE
Repo status should indicate explicitely when quota is reached

### ISSUE THREAD

**Issue by camillem** [haiwen/seafile-client#752]
A library shared by a user who has reached its space quota will get stuck in "waiting for sync" state in the UI. You have to read seafile.log to understand the nature of the problem. 
It would be more straightfoward to have a "no space left" status.

**Comment by lins05** [comment]
In the to-be-released seafile client 5.0.0, the quota would be dispalyed in the bottom of the main window.

**Comment by camillem** [comment]
Great, thanks !
