### ISSUE TITLE
Feature: Accessing version history from client

### ISSUE THREAD

**Issue by MarcoWue** [haiwen/seafile-client#753]
When a file or folder is right-clicked in Explorer, there should be a menu entry "Previous Versions..." in the "Seafile" group. Clicking this item should open the browser at the Seafile version history of this file.

A more advanced approach for future versions or the PRO edition could be to add a tab to the file property dialog similar to Windows VSS:
![Previous Versions Tab](http://res1.windows.microsoft.com/resbox/en/windows%207/main/1febb176-70a8-4ea2-b8f4-3cf1d98fa8e8_45.jpg)

**Comment by shoeper** [comment]
This would be awesome.

**Comment by kenayagi** [comment]
Absolutely needed. This would bring the history function to the next level!

**Comment by shoeper** [comment]
In the meantime a context menu to access the history via browser just by one click has been added.

**Comment by kenayagi** [comment]
I'm using 5.1.3 on Windows, but I still can't see that option.
What am I missing?

**Comment by shoeper** [comment]
Did you enable the explorer extension in your Seafile settings?

**Comment by freeplant** [comment]
@kenayagi You need to restart the windows explorer. Just log out and log in.

**Comment by kenayagi** [comment]
Thanks for your feedbacks guys, but I still can't see that menu item:

![seafile_context_menu](https://cloud.githubusercontent.com/assets/2090591/16980319/b5fffd24-4e65-11e6-8584-3e189762effd.jpg)

I've tried disabling and re-enabling on the settings windows, and even by fully uninstalling and re-installing.
So a suspect arise: is it available only on "PRO" version?

**Comment by shoeper** [comment]
The history link currently only appears for files.

**Comment by shoeper** [comment]
It is available by viewing the libraries history -> snapshot -> restore folder.
