### ISSUE TITLE
Share link generates HTTP links even if server is configured for HTTPS only

### ISSUE THREAD

**Issue by bagage** [haiwen/seafile-client#756]
Using the cloud filesystem manager from the desktop client, I can generate shared URL for files/folders, however there are always using http protocol while they should use https.

**Comment by shoeper** [comment]
I cannot confirm this, have you checked that you have configured your Server url with https in the client?

**Comment by bagage** [comment]
Yes my server is listening only on HTTPS so it would not work otherwise.

Did you manage to generate an HTTPS link on your side? I'm currently using 5.0.0 version.

**Comment by shoeper** [comment]
Clicking on your profile picture, hovering over your account and selection account settings you can see which url you've set for the account.

**Comment by bagage** [comment]
Yes, it is an https link.

**Comment by shoeper** [comment]
And your SERVICE_URL on server side also contains https?

**Comment by bagage** [comment]
That was the issue indeed, thanks for the hint @shoeper!
