### ISSUE TITLE
Centos 7 client memory leak

### ISSUE THREAD

**Issue by sifalios** [haiwen/seafile-client#757]
Hi I have installed the seafile client on my machine (Centos 7) and the seaf-daemon allocates 14 GB of memory from the 16 GB available

**Comment by shoeper** [comment]
This currently also discussed at https://forum.seafile-server.org/t/client-crash-out-of-memory/3468/19

**Comment by killing** [comment]
@sifalios What client are you using? Which version?

**Comment by sifalios** [comment]
Hi I am using linux client version 4.4.2

**Comment by killing** [comment]
As noted in the forum thread, we've found the memory leak. It'll be fixed in the next version.
