### ISSUE TITLE
Constant CPU usage - Windows Client 5.0.0

### ISSUE THREAD

**Issue by katnapped** [haiwen/seafile-client#758]
Hello devs,

Once in a while my Windows Seafile cloud would start to endless use the CPU and disk (at about 1MB/s).  I am not sure of the problem, but was able to fetch a log that may be useful.

I have attached the log to this post.  The original log is 27GBs, but since after the first dozens of lines its just "read pipe error" endlessly, I have truncated it.  

[log.txt](https://github.com/haiwen/seafile-client/files/67393/log.txt)

I have also tried the 4.4.2 version and the same issue occurs.  Let me know if more info is needed for getting to the bottom of this.

Thanks,
Sean

**Comment by katnapped** [comment]
Found that ccnet.log has some events matching the time stamp.  Here it is:


[ccnet.txt](https://github.com/haiwen/seafile-client/files/67394/ccnet.txt)

**Comment by shoeper** [comment]
Is in one of your libraries a file that is constantly getting changed?

**Comment by katnapped** [comment]
As far as I know, no.  They are all just excel, pictures, and word documents really.
