### ISSUE TITLE
linux client no longer automatically alerting to new versions

### ISSUE THREAD

**Issue by caniwi** [haiwen/seafile-client#764]
Since Seafile linux client 4.3.3, the client has not been notifying users that new versions of the client are available.   A tcpdump showed it was making a https call and getting a bad string informing the latest versions were 4.3.4.  A search of tags in the source revealed that no version 4.3.4 was available.  Can this get fixed please?

curl -s -i -k  https://www.seafile.com/api/client-versions/?id=<redacted>&v=linux-5.0.1
[1] 25582
<removed>:~# HTTP/1.1 200 OK
Server: nginx/1.1.19
Date: <you don't need to know>
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept, Accept-Language, Cookie
Content-Language: zh-CN
Allow: GET, HEAD, OPTIONS
Strict-Transport-Security: max-age=63072000
X-Frame-Options: DENY
X-Content-Type-Options: nosniff

{"windows": "4.3.4", "mac": "4.3.4", "linux": "4.3.4"}

**Comment by freeplant** [comment]
We have updated the latest stable version to v5. It should report now.

**Comment by caniwi** [comment]
Uhhhh... seems not to be working... the download website shows 5.0.5 as the latest linux client but ..... 

dthompson@LAP-DAT001:~/catalyst-general-puppet/modules/duplicity/manifests$ curl -s -i -k https://www.seafile.com/api/client-versions/?id=&v=linux-5.0.5
[1] 15695
dthompson@LAP-DAT001:~/catalyst-general-puppet/modules/duplicity/manifests$ 
dthompson@LAP-DAT001:~/catalyst-general-puppet/modules/duplicity/manifests$ HTTP/1.1 200 OK
Server: nginx/1.1.19
Date: Wed, 24 Feb 2016 23:42:56 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept, Accept-Language, Cookie
Content-Language: zh-CN
Allow: GET, HEAD, OPTIONS
Strict-Transport-Security: max-age=63072000
X-Frame-Options: DENY
X-Content-Type-Options: nosniff

{"windows": "5.0.4", "mac": "5.0.3", "linux": "5.0.1"}
