### ISSUE TITLE
"Repo already exists" when cancelling re-sync of library

### ISSUE THREAD

**Issue by Crazyphil** [haiwen/seafile-client#767]
It seems that the Seafile client cleans unused repo data only on exit, which prevents users from syncing a library after they cancelled a re-sync operation.

**Steps to reproduce:**
1. Right-click a library that is already synced
2. Choose "Resync this library" in context menu
3. Cancel the dialog that appears, asking for the new location of the local library copy
4. Notice that the library now is in unsynced state (showing a cloud on the right side)
5. Right-click the library again
6. Choose "Sync this library" in context menu
7. Click link "sync with an existing folder" in the appearing dialog
8. Choose the same folder where the library was synced previously
9. Click "OK"
10. The error message appears: "Failed to add download task: Repo already exists"
11. Restart the client and try again: Now, syncing the library works

**Errors logged in `applet.log`**:

```
[01/18/16 17:59:05]Fehler beim Hinzuf�� der ݢertragungsaufgabe:
Repo already exists
[01/18/16 18:05:24]Fehler beim Hinzuf�� der ݢertragungsaufgabe:
Repo already exists
[01/18/16 18:12:24]Fehler beim Hinzuf�� der ݢertragungsaufgabe:
Repo already exists
```

**Comment by kFTY** [comment]
Same issue

**Comment by freeplant** [comment]
Please try the latest version. This problem should have been fixed.
