### ISSUE TITLE
Stuck connecting to server

### ISSUE THREAD

**Issue by aramirezverbio** [haiwen/seafile-client#769]
When I try to sync a library from a desktop client, some libraries work OK, but others get stuck in `connecting server...`. I can still browse them from Seahub and from the cloud file browser. I noticed this only happens with shared libraries.
This first happened with 4.3.2 version of the server. I updated it to 5.0.4, but the problem persists. Tried with Windows & Linux clients with the same behaviour.
I also run fsck with the repair option and gc, to no avail.

**Server:** 4.3.2, updated to 5.0.4, Ubuntu 14.04 64 bit
**Clients:** 5.0.3, Windows 7 32 bit & 5.0.1, Ubuntu 14.04 64 bit

On the client side, `seafile.log` and `applet.log` don't seem to offer any info.

`ccnet.log` is full of messages like this:
> [01/20/16 11:41:06] ../common/connect-mgr.c(289): [Conn] Peer (null) (49fce31510) connected

It repeates once every 10 seconds.

On the server side, the `ccnet.log` is full of messages like these:
> [01/20/16 11:37:50] ../common/connect-mgr.c(289): [Conn] Peer David@ (9e91bade7f) connected
> [01/20/16 11:37:50] ../common/peer.c(949): [Net Error] Peer David@ (9e91bade7f) down
> [01/20/16 11:37:50] ../common/processors/keepalive2-proc.c(475): [Keepalive] Error from peer 515 peer down

They are repeated over and over for different users.
`controller.log` and `seafile.log` don't offer any info either.

**Comment by shoeper** [comment]
https://forum.seafile-server.org
