### ISSUE TITLE
Can't run seafile-applet.exe on latest Windows 10 Insider build (14251)

### ISSUE THREAD

**Issue by raleksandar** [haiwen/seafile-client#773]
I've just updated to Windows 10 1511.14251.1000 (available currently on Fast Ring) and Seafile client (5.0.4) won't start.

I get "The application was unable to start correctly (0xc0000142)." error when I try to run it.

Running it with different compatibility settings does not solve the problem. And I have also tried uninstalling seafile and reinstalling 5.0.4, then I've tried installing 5.0.3 and 4.4.0 but there was no difference, it still won't start.

I'm using this Windows build for less than a day but other than Seafile all other applications are working so I believe that it has something to do with Seafile (maybe Qt is not compatible for some reason with this build?).

**Comment by citizennn** [comment]
Same problem after upgrade to last windows version : build 14251rs1 release 160124.1059

**Comment by citizennn** [comment]
Update to Windows 10 version : 14257 and Seafile Client run fine again.

**Comment by raleksandar** [comment]
Yup, I can confirm that with build 14257 Seafile client works again!
