### ISSUE TITLE
Daemon is crashing syncing certain library

### ISSUE THREAD

**Issue by remielowik** [haiwen/seafile-client#774]
Running on windows 10 with client 5.04(server 5.04 x64 on ubuntu 14.04)
I have several libraries but only one makes the daemon crash(tested it by disabling the library which kept the daemon running until i tried to sync it again).
I've ran fsck on all libraries which showed no error.
Logs:
[applet.txt](https://github.com/haiwen/seafile-client/files/110422/applet.txt)
[ccnet.txt](https://github.com/haiwen/seafile-client/files/110421/ccnet.txt)
[seafile.txt](https://github.com/haiwen/seafile-client/files/110423/seafile.txt)

**Comment by killing** [comment]
Cloud you please also include the dump file? You can find them in the "dumps" sud-folder in the log folder.

**Comment by remielowik** [comment]
[3da58238-8a7f-4110-badd-ed901debc914.dmp.txt](https://github.com/haiwen/seafile-client/files/111067/3da58238-8a7f-4110-badd-ed901debc914.dmp.txt)
[6ca16ffb-8597-419b-a94b-bac821f7e466.dmp.txt](https://github.com/haiwen/seafile-client/files/111068/6ca16ffb-8597-419b-a94b-bac821f7e466.dmp.txt)
[77f108a6-bc84-4ba3-b9ec-eccde88f88c3.dmp.txt](https://github.com/haiwen/seafile-client/files/111066/77f108a6-bc84-4ba3-b9ec-eccde88f88c3.dmp.txt)

**Comment by killing** [comment]
I checked the dump file. It seems that there is a certain file name in that library with invalid character encoding caused the crash.

**Comment by killing** [comment]
I built a test package which will skip files with invalid character encoding. Please try whether it works.
https://app.seafile.de/f/2ccc2e94ae/?raw=1

**Comment by remielowik** [comment]
Unfortunalty it is still crashing
[applet.log.txt](https://github.com/haiwen/seafile-client/files/112202/applet.log.txt)
[ccnet.log.txt](https://github.com/haiwen/seafile-client/files/112203/ccnet.log.txt)
[seafile.log.txt](https://github.com/haiwen/seafile-client/files/112204/seafile.log.txt)
[b0e585bd-188f-4996-83eb-967d0c550285.dmp.txt](https://github.com/haiwen/seafile-client/files/112206/b0e585bd-188f-4996-83eb-967d0c550285.dmp.txt)

**Comment by killing** [comment]
I added more debug messages in the log. The link has been updated. Could you try it and share the log again?

**Comment by remielowik** [comment]
[applet.log.txt](https://github.com/haiwen/seafile-client/files/114706/applet.log.txt)
[ccnet.log.txt](https://github.com/haiwen/seafile-client/files/114705/ccnet.log.txt)
[seafile.log.txt](https://github.com/haiwen/seafile-client/files/114707/seafile.log.txt)
[83e55fb4-18e0-440a-b249-f4149f2ba7b3.dmp.txt](https://github.com/haiwen/seafile-client/files/114708/83e55fb4-18e0-440a-b249-f4149f2ba7b3.dmp.txt)

**Comment by killing** [comment]
Hi,
I found a potential bug that could cause this crash. But I'm not 100% sure. So I also added some logs to help me debug the root cause. I've updated the link. Please try and report back.

**Comment by remielowik** [comment]
Its actually working with the new link, did you change something else other then adding more logging?

**Comment by killing** [comment]
Yes I fixed the potential bug I found. It seems I was correct about it.

**Comment by killing** [comment]
Can you still give me the log messages? I'd like to confirm my theory. Thanks!
