### ISSUE TITLE
Hidpi support on linux

### ISSUE THREAD

**Issue by MichaelAquilina** [haiwen/seafile-client#775]
Hi, according to http://help.seafile.com/en/faq.html, hidpi seems to be supported on linux. I use `QT_DEVICE_PIXEL_RATIO=auto` with success to scale QT applications, but it doesnt seem to work with seafile. Setting `QT_DEVICE_PIXEL_RATION=2` also doesnt solve the problem.

Ubuntu Gnome 15.10
Seafile 5.0.1

Is there anything else I need to enable, or is this a known issue?

P.S. thank you for a great open source alternative for file syncing!

**Comment by lins05** [comment]
Hi, the faq says:

```
You need to build client against Qt 5 (5.4 or later) and set the correct environment variable before starting client.
```

The official released deb packages for seafile-client are built with Qt 4 (for older distributions like ubuntu 12.04 that has no Qt 5 in the software repository unless you add some ppa) .

**Comment by MichaelAquilina** [comment]
Just compiled it myself and I can confirm that it works. Thanks for that and sorry for not checking more thoroughly!
