### ISSUE TITLE
case conflict

### ISSUE THREAD

**Issue by Savvkin** [haiwen/seafile-client#778]
After syncing with Mac I've noticed that conflict files flooded the folder.
And also I'm unable to remove, move or do anything with them. System says that filenames are too long to do anything with them.
I'm completely stuck with those trash files.
![capture](https://cloud.githubusercontent.com/assets/740729/13070456/b7b5f6ce-d49d-11e5-8567-ba3ee7d46bf0.JPG)

**Comment by Savvkin** [comment]
I can delete those files using Far Manager, but seems like SeaFile can't delete them from other clients and all this trash start syncing back again

**Comment by killing** [comment]
There was a similar bug in some old version of Mac client. What version do you use on Mac and Windows?
You should find two files in this folder with the same name. This is the root cause of the issue. Some Mac client failed to handle UTF-8 encoding correctly. It uploaded the same file in two different UTF-8 encoding (Decomposed form and composed form).

**Comment by Savvkin** [comment]
Latest available versions are used.
The problem that SeaFile can't delete files with long names on all clients. And after deleting those bugged files, they are left untouched locally and start sync back to cloud.

**Comment by killing** [comment]
You can unsync the library from all clients first. Then remove all the duplicate files on the server.
Can you find the two files with the same name on the web interface? Can you recall how the current situation comes? Can you reproduce it reliably?

**Comment by Savvkin** [comment]
I can't unsync library, it's already 30+ clients use it.
Even if I try unsync library, clients can't delete content, because SeaFile can create long files, but can't delete it (see first screenshot)

**Comment by killing** [comment]
I believe the latest client can create and remove long paths on Windows.
Are you sure all your clients are up-to-date? Perhaps some client is still very old and cannot handle deletion of long paths.

**Comment by killing** [comment]
You can find out which client re-upload the deleted files by reviewing the history of the library.
