### ISSUE TITLE
windows client not checking for new versions

### ISSUE THREAD

**Issue by gvesna** [haiwen/seafile-client#784]
Since v5.0.4 I'm noticing that windows client does not check for new version on startup. In applet log file is only this line "[03/08/16 14:13:36]The latest version is 5.0.4". 

Can this be fixed?

**Comment by shoeper** [comment]
It checks for updates, but for some reason 5.0.4 is currently reported as being the most recent version.

**Comment by szponek** [comment]
It's happening for the same reason as in #764 
https://www.seafile.com/api/client-versions just needs a version bump.

**Comment by gvesna** [comment]
My windows client still thinks the latest version is 5.0.4 ("[05/04/17 07:40:48]The latest version is 5.0.4"), although I have installed 6.0.0 (latest version is 6.0.4)...

**Comment by lins05** [comment]
We have improved the update checking feature in seafile client (#889), and would be included in the next release.

**Comment by gvesna** [comment]
Great! Thanks for quick answer :)

**Comment by shoeper** [comment]
That still does not show an update message for older clients. Would be better if you update the most recent version for older clients as well, so that they'll show a message to update.
