### ISSUE TITLE
Dropping multiple folders into file browser does not work

### ISSUE THREAD

**Issue by tvollstaedt** [haiwen/seafile-client#789]
OS: Windows
Client version: 5.0.6
Server version: Pro 4.4.7

Dropping multiple folders from Windows explorer into seafile file browser (arbitrary library) does not work. A "sync" dialog shortly appears, but disappears immediately. Dropping multiple files works perfectly, as well as single folders. Only multiple windows folders does not work.

Steps to reproduce:
1. Open library through Seafile client with seafile file browser
2. Select multiple (2+) arbitrary windows folders
3. Drag & drop the marked folders into Seafile file browser

**Comment by freeplant** [comment]
This should have been fixed in the latest version.
