### ISSUE TITLE
Font scaling problems in Windows 10

### ISSUE THREAD

**Issue by modemuser** [haiwen/seafile-client#794]
On a laptop with a 4k display, Windows 10 and scaling set to 175% system-wide, the Seafile desktop client (v5.0.7) looks like this:

![seafile-font-scaling problem-4k-win10](https://cloud.githubusercontent.com/assets/329455/14235029/dc046d42-f9f2-11e5-8bc7-dd1d58bc164d.png)

The font is very small nearly everywhere, and in some places the line height is far too small.

I'd be happy to provide more information if needed.

**Comment by der-eismann** [comment]
I'm working on a desktop with a 4K display and 200% scaling and everything looks fine:
![asdasd](https://cloud.githubusercontent.com/assets/10406217/16351871/3708be1c-3a69-11e6-9d6c-ecf1179623f7.PNG)

Have you tried upgrading to the latest version? Or using 200% scaling?

**Comment by shoeper** [comment]
This has been fixed in 5.1.x
