### ISSUE TITLE
OSX client repeatedly errors due to purposefully unsigned SSL keys

### ISSUE THREAD

**Issue by mrcybermac** [haiwen/seafile-client#798]
Hi,

I've got an internal Seafile installation where we simply installed the SSL certs following the instructions here: http://manual.seafile.com/deploy/https_with_nginx.html

We don't have any need to sign the certificates.

Now in the OSX client when trying to sync it just says "connecting server..." and never completes.

The logs give the following message:

[05/02/16 15:31:24] http-tx-mgr.c(707): libcurl failed to GET https:///seafhttp/protocol-version: SSL peer certificate or SSH remote key was not OK.

Any ideas? The webclient is working fine once we tell the browser to ignore the unsigned SSL certificates.  But the client continuously errors.

**Comment by lins05** [comment]
You can either:

- add your server certificate to osx keychain and trust it, or
- turn on the option "do not verify server certificate during syncing " in seafile settings dialog (right click seafile tray icon menu -> settings)

**Comment by mrcybermac** [comment]
Awesome it works.  Thank you!
