### ISSUE TITLE
Is seaf-cli still in development?

### ISSUE THREAD

**Issue by xkpd3** [haiwen/seafile-client#799]
Hello,
I couldn't find a repo for the seaf-cli client. Is the command line client still in development? It hasn't seen updates for quiet some time. It's my favorite client so I wonder what its future will look like.

Best Regards,
Stefan

**Comment by shoeper** [comment]
Yes, it is. It is build from the seafile-client repo without GUI. It is just not rebuild that regulary because most changes don't effect the core but the GUI part of the client.
