### ISSUE TITLE
Cache not cleaned on logout

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-client#804]
Logging out in the client does not clean the cache (for the specific account) at `Seafile\seafile-data\file-cache`. I'd expect that unsynced files are not available when being logged out.

Seafile Client 5.1.1. Windows 10

**Comment by jeffmikels** [comment]
bump

**Comment by freeplant** [comment]
It will be fixed in the next release.

**Comment by shoeper** [comment]
According to https://manual.seafile.com/changelog/client-changelog.html this has been fixed in 6.0.6 (2017/05/08)
