### ISSUE TITLE
Download remains at 96% of 74GB library (Windows Client)

### ISSUE THREAD

**Issue by confile** [haiwen/seafile-client#808]
I use Seafile 5.1.3 on RaspberryPi. I shared a not encrypted library of 74GB between two users. One user on MAC OSX Seafile Client 5.1.1 has no problem with downloading the complete library. 
The other user on Windows 8 with Seafile Client 5.1.1 has 54 of 74 GB having downloaded. Seafile Client shows 96% constantly since days on the Windows Client without any change in the library folder size on the Windows system.

The library is not encrypted. The transmission work over https.

Seafile Windows Client is downloading at 1500 kbit/s from the Seafile Server but still since days the library folder size on the Windows system does not change.

Do you need any more information on this issue?

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile.de/.

**Comment by confile** [comment]
@shoeper This is a bug.
