### ISSUE TITLE
update copyright information for QtAwesome

### ISSUE THREAD

**Issue by unDocUMeantIt** [haiwen/seafile-client#812]
the `third_party` directory holds source code of [QtAwesome](https://github.com/gamecreature/QtAwesome). its copyright notice does not mention any kind of free license, but "all rights reserved" (see head of files). however, looking at the [original sources](https://github.com/gamecreature/QtAwesome), the package is licensed under a MIT license.

you should update the included source files. a proper attribution note in your global copyright information for seafile-client would also be a good idea.

**Comment by freeplant** [comment]
License is added. https://github.com/haiwen/seafile-client/commit/8ac63b8
