### ISSUE TITLE
Generic "Transport error" in case of daemon crash

### ISSUE THREAD

**Issue by bagage** [haiwen/seafile-client#815]
When seafile-daemon is not running (probably caused by a crash but I did not investigate this), the application becomes unusable (expected though). For instance all libraries reset to default "unsync" status and if one try to sync it again, a generic "Transport error" popup is shown.
Could it be possible either that:
1. (simplest) The message is changed to something more valuable to the user ("Check your logs for potential errors" and/or "Check that the seafile daemon is running" and/or "Check your network capabilities")
2. (nicest) An error is shown within the application when connection to the daemon is lost, alerting the user that something is going really wrong here.

An easy way to replicate this bug:
1. Start seafile normally: `seafile-applet` with daemon running
2. Abruptally kill the daemon: `pkill -9 seaf-daemon`
3. Get back to seafile and try to sync a library. You should get "transport error" popup.

**Comment by allo-** [comment]
Is there a workaround to get seafile working again? Killing all and then starting the seafile-applet doesn't seem to help here.

**Comment by bagage** [comment]
Restarting the daemon using `seaf-daemon --daemon` should fix the problem.

**Comment by allo-** [comment]
This works. But i had to resync all libraries. And shouldn't seafile-applet restart seaf-daemon, when it's started and nothing is running?
