### ISSUE TITLE
undefined symbol: seafile_encryption_info_get_type (KDE Plasma 5 // openSUSE Tumbleweed)

### ISSUE THREAD

**Issue by jaltek** [haiwen/seafile-client#817]
Hi,

I tried to create a new encrypted library by using the ```seafile-applet```. When I chose the desired folder, tick "encrypted" fill in the password and click "OK", the applet exits with the message:

```/usr/bin/seafile-applet: symbol lookup error: /usr/bin/seafile-applet: undefined symbol: seafile_encryption_info_get_type```

Version: 5.1.3
My Repo: https://build.opensuse.org/package/show/home:jaltekger/seafile-client

**Comment by dbruenig** [comment]
could you ```readelf -d /bin/seafile-applet```

**Comment by jaltek** [comment]
My bad. I've had the wrong version installed on my test machine for the test. With 5.1.3 it works flawlessly. Sorry.
