### ISSUE TITLE
Bought cloud, no idea which server to use to log in from client

### ISSUE THREAD

**Issue by quesada** [haiwen/seafile-client#818]
Hi,

Sorry about polluting the issue tracker with this (menial) request, but there was no other support channel I could find. Bought cloud, no idea which server to use to log in from client. Tried the two domains offered, they didn't like my credentials.

Since you are competing with Dropbox and they are very simple to start using, you should really consider improving the UX of 1st-time cloud users. I have a PhD and I'm getting lost :P

**Comment by freeplant** [comment]
Hi,

Do you bought the cloud account from app.seacloud.de?
