### ISSUE TITLE
endless redirect: too many levels of symbolic links in linux

### ISSUE THREAD

**Issue by linuxhenhao** [haiwen/seafile-client#819]
We all know there is symbolic link in linux file system.Considering such a situation:
Dir-A--(file-1,symbolic link to Dir-A)
The seafile will deep into dir-a and found the symbolic link to dir-A, then follow the link to goto Dir-A again,And found a link to Dir-A,then follow ....,endless loop.
Can you guys do something to avoid such a thing happening?

---
## new

I think seafile-client should check wether the symbolic link is directing to a folder that containing the  symbolic link itself, If the answer is yes, don't follow the link. For the chain of links, do it recursively as simpliest way.

Thanks for your hard and great work for giving us such a wonderful private cloud solution！！！

**Comment by kevinvalk** [comment]
Second this, when installing steam on Mac, and syncing of /Users/* folder, one gets the same problem.
