### ISSUE TITLE
Old server isn't removed when server URL is modified

### ISSUE THREAD

**Issue by GeorgeHahn** [haiwen/seafile-client#826]
Reproduction steps:
-  Log into a server
-  [external] Server changes address/IP
-  Change server address by clicking avatar and editing URL
-  Client never deletes the old URL

After this, the Seafile client shows an error - not all servers are connected. The old server is shown in the server list, and there is no way to remove it.

**Comment by Plumarh** [comment]
Hi,

Here a quick fix :

- Open regedit 
- Open HKEY_CURRENT_USER\Software\Seafile\Seafile Client\UsedServerAddresses
- Edit the "main" key and remove the unused servers.
- Exit regedit and restart seafile client.

Hope it will help,
Plumarh.
