### ISSUE TITLE
"not a valid server address" when using new gTLDs

### ISSUE THREAD

**Issue by jamal** [haiwen/seafile-client#839]
Can't use domains with new gTLDs in the Desktop client (OS X). For example, using "jamal.codes" as the server gives the following error: "jamal.codes is not a valid server address".

!["jama.codes is not a valid server address"](https://ct.yimg.com/cy/5696/30792688325_a503a1_o.png)

**Comment by lins05** [comment]
You need the http:// or https:// prefix.
