### ISSUE TITLE
seafile-client on Debian Sid

### ISSUE THREAD

**Issue by andreasspeck** [haiwen/seafile-client#840]
The Seafile Client stopped working on Debian Sid. I had a self-compiled version of seafile-client-4.x running (the packaged version did not work), but due probably to upgrades to libopenssl from 1.0.2 to 1.1 it stopped working. It seems seaf-daemon crashes and then you get the generic "transport error" on syncing (you can use the built-in file browser through).

I tried to recompile seafile-client-6.0.0 and all its dependencies, using libssl1.0-dev (for openssl1.0.2) and NOT libssl-dev (which now is for openssl1.1.x). I made the necessary adjustments to all debian/control files.

- libsearpc: does build, and installed the recompiled packages, including dev-packages.
- ccnet: does not complie
- seafile-daemon: does buld
- seafile-gui: does build

However, there is no improved performance - the same transport error as before.

**Comment by andreasspeck** [comment]
All works now, after I managed to also recompile ccnet: https://github.com/haiwen/ccnet/issues/112

On one of my boxes I had to re-sync all folders, but maybe that was because I tried to often to do so without success before.
I haven't updated my other box yet, so can't tell if it works smoothly there.

**Comment by killing** [comment]
The client now compiles on Stretch with both libssl 1.0 and 1.1 without problems.
