### ISSUE TITLE
Client delays folder renaming in explorer

### ISSUE THREAD

**Issue by liayn** [haiwen/seafile-client#841]
On windows version 6.0 causes some heavy delays to the system (explorer even freezes) when renaming folders. It does not matter whether the folder is inside the seafile storage. Any folder renaming on any path in the system is delayed. Sometimes 15 seconds and longer.
Closing the client lets the problem go away immediately.

**Comment by lins05** [comment]
When it happens, can you check what's in the logs files? especially:

- C:/Users/yourname/ccnet/logs/applet.log
- C:/Users/yourname/ccnet/logs/seafile.log
- C:/Users/yourname/seaf_ext.log

**Comment by liayn** [comment]
Neither of those log files shows anything in this regard unfortunately

**Comment by StoneGuo** [comment]
NOW I WANT TO DESIGN A ICON OVERLAY PLUGGIN.

2016-11-11 14:30 GMT+08:00 Shuai Lin <notifications@github.com>:

**Comment by liayn** [comment]
Weird thing. Today, Seafile client is not running, I seem to have similar issues.
Seems that it could be a bad mix of of explorer extensions that somehow triggers that issue and none of the products is guilty at all. I'll close this issue for the time being.
