### ISSUE TITLE
Mac Client - Window disappears forever

### ISSUE THREAD

**Issue by LeonardoGentile** [haiwen/seafile-client#843]
Seafile Client 6.0.0
OSX 10.11.6

I've set the option to launch the client at startup and to hide the main window when started. This seems to work, however things get messy when manually quitting and relaunching the client.
I've moved my folder somewhere else so before doing so I quit the application then relaunched and I had the following behaviour: 
- on opening the application window disappear and the tray icon is not created, altough from activity monitor I could see 3 process running related to seafile.
- on manually relaunching the application two things can happen 
  - nothing, forever. The main window is not created not the tray icon
  - sometimes the main window open, but it is asking again to insert my user and pass as it was the first time I am connecting
- manually quitting the processes from activity monitor not always help, meaning that sometimes the app restart as normal (most of the times asking again for user/pass and sync folder) sometimes again nothing is showed (not window, nor icon)

I could see this behaviour not only when changing the main sync folder but usually when manually quitting / relaunching the application without touching anything else.

**Comment by lqhl** [comment]
I encountered the same problem. Have you solved it?

**Comment by justinforlenza** [comment]
I am also facing the same issue, any solutions? I have cleaned out every file relating to seafile, and am unable to get it to open. I even tried editing the defaults to show the app icon in the dock, no luck

**Comment by freeplant** [comment]
@lqhl @justinforlenza Do you use OSX 10.11 too?

**Comment by lqhl** [comment]
> @lqhl @justinforlenza Do you use OSX 10.11 too?

I'm using macOS 10.14 now.

**Comment by lqhl** [comment]
@freeplant Do you know some workarounds for this issue? I've tried to delete and reinstall the app multiple times (using different versions of the app). I even deleted everything related to seafile including my data folder and some hidden directories (using `find / | grep seafile`). But it still didn't work.

**Comment by freeplant** [comment]
@lqhl I don't know the cause of the problem and don't have a solution yet.

**Comment by killing** [comment]
You may try to upgrade to OSX 10.14.1.

**Comment by lqhl** [comment]
@killing upgrading to macOS 10.14.1 fixed this problem. thanks.
