### ISSUE TITLE
Looking for seafile-client with Shibboleth Support (university single sign-on)

### ISSUE THREAD

**Issue by heis2201** [haiwen/seafile-client#845]
Hi,
I would like to use seafile-client under Fedora and installed `seafile` and `seafile-client` from the official [Fedora repos](https://admin.fedoraproject.org/pkgdb/package/rpms/seafile/).

This seems to be the "standard" version of the client. What I am looking for is a build that supports Shibboleth sign-on since that is what my server is requiring for authentication.

Couldn't find any conf file where I can enable it.

I am talking about seafile version 5.1.1 here (release 3.fc24).

Thanks

**Comment by lins05** [comment]
Seems the maintainer of the seafile client package on Fedora is missing one flags when building the package, i.e.`-DBUILD_SHIBBOLETH_SUPPORT=ON` which means to enable Shibboleth support.

http://pkgs.fedoraproject.org/cgit/rpms/seafile-client.git/tree/seafile-client.spec?id=03b2c9ec2076fc83703c510a910f543ddca30e8f#n42

You can refer him to take a look at how the debian packaging scripts use it: https://github.com/haiwen/seafile-client/blob/v6.0.0/debian/rules#L9

**Comment by heis2201** [comment]
Oh, that would explain why. Thanks a lot for the information. I passed it on to the Fedora package maintainers.

**Comment by heis2201** [comment]
and they rebuilt the fc25 package: 

https://bugzilla.redhat.com/show_bug.cgi?id=1395809

https://bodhi.fedoraproject.org/updates/FEDORA-2016-5f73f9d65f

**Comment by killing** [comment]
@heis2201 Thanks. Can this issue be closed?

**Comment by heis2201** [comment]
Sure, let's go ahead and close it. Package for Fedora has been rebuild by maintainers with correct flags. All working well now.
