### ISSUE TITLE
how to build seafile-client on mac for windows

### ISSUE THREAD

**Issue by carol881221** [haiwen/seafile-client#848]
I compile the seafile-client sourse only generated seafile-applet file which only can be  installed on os system. Who can tell me how to build seafile-client on mac for windows.

**Comment by shoeper** [comment]
Duplicate of https://github.com/haiwen/seafile-client/issues/810

**Comment by wangwei19900725** [comment]
> I compile the seafile-client sourse only generated seafile-applet file which only can be installed on os system. Who can tell me how to build seafile-client on mac for windows.

I need make a dmg package to publish in stores,but I cannnot find the right way,can you give some tips.
