### ISSUE TITLE
automatic locking for Microsoft Access

### ISSUE THREAD

**Issue by samsk** [haiwen/seafile-client#856]
Microsoft Access databases are stored in .mdb files. When user opens this database, a .ldb file is created with same name as original .mdb file.
Same ways as in #763 seafile can use presence of this .ldb file to automatically lock given file.

.LDB file:
https://support.microsoft.com/en-us/kb/966848

**Comment by dofl** [comment]
Yes, this would be a very welcome addition to prevent database corruption

**Comment by freeplant** [comment]
We don't have such a plan.
