### ISSUE TITLE
Seafile Client on BSD

### ISSUE THREAD

**Issue by antares2001** [haiwen/seafile-client#86]
Hello,

we're considering to install BSD on several machines, since the features provided by ZFS are very appealing (the same for server solutions, i.e. de-duplication, dynamic hard disk pool resize, ...). Is it there a client available for BSD or is it possible to compile the client without major issues on BSD?

**Comment by Chilledheart** [comment]
There is a working freebsd port recipe [`net-mgmt/seafile-gui`](https://github.com/freebsd/freebsd-ports/blob/c4beff3b219b0e8a25ca3163723ec4f33852b1b1/net-mgmt/seafile-gui/Makefile). Maybe that is what you want.

Closing it.
