### ISSUE TITLE
Bad response: 102 processor is dead error

### ISSUE THREAD

**Issue by mrjovanovic** [haiwen/seafile-client#861]
Trying to sync a fairly large library (7GB) of mostly image files. When I use either seafile-gui or seaf-cli to sync, it uploads some files, but then gives: 
```
$ tail -f applet.log
[02/03/2017 08:49:00 PM][Sea RPC] Bad response: 102 processor is dead.
... (repeating)

```
Other libraries sync fine. 

Using Seafile client 6.0, on Debian Stretch. Server running on Raspberry Pi (worked fine before upgrade to stretch).

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.

**Comment by mrjovanovic** [comment]
For anyone else looking for this, others have had the issue on the forums as well as AUR:

https://forum.seafile.com/t/seafile-client-on-ubuntu-transport-error/4749

https://aur.archlinux.org/packages/seafile/?comments=all (see comment by Captain Rage)

Might be related to openssl, upgrade to 6.0.6 solved the issue.
