### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by anexit1** [haiwen/seafile-client#863]
Getting the below, any insight?

seafile-client-master/src/rpc/rpc-client.cpp:1046:9: error: use of undeclared identifier 'SEAFILE_TYPE_FILE_SYNC_ERROR'
        SEAFILE_TYPE_FILE_SYNC_ERROR,
         ^

**Comment by killing** [comment]
Make sure you have installed the libseafile library from the seafile source code (under the lib directory).

**Comment by DanSman** [comment]
I got the same issue.
I don't understand your post @kiling 
How can i install the libseafile library on my raspberry? Is it even possible to compile the client on my raspberry with already running the seafile server?

**Comment by saljut7** [comment]
Same error for me: 

```
$ make
[  4%] Built target utils
[  4%] Building CXX object CMakeFiles/seafile-applet.dir/src/rpc/rpc-client.cpp.o
/mnt/ext-data/lab/seafile/seafile-client-rpi/6.0.7/seafile-client-6.0.7/src/rpc/rpc-client.cpp: In member function ‘bool SeafileRpcClient::getSyncErrors(std::vector<SyncError>*, int, int)’:
/mnt/ext-data/lab/seafile/seafile-client-rpi/6.0.7/seafile-client-6.0.7/src/rpc/rpc-client.cpp:1046:9: error: ‘SEAFILE_TYPE_FILE_SYNC_ERROR’ was not declared in this scope
         SEAFILE_TYPE_FILE_SYNC_ERROR,
         ^
CMakeFiles/seafile-applet.dir/build.make:1670: recipe for target 'CMakeFiles/seafile-applet.dir/src/rpc/rpc-client.cpp.o' failed
make[2]: *** [CMakeFiles/seafile-applet.dir/src/rpc/rpc-client.cpp.o] Error 1
CMakeFiles/Makefile2:835: recipe for target 'CMakeFiles/seafile-applet.dir/all' failed
make[1]: *** [CMakeFiles/seafile-applet.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

Any updates here?

**Comment by killing** [comment]
I mean you should run `make install` in the seafile source code directory. Seafile-client project relies on some libraries provided by Seafile project.

**Comment by saljut7** [comment]
@killing thx for your help. Assuming you mean a `make install` under `seafile-${version}/` according to [manual](https://manual.seafile.com/build_seafile/linux.html). If so would be a `dpkg -i install seafile-${version}.deb` (which I compiled via `checkinstall` in `seafile-${version}/`) the same? 
If so I got same error in `seafile-client-${version}` with `make`:

```
$ make
[  4%] Built target utils
[  4%] Building CXX object CMakeFiles/seafile-applet.dir/src/rpc/rpc-client.cpp.o
/mnt/BIGRED/lab/seafile/seafile-client-rpi/6.0.7/seafile-client-6.0.7/src/rpc/rpc-client.cpp: In member function ‘bool SeafileRpcClient::getSyncErrors(std::vector<SyncError>*, int, int)’:
/mnt/BIGRED/lab/seafile/seafile-client-rpi/6.0.7/seafile-client-6.0.7/src/rpc/rpc-client.cpp:1046:9: error: ‘SEAFILE_TYPE_FILE_SYNC_ERROR’ was not declared in this scope
         SEAFILE_TYPE_FILE_SYNC_ERROR,
         ^
CMakeFiles/seafile-applet.dir/build.make:1670: recipe for target 'CMakeFiles/seafile-applet.dir/src/rpc/rpc-client.cpp.o' failed
make[2]: *** [CMakeFiles/seafile-applet.dir/src/rpc/rpc-client.cpp.o] Error 1
CMakeFiles/Makefile2:835: recipe for target 'CMakeFiles/seafile-applet.dir/all' failed
make[1]: *** [CMakeFiles/seafile-applet.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

So is a `make install` under `seafile-${version}/` really mandatory?

**Comment by killing** [comment]
@saljut7 Actually I don't totally understand how you compile the packages. Do you want to compile debian packages? Then there is a libseafile-dev package built from the 'seafile' project, which you need to install.

**Comment by saljut7** [comment]
@killing thanks for your reply:

> Actually I don't totally understand how you compile the packages. Do you want to compile debian packages?

I follow completely https://manual.seafile.com/build_seafile/linux.html except using `checkinstall` whenever there is a `make install`. 
First reason for this is that I don't want to install something passing over the package manager on my system. Second reason is: yes, I want to compile Debian packages, don't you [remember](https://forum.seafile.com/t/install-seafile-cli-client-on-raspberry-pi/778/8)? ;) 

> Then there is a libseafile-dev package built from the 'seafile' project, which you need to install.

I could only find something called `libseafile-dev.install`:

```
$ find /mnt/ext-data/lab/seafile/seafile-client-rpi/6.0.7/ -name libseafile-dev*
/mnt/ext-data/lab/seafile/seafile-client-rpi/6.0.7/seafile-6.0.7/debian/libseafile-dev.install
```

Beside this something called `libseafile-dev` is not mentioned in https://manual.seafile.com/build_seafile/linux.html - what did I miss?
