### ISSUE TITLE
Confidence about data integrity 

### ISSUE THREAD

**Issue by Kwadz** [haiwen/seafile-client#864]
To be confident with the data integrity:
- is there an integrity checking for the transport?
- is there a checking like a comparison between the tree of the server and the client (e.g number of files for every directory, size, etc.)?

**Comment by killing** [comment]
- We don't do extra integrity checking on transport except for the default crc based checksum provided by TCP
- There is no need to do extra comparison between the client and the server. The syncing algorithm is already designed to replicate the folder structure between the client and server.

**Comment by Kwadz** [comment]
> We don't do extra integrity checking on transport except for the default crc based checksum provided by TCP

So, that could be improved.

> There is no need to do extra comparison between the client and the server. The syncing algorithm is already designed to replicate the folder structure between the client and server.

Would you be able to outline the way how the folder structure is replicated?

**Comment by shoeper** [comment]
https://manual.seafile.com/develop/sync_algorithm.html
