### ISSUE TITLE
Trashed file looses history.

### ISSUE THREAD

**Issue by deragon** [haiwen/seafile-client#878]
When a file is deleted, it is moved to the trash.  After restoring it,
all history has been lost.

Seafile server 6.0.8 with seafile-cli 6.0.4-1185~ubuntu16.04.1.

During my test, the latest version was retrieved.  However, I had another
(real, useful) file which I believe not the latest version was retrieved.  If there are any means to try to retrieve the latest version, please provide instructions.  I, like many, use Seafile as a backup system.  History preservation is primordial in this context.

**Comment by freeplant** [comment]
You can find the old version in the history->view snapshot.

**Comment by deragon** [comment]
Ok, great!  You help me restore the proper version.  Thank you so much.

However, this is not intuitive (thus the reason I created this issue). The full history should show up in the file's history, as if it was never deleted.  Can you please reopen this ticket?  Surely you must understand the user friendliness this would bring to Seafile.

For reference, for other readers, what freeplant meant is that one has to go the library's snapshot history, as described in [Library History and Snapshots](https://www.seafile.com/en/help/snapshot/)

**Comment by deragon** [comment]
Should I open a new issue since this one was closed?

**Comment by freeplant** [comment]
Yes, please open a new issue.
