### ISSUE TITLE
osX build fails because of openssl dependency

### ISSUE THREAD

**Issue by halfsoft** [haiwen/seafile-client#882]
in Mac OSX 10.10 apple removed the openssl headers. Now on a new install of OSX, with libraries (libevent, openssl, gobject...) installed using Homebrew i am not able to build the project as it complains that it cannot find the headers.

> Undefined symbols for architecture x86_64:
>   "_BIO_free", referenced from:
>       _load_certs in http-tx-mgr.o
>   "_BIO_new", referenced from:
>       _load_certs in http-tx-mgr.o
>   "_BIO_s_mem", referenced from:
>       _load_certs in http-tx-mgr.o
>   "_BIO_write", referenced from:
>       _load_certs in http-tx-mgr.o
>   "_CRYPTO_num_locks", referenced from:
>       _seafile_curl_init in curl-init.o
>       _seafile_curl_deinit in curl-init.o...

How do you setup your build environment?

**Comment by killing** [comment]
The seafile-client project can only compile with openssl 1.0. We will add compatibility to openssl 1.1 later.
