### ISSUE TITLE
Linux: Seadrive only client available in stretch repo

### ISSUE THREAD

**Issue by mrjovanovic** [haiwen/seafile-client#883]
Hey folks, so a SeaDrive linux client is the only one available in my stretch bintray repo. 

Expected behavior: installs ccnet seafile-gui seafile-deamon and seafile-cli

Actual behavior: 

```
grep Package /var/lib/apt/lists/dl.bintray.com_seafile-org_deb_dists_stretch_main_binary-amd64_Packages 
Package: libsearpc-dbg
Package: libsearpc-dbg
Package: libsearpc-dev
Package: libsearpc-dev
Package: libsearpc1
Package: libsearpc1
Package: seadrive-daemon
Package: seadrive-daemon-dbg
Package: seadrive-gui
Package: seadrive-gui-dbg

```
Am I doing something wrong?

I have no idea how to use this. Is this a new client? Is the old one deprecated? If [these](https://www.seafile.com/en/help/drive_client/) are the only features available in the future, we'll have to move away from Seafile. We use it as a backup and file syncing solution, and prefer to have all the files available offline at all times. Likewise, without the ability to sync symlinked folders, see sync status, set particular libraries to be synced (all features on the old client) it's quite useless for us, unfortunately.

**Comment by shoeper** [comment]
Yes, the linked one is the drive client, but is has no influence on the "normal" client. The Drive Client can be used in addition to the normal Seafile client, but there is no need to use it and the "normal" Seafile client is supported and developed.

**Comment by mrjovanovic** [comment]
Thank you for the response. I am so happy to hear that the Seafile client is support. However, my issue is that the Seafile client packages are not in the stretch bintray repository (see command above). The client cannot be installed or updated.

**Comment by shoeper** [comment]
Afaik it is in the Debian repository. Search using apt-cache.

**Comment by mrjovanovic** [comment]
In sid, [yes](https://packages.debian.org/search?keywords=seafile&searchon=names&suite=all&section=all&sourceid=mozilla-search). Doesn't appear to be in [stretch](https://packages.debian.org/search?suite=stretch&searchon=names&keywords=seafile).

If you're talking about bintray, it isn't there for me. [Look for yourself](http://dl.bintray.com/seafile-org/deb/stretch/pool/main/s/).

**Comment by shoeper** [comment]
Ok, your right. There currently is no stretch repository.

@freeplant

**Comment by mrjovanovic** [comment]
Thanks for the response! FYI, the *.deb files from the Ubuntu PPA work fine on stretch.

**Comment by killing** [comment]
Debian repository for Stretch is not yet available. We'll add it later. But you can already use the client packages from official Debian unstable branch. It's now maintained by Debian developers.

**Comment by shoeper** [comment]
How do you expect someone to do that? It's really a pain to do something like that.

**Comment by mrjovanovic** [comment]
@killing Closing the bug doesn't make sense at all. The bug says that the Seafile client is missing from the stretch repo. That is still not resolved. A user that follows installation instructions on the website would encounter an error.

I apologize if this is inappropriate, but it's quite frustrating that this issue isn't being taken seriously. The existing .deb files for 6.0.4 work fine in jessie. It's just about uploading them to bintray. It's only a few minutes of work.

As for using files from sid - that is [not something that one is supposed to do](https://wiki.debian.org/DontBreakDebian).

**Comment by killing** [comment]
Actually you can use testing and unstable sources if you set them up properly, without harming your system. See http://www.binarytides.com/enable-testing-repo-debian/

Okay, I'll keep this open.

**Comment by mrjovanovic** [comment]
Thank you for keeping it open! I think it's really about putting the packages on the bintray repo. As I said, existing 6.0.4 ones from the Ubuntu PPA work perfectly. :)

**Comment by mrjovanovic** [comment]
As per #936, seafile is now available in stretch-backports. Great news!
