### ISSUE TITLE
Compile issue with openssl-1.1

### ISSUE THREAD

**Issue by eolianoe** [haiwen/seafile-client#899]
[ccnet-server](https://github.com/haiwen/ccnet-server), [ccnet](https://github.com/haiwen/ccnet) and [seafile](https://github.com/haiwen/seafile) compile fine with openssl-1.1 using the master branch. Would it possible that the next release of the other seafile packages also compile fine with openssl-1.1?

**Comment by david-geiger** [comment]
Hi,

I have the same issue here on Mageia Cauldron with openssl 1.1.0f:

[seafile-client-build-log.txt](https://github.com/haiwen/seafile-client/files/1218751/seafile-client-build-log.txt)

**Comment by freeplant** [comment]
This should have been fixed.
