### ISSUE TITLE
Client does not show synchronized subfolders in it's list of synchronized libraries

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-client#903]
... thus it is neither possible to view the sync state nor to unsync them without using a trick (renaming the folder)

**Comment by killing** [comment]
In my client, the subfolders are shown. Anything special in your case?

**Comment by shoeper** [comment]
No, nothing special.

Went to a library, synchronized a subfolder. Looked at the list of synchronized libraries and it does not contain the subfolder, thus I cannot unsync it (renaming the folder locally is the only option)

**Comment by freeplant** [comment]
It is fixed in version 6.1.0.

**Comment by shoeper** [comment]
Thanks

**Comment by shoeper** [comment]
This has not been fixed. Synchronized subfolders are still not shown in the libraries list of the device.
