### ISSUE TITLE
Seafile Client show randomly host resolution misfunction (macOS)

### ISSUE THREAD

**Issue by marioli** [haiwen/seafile-client#906]
Hi seafile team,

I´m using Seafile on my Server at home and the Client on my Mac sometimes shows me a red exclamation mark within the notification icon.

The applet.log logs those messages if this occurres:

> [05/14/17 21:59:08][network detector] got a network failure
> [05/14/17 21:59:08][api] network error for https://mbox.marioli.de/api2/account/info/: Host mbox.marioli.de not found
> 
> [05/14/17 21:59:23][network detector] resetting the qt network access manager
> [05/14/17 23:02:16][network detector] got a network failure
> [05/14/17 23:02:16][api] network error for https://mbox.marioli.de/api2/account/info/: Host mbox.marioli.de not found
> [05/14/17 23:02:46][network detector] resetting the qt network access manager

However the network is up and working (the HTTP client is working during this time, "dig mbox.marioli.de" is showing the result I expect).

Restarting the Client makes it work immediately again. Any idea?

**Comment by killing** [comment]
This is a known issue and we're working on it already.

**Comment by freeplant** [comment]
It should have been fixed in version 6.0.7.
