### ISSUE TITLE
Start ccnet and seaf-daemon without conhost.exe on Windows

### ISSUE THREAD

**Issue by sinni800** [haiwen/seafile-client#922]
Hi,

conhost.exe is a process that is automatically attached to console applications on Windows to provide stdout and stdin to those applications. In this case these are unneeded because the user never sees those console host windows. Conhost will needlessly use RAM in this case. 

Microsoft has a DETACHED_PROCESS flag as per here: 

https://msdn.microsoft.com/en-us/library/windows/desktop/ms684863(v=vs.85).aspx

QProcess has a way to specify Windows-specific arguments for CreateProcess() (which is used by QProcess) as shown here: http://doc.qt.io/qt-5/qprocess.html#notes-for-windows-users

This is not a defect, it is just a suggestion that would make the program use less memory on Windows PCs

**Comment by ngugcx** [comment]
This feature was added in version 5.7, is there a workaround for 5.6? Thanks!

**Comment by sinni800** [comment]
You would have to port the change yourself. It's not really a defect though, it's like 20 Megabytes of RAM more.

**Comment by ngugcx** [comment]
This feature uses std::function, but 5.6 does not enable use of C++ 11 in modules.
There is no straightforward way to backport it.
