### ISSUE TITLE
SSL Certificate not trusted on wildcard certificate

### ISSUE THREAD

**Issue by ruffy91** [haiwen/seafile-client#93]
I get an error that the certificate is not trusted when I try to add my server.
My server is using a wildcard certificate (*.domain.com) and seafile runs under seafile.domain.com

**Comment by dionysius** [comment]
I got this error message too with my wildcard certificate. After some research my system seems not to be wrong: http://serverfault.com/questions/671616/apache-ssl-unable-to-get-local-issuer-certificate

But reopening seafile-applet did not ask me again. So I dunno how I should reproduce it again to provide a screenshot.

**Comment by shoeper** [comment]
I use seafile with a chained wildcard certificated and have no issues. Don't think there is an error in the software.

In most cases people just do not include chain certificates.
