### ISSUE TITLE
Can't sync with folders outside of the seafile folder

### ISSUE THREAD

**Issue by thevik** [haiwen/seafile-client#939]
in the webGUI there is the option:

DISABLE_SYNC_WITH_ANY_FOLDER
If turn on, the desktop clients will not be able to sync a folder outside of the default Seafile folder.

which is unchecked, but client keeps reverting any folder I set outside of /home/seafile

**Comment by shoeper** [comment]
Do I understand you correctly? You first enabled the feature then disabled it but it is still active?

Have you restarted the client since?

**Comment by thevik** [comment]
no, it was unchecked by default, and is still remains unchecked.

**Comment by shoeper** [comment]
Which server version are you using?

Have you configured multiple servers in the client?

**Comment by thevik** [comment]
theres only a single server in the client, and the version of the server is 5.1.2
