### ISSUE TITLE
Client 'forgets' synced folders

### ISSUE THREAD

**Issue by cocowalla** [haiwen/seafile-client#941]
Rather than syncing an entire library, I'm using 6.0.7 to sync specific folders. After choosing the folder to sync, it syncs OK, and I can see the folder displayed in the client.

After restarting the Seafile client, the synced folder is no longer visible, and files are no longer synced in the folder.

**Comment by haidian6672** [comment]
Would you like to check key words "synced subfolder" or "synced_sub_folder" in log file?
Or check "SyncedSubfolder" table in accounts.db file.

**Comment by cocowalla** [comment]
No mention of `synced subfolder` or `synced_sub_folder` in `applet.log`, `ccnet.log` or `seafile.log`.

The `SyncedSubfolder` table in `accounts.db` is empty.

I did some more digging, and all the subfolders in `seafile-data\storage` are also empy - looks like all traces of them are gone!

**Comment by haidian6672** [comment]
Is it a similar problem?
https://github.com/haiwen/seafile-client/issues/851#issuecomment-314094664

**Comment by cocowalla** [comment]
@haidian6672 I think so, yes. Has the root cause been found?

**Comment by haidian6672** [comment]
Due to `on delete cascade` has been setted in `SyncedSubfolder` table,
replace sql statement into `accounts` table will delete synced sub folder in `SyncedSubfolder` table.
[https://github.com/haiwen/seafile-client/blob/master/src/repo-service.cpp#L166]

**Comment by cocowalla** [comment]
@haidian6672 great, will a fix be in 6.0.8, and do you know when it's expected?

**Comment by freeplant** [comment]
It is fixed in version 6.1.0.
