### ISSUE TITLE
Change of the profile picture is not shown in the client.

### ISSUE THREAD

**Issue by JulianMH** [haiwen/seafile-client#943]
Observed under Mac OS with client version 6.0.7 and server version 6.0.9.
Change of the profile picture is not shown in the client.

Steps to Reproduce:
- login seafile desktop client into an account with any custom profile picture set.
- change the profile picture on the seafile web interface to a new profile picture.
- Expectation: The client software should show the new profile picture, at the very least after a restart.

**Comment by freeplant** [comment]
It is fixed in version 6.1.0.
