### ISSUE TITLE
Couldn't Resolve Hostname - FreeBSD Client

### ISSUE THREAD

**Issue by andrew2005** [haiwen/seafile-client#947]
Hi,

I'm not sure how much you're supporting the FreeBSD client - I know in your manual it says under construction. Please close ticket if you're not supporting.

I have running the server in a FreeBSD Jail successfully [using the package](https://www.freshports.org/net-mgmt/seafile-server/). It's actually running on FreeNAS.

I have recently set up the client in a separate FreeBSD Jail [using it's package](https://www.freshports.org/net-mgmt/seafile-client/). It installed fine and did the initial syncs perfectly. I logged in the next day and noticed two errors. First was 100% CPU usage with nothing in the logs. Later on in the day I noticed this new error:

    [07/11/17 16:55:29] http-tx-mgr.c(787): libcurl failed to GET https://seafile.XXX.com.au:8000/seafhttp/protocol-version: Couldn't resolve host name.

All my other clients are working fine. In the client I can run curl manually and it works:

    root@seafile_client:/ # curl https://seafile.XXX.com.au:8000/seafhttp/protocol-version
    {"version": 1}   

    root@seafile_client:/ # curl --version
    curl 7.54.1 (amd64-portbld-freebsd11.0) libcurl/7.54.1 OpenSSL/1.0.2j zlib/1.2.8 nghttp2/1.23.1
    Release-Date: 2017-06-14
    Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp 
    Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy

I deleted the client configuration directories and set up the client from scratch. Again worked fine for a while and then the same thing happened again. It seems to come and go without any pattern.

I'll worry about the CPU usage when/if I get this resolved.

Other version info:

    root@seafile_client:/ # uname -a
    FreeBSD seafile_client 11.0-STABLE FreeBSD 11.0-STABLE #0 r313908+f4b711d1be8(freenas/11.0-
    stable): Tue Jun 13 19:17:29 UTC 2017     root@gauntlet:/freenas-11-releng/freenas/_BE/objs/freenas-
    11-releng/freenas/_BE/os/sys/FreeNAS.amd64  amd64

    root@seafile_client:/ # pkg info | grep seafile
    seafile-client-6.0.7           Open Source Cloud Storage (Client)

Thanks,

Andrew

**Comment by freedeaths** [comment]
Hi Andrew, I met some problems while install seafile-server. Could you give me some advice?

**Comment by melbruki** [comment]
I have the exact same issue running hte same setup as andrew has this been resolved??
