### ISSUE TITLE
Excessive notifications

### ISSUE THREAD

**Issue by iliis** [haiwen/seafile-client#948]
I think this screenshot says it all:
![seafile_bug](https://user-images.githubusercontent.com/933300/28110030-56adfda8-66f1-11e7-9c09-813e0597774c.jpg)

I synced a new PC which had an older version of my files and it created a bunch of conflicts. Each of which created a notification, spamming my screen ;)

**Comment by shoeper** [comment]
You can disable notifications in the settings. Most operating systems don't spam the whole display in case of a larger amount of notifications.

**Comment by iliis** [comment]
Well, mine appearantly doesn't :( And completely disabling notifications seems a bit severe. How about a single "2452 conflicts detected" message?

**Comment by shoeper** [comment]
Feel free to submit a PR.
