### ISSUE TITLE
It is not possible to build a docker image on a seadrive drive

### ISSUE THREAD

**Issue by maxboehm** [haiwen/seafile-client#954]
I'd like to store the company's Dockerfiles on a drive mounted by seadrive.

But trying to build the image results in the following error:
PS S:\Meine Bibliothek\Docker> docker build .
time="2017-07-21T08:44:15+02:00" level=error msg="Tar: Can't stat file \\\\?\\S:\\Meine Bibliothek\\Docker to tar: Readdir \\\\?\\S:\\Meine Bibliothek\\Docker: Das System kann den angegebenen Pfad nicht finden."
Sending build context to Docker daemon  1.024kB
Error response from daemon: Cannot locate specified Dockerfile: Dockerfile

"Das System kann den angegebenen Pfad nicht finden" is the german phrase for "System can not find the given path"

How to replicate the error: (Preliminary: Install docker)
a) Create empty dir within you seadrive drive
b) Create a new file called "Dockerfile"
c) Insert "FROM alpine:latest" into the Dockerfile (so at least something should happen)
d) Run "docker build -t test ." within this directory

**Comment by shoeper** [comment]
This is seafile-client. See https://github.com/haiwen/seadrive-gui
