### ISSUE TITLE
error "p invalid" when trying to restore older versions from MacOS client

### ISSUE THREAD

**Issue by querteru** [haiwen/seafile-client#964]
I'm using Seafile Server Pro 6.1.4, MacOS Sierra 10.12.6, and Seafile Client 6.0.7. I'm also using the Windows Seafile Client with the same Server. I'm trying to view older version of a file and restore it from a Mac in the following steps:

1. open finder
2. right-click a file
3. from the seafile options, select "View file history"
4. Safari opens and shows the history of the file
5. click "restore" ("Wiederherstellen") for an older version
6. the error "p invalid" is shown at the top of the site (overlaid box, red ground)
7. I also recognized that on the history page (step 4) the path to the file is displayed incorrectly: The first folder in the path, immediately following the name of the library, is missing the first character. I.e., assume that the path is "Library>Top-Folder>Sub-Folder>File.txt". In this case, the path displayed in step 4 would be "Library>op-Folder>Sub-Folder>File.txt". 

When I navigate to the file in the web client, starting from the library, the path is displayed correctly and restoring works. The problem does also **not** occur with the Windows client. The problem only occurs if I open the history page directly from within the Mac Desktop client.

**Comment by querteru** [comment]
... still there with client 6.10 and server Pro 6.1.8

**Comment by freeplant** [comment]
It should have been fixed in client version 6.1.1
