### ISSUE TITLE
MacOS Client thinks it's not in Applications folder

### ISSUE THREAD

**Issue by Ardakilic** [haiwen/seafile-client#970]
Hello,

I've stumbled upon a simple issue in MacOS client.

When I run 6.1.0 from applications folder, and try to "check for update", it thinks it's not in applications folder and tells me to move it inside.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/2063957/28998674-df4eeb62-7a39-11e7-9e9b-ac791d8b29ba.png)

MacOS version: 10.12.6 (16G29)
Using on Macbook Air Mid 13 if that would matter.

Thank you for maintaining such an awesome app and server.

Thanks in advance,

**Comment by freeplant** [comment]
We use a third party auto-upgrade tool. This problem is rare and is beyond our scope to fix.
