### ISSUE TITLE
Handle leak in Windows Explorer Extension

### ISSUE THREAD

**Issue by yyjdelete** [haiwen/seafile-client#976]
The leak code:(Not call predefined function in `registry.cpp` and `parent_key` is not closed by `RegCloseKey` when finished), used by shell
https://github.com/haiwen/seafile-client/blob/8f10ec5addb01da10453687ca8d0603a72ebdbc5/extensions/ext-utils.cpp#L481

What's more:(`parent_key` is not closed by `RegCloseKey` when finished), lucky it's only used when uninstall.
https://github.com/haiwen/seafile-client/blob/8f10ec5addb01da10453687ca8d0603a72ebdbc5/src/utils/registry.cpp#L112

Also reported as https://bbs.seafile.com/t/seafile-6-1-0-win10-16257-x64-explorer/4133

**Comment by lins05** [comment]
Thanks for the reporting! We'll fix it soon!
