### ISSUE TITLE
[New Feature] LAN Sync

### ISSUE THREAD

**Issue by TakeMeNL** [haiwen/seafile-client#981]
Hey guys,
I was just thinking what does it need to make the client app a bit better. And then i came to me.
LAN Sync, What is LAN sync?
Well its not new, and dropbox has build such thing in there app, info here https://www.dropbox.com/help/syncing-uploads/lan-sync-overview.

But is a nice feature, because you don't have to redownload all the files from the server if there is a other devices with that on the network. This saves bandwidth and is generally speaking quite faster than internet downloading.  

Let me know what you guys think.

**Comment by freeplant** [comment]
Implementing LAN sync is too complicated in self-hosted servers. We don't have such a development plan.
