### ISSUE TITLE
"failed to check server information" using Seafile Pro Edition

### ISSUE THREAD

**Issue by Dinawhk** [haiwen/seafile-client#982]
I'm using this client with Seafile Community Edition with no problem.
Today I've set an istance of Seafile Pro Edition (free up to 3 users) on my server with Docker (https://github.com/xama5/docker-seafile-pro). Everything works well except the windows client.
It is able to fetch the list of libraries, but is unable to sync any of them cause "Failed to check server information".
In the meantine the andoid client works well and it's able to upload and sync photos.

**Comment by killing** [comment]
Can you check seafile.log on the client?

**Comment by Dinawhk** [comment]
[09/04/17 16:59:45] clone-mgr.c(857): Transition clone state for 2ff44d40 from [check server] to [error]: check server.[09/04/17 16:59:49] clone-mgr.c(840): Transition clone state for 2ff44d40 from [error] to [check server].[09/04/17 16:59:50] http-tx-mgr.c(1236): Bad response code for GET http://[IP]:[PORT]/seafhttp/protocol-version: 404.I've hidden ip and port.
          
            
            On set 4 2017, at 3:44 pm, Jiaqiang Xu <notifications@github.com> wrote:
            
            
              Can you check seafile.log on the client?

**Comment by mustafasezgin** [comment]
Im having this problem too. I think its because the client is looking for the path based on the seafhttp value but I have a custom value setup with on the server side. There does not seem to be a way configure this value in the client whereas you can in the mobile clients.

**Comment by mustuhfa** [comment]
Could this be happening as a result of deploying the server at a noon root directory (e.g /opt/seafile-server-latest) and not following the steps on the following [page](https://manual.seafile.com/deploy/deploy_seahub_at_non-root_domain.html)?

**Comment by shoeper** [comment]
Have you kept the following in mind?

> Please note that the file server path will still be e.g. www.example.com/seafhttp (rather than www.example.com/seafile/seafhttp) because this path is hardcoded in the clients.

**Comment by mustafasezgin** [comment]
So then the solution here is to make the clientside configurable no? Otherwise this enabled people to randomly scan for that URL on google and find the servers. I should be able to customise the client and backend to still work.

I actually tried looking for the code on the client where this is hardcoded so I could submit a patch but have not had any luck so far

**Comment by monkeydri** [comment]
same issue here.

Seafile sever v6.2 setup an non-root domain (https://domain.com/seafile) behind an nginx reverse-proxy with seafile cinfigured according to the [docs](https://manual.seafile.com/deploy/deploy_seahub_at_non-root_domain.html) and nginx configuration described here : https://monkeydri.github.io/posts/seafile-https-nginx-reverse-proxy/

Client `seafile-gui` & `seafile-daemon` 6.1.5-1 on Ubuntu 18.04

Seafile Client is trying to access  `/seafhttp` instread of  `/sefile/seafhttp`. nginx `access.log` :

`192.168.1.9 - - [21/May/2018:10:00:56 +0200] "GET /seafhttp/protocol-version HTTP/1.1" 200 988 "-" "Seafile/6.1.5 (Linux)"`

**Comment by shoeper** [comment]
> Seafile Client is trying to access /seafhttp instread of /sefile/seafhttp

This is exactly what you can read in the docs.

**Comment by monkeydri** [comment]
Yes I did see your previous post, however to me the client should use the URL configured in the settings as the base path.

**Comment by shoeper** [comment]
It's not only my post. It's the documented behavior.

**Comment by monkeydri** [comment]
I understood your post was quoting the official doc (it is also quoted in the blog post I mentioned https://monkeydri.github.io/posts/seafile-https-nginx-reverse-proxy/), what I don't understand is why seafile-client is not using the full seafile server URL provided but just the domain part for seafhttp.
