### ISSUE TITLE
Issue with right click options

### ISSUE THREAD

**Issue by alexander-cristian-sphs** [haiwen/seafile-client#983]
Hello,

I have issues with my seafile client, on mac and on windows. Randomly when I try to copy file the right click options when I try to paste dissapear. Checked the logs and there is nothing there. What can this be and how can I resolve it? 

Thanks!

**Comment by georgeguta** [comment]
Hello,

I have the same issue. Can anyone check this

Thank you

**Comment by georgeguta** [comment]
Hello, Anyone can loook into this problem ? Still didn't receive an answer. Thank you very much.
