### ISSUE TITLE
macOS client using discrete GPU

### ISSUE THREAD

**Issue by Illule** [haiwen/seafile-client#984]
Seafile client seems to use discrete GPU.  In activity monitor, _Requires high performance GPU_ is marked yes. Doing so it drains battery.

System
-------

* macOS Sierra (up to date)
* MacBook Pro 15" 2015

**Comment by lins05** [comment]
What's the seafile client version you're using? Can you try to use an older version (e.g. [v6.0.7](https://download.seadrive.org/seafile-client-6.0.7.dmg)) and compare?

Thanks for reporting this.

**Comment by Illule** [comment]
I am using the version 6.1.0. I have just tried with the version 6.0.7 you linked me it does not use the discrete GPU.

Thanks for addressing this the issue

**Comment by mpsrig** [comment]
Having the same issue

**Comment by mpsrig** [comment]
Seems related to https://github.com/haiwen/seafile/commit/bea10fe68c4936ddfcb648291835009b75fbff9b

**Comment by jokey2k** [comment]
Did not change in 6.1.1 so must be something else... iStat Menus reports "seafile-applet" being the reason.

**Comment by mattmyne** [comment]
Same here, running macbook pro and macOS sierra 10.12.6. iStat menus also reporting "seafile-applet" as requesting discrete GPU. Confirmed by "About this Mac" now showing AMD Radeon in use, when it would normally be lower-power integrated Intel Iris (as not running any other GPU-intensive applications). This should be a priority fix for any macbook users - might even be worth uninstalling until fixed if battery life is important for you.

**Comment by ehoppmann** [comment]
FYI to anyone who is suffering from this issue, as I mentioned in https://github.com/haiwen/seafile/issues/1967 (sorry for not creating the issue on the client repo, and not realizing it was a duplicate!), it's possible to fix the Seafile package yourself until a fix makes it into a release. All that is required is opening up the Info.plist file inside `Seafile Client.app` and setting the key `NSSupportsAutomaticGraphicsSwitching` to `true`.

**Comment by mattmyne** [comment]
Good find @ehoppmann! Is this fix planned for the next release?

**Comment by freeplant** [comment]
@lins05 Please look into the problem. @ehoppmann Thank you very much for the hint.
