### ISSUE TITLE
Ubuntu 17.10 seafile-gui PPA error:

### ISSUE THREAD

**Issue by falkowich** [haiwen/seafile-client#987]
I know that this is a moving target with 17.10 and such.
But it looks like libevent has been updated in 17.10 repos and seafile-gui from PPA wont install anymore.

This is what is installed with 17.10:
```
falk@broekn-notepad:~/src$ dpkg -l | grep libevent
ii  libevent-2.1-6:amd64                       2.1.8-stable-4                              amd64        Asynchronous event notification library

```

Error from installation below.
```
falk@broekn-notepad:~/src$ sudo apt install seafile-gui
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 seafile-gui : Depends: libevent-2.0-5 (>= 2.0.10-stable) but it is not installable
               Depends: seafile-daemon (>= 5.1.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.


```

**Comment by digital-spinner** [comment]
Yep, same issue on relased today official 17.10.. Could not use the Seafile GUI client anymore :(

**Comment by theliquid** [comment]
Same here! A shame that this doesn't get picked up by devs, since I think its easy to fix.

**Comment by jhonny-oliveira** [comment]
Same here!

**Comment by dutt** [comment]
Here too. Can I do anything to help fix it?

**Comment by Jip-Hop** [comment]
I'm having this issue too on Lubuntu 17.10. The GUI client was actually working for a while. But I suppose running apt-get upgrade broke it.

**Comment by Lyca-Knight** [comment]
same here.. not working anymore. Any workaround?

**Comment by PlaidPhantom** [comment]
I am having this issue as well.

**Comment by lins05** [comment]
It should have been fixed by now, please try again.

**Comment by falkowich** [comment]
Hi @lins05.
I can confirm that you have fixed the packet.
Thanks for the feedback and fix!

--
Regards Falk
