### ISSUE TITLE
Invalid "Storage quota full"

### ISSUE THREAD

**Issue by benruijl** [haiwen/seafile-client#990]
When at some point a file is created in a repository that will cause the size of the directory to exceed the storage quotum, this error cannot be undone by removing the file.

Even after removal, the status will remain that the storage quota is exceeded. The only way to fix it, is to remove the .seafile-data directory.

**Comment by freeplant** [comment]
This is because the file are indexed into the internal folder before upload.

**Comment by benruijl** [comment]
I don't understand why you closed the issue. Surely it is not a feature that I am forced to delete the internal folder and start from scratch?

Deleting the file in the repository should also delete it in the internal folder.

**Comment by ehoppmann** [comment]
This is still an issue and really should be resolved, as this behavior is counter to what any user of the software would expect (and most non-technical users would be unable to resolve on their own). Can you re-open this issue @freeplant ?

**Comment by BigAndini** [comment]
I encounter this problem as well. The library is 50G large, but single files only up to 300MB. A user with a quota of 10G who was invited to this library is not able to use it properly.

**Comment by lumaalvinho** [comment]
This problem persists. After copying a file that exceeded the available quota, the message "Storage quota full" was always active. The only solution was to delete the folder from the server and re-upload within the available quota.
