### ISSUE TITLE
Title bar on Wayland is not working as expected

### ISSUE THREAD

**Issue by poofeg** [haiwen/seafile-client#991]
On Wayland session:
* Title bar can't move the window
* The minimize button is not working
* Window have no icon in taskbar
![image](https://user-images.githubusercontent.com/586294/31532363-3d9e9a6c-b006-11e7-9a35-1f2c070409c3.png)

System:
* Kubuntu 17.04 with backports
* KDE Plasma: 5.10.5
* Qt: 5.7.1

**Comment by HenriWahl** [comment]
With latest Fedora 31 and Qt 5.12.5 I have the same problem.

I assume the cause is that on Wayland windows are not allowed to move themselves?

**Comment by scyptnex** [comment]
Adding to this:

This reprodicuces also on:
 - ChromeOS Crostini+Sommelier
 - Weston

FWIW weston is the reference compositor so any bug on weston is a bug in seafile-gui

> I assume the cause is that on Wayland windows are not allowed to move themselves?

This is not true, GTK3+ apps are native wayland and can move themselves (e.g. gedit), as can several other apps running under XWayland (i.e. x11 apps) with client side decorations (e.g. vscode)

This bug was reported to chromeos as https://bugs.chromium.org/p/chromium/issues/detail?id=1026693

**Comment by HenriWahl** [comment]
@scyptnex are you sure they can move themselves? I do not mean they can be moved by the user.

 I know of [Nagstamon](https://github.com/HenriWahl/Nagstamon) which is a Qt5 app like Seafile and there is the same probleme arising when being run natively under GNOME Wayland as Wayland app. Position of the window cann not be defined by the app.

**Comment by scyptnex** [comment]
in general WL clients aren't allowed to control their location on the desktop (other than, e.g. "make me maximized")

One way they can indicate that the user is trying to move them is here:
https://github.com/wayland-project/wayland-protocols/blob/6d0fc7065633d6056602623c9ab8376db306ec2e/stable/xdg-shell/xdg-shell.xml#L639

If this is also an issue with other Qt5 apps then seafile might want to file this bug against Qt, other toolkits like GTK3 do not have this issue running native WL clients (e.g. geddit, sublime3)

**Comment by erenoglu** [comment]
Very annoying issue, seafile window is stuck in the middle of my screen.

**Comment by jknaus** [comment]
I found a workaround:
- Create a copy of `/usr/local/share/applications/seafile.desktop` in `~/.local/share/applications/`
- Within that copy change the line`Exec=seafile-applet` into `Exec=seafile-applet -platform xcb`
- don't forget to do this also for the .desktop-file in `~/.config/autostart/` if you want the seafile client to automatically start at login.

This enforces qt5 apps to use x (xwayland) inside a wayland session.

**Comment by alpemwarrior** [comment]
From my understanding on wayland windows don't move themselves, rather they are moved by the compositor. On Gnome you can make it move by holding super and then dragging the window. It seems to me that perhaps seafile doesn't communicate properly what surfaces can be grabbed? This is most definitely not a wayland bug, however.

**Comment by alpemwarrior** [comment]
FYI, I've posted a PR with a proper fix in #1422 if anyone wants to test.
