### ISSUE TITLE
Service discover via SRV record

### ISSUE THREAD

**Issue by samsk** [haiwen/seafile-client#994]
It would be great if seafile client(s) could perform **server address discovery via SRV record** - see https://en.wikipedia.org/wiki/SRV_record

Instead of entering server+email/user+password, user could alternatively enter only email+password. Seafile client would then perform SRV discovery on user's email domain, and 'autocomplete' server address.

With this, connection setup to a seafile server would become extremely easy for anyone.

**Comment by shoeper** [comment]
It's a great idea.

**Comment by freeplant** [comment]
We don't have a plan to add such feature.
