### ISSUE TITLE
State barely visible with new tray icon (6.1.2 - windows)

### ISSUE THREAD

**Issue by 92lleo** [haiwen/seafile-client#997]
With the new tray icon it's hard to distinguish if seafile is in sync or paused, please revert to the old icon or don't use the same color for the inner seafile logo and the sync state icon
____
edit: screenshot added
![seafile_tray](https://user-images.githubusercontent.com/12110344/32186573-b4dc2366-bda2-11e7-83af-cd396a5f166f.png)
![seafile_tray_2](https://user-images.githubusercontent.com/12110344/32186629-d947987a-bda2-11e7-9b91-cc2abe66061a.png)
It may be not that hard to see with the screenshots, but it is with other icons in the tray

**Comment by freeplant** [comment]
Thanks for reporting the issue.

**Comment by freeplant** [comment]
It is fixed. It will be included in the next release.
